# Generated by Django 6.1 on 2026-08-20 09:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=50, null=True, verbose_name='លេខកូដ ISBN / Book Code')),
                ('title', models.CharField(max_length=200, verbose_name='ចំណងជើងសៀវភៅ / Book Title')),
                ('author', models.CharField(blank=True, max_length=150, null=True, verbose_name='អ្នកនិពន្ធ / Author')),
                ('category', models.CharField(default='General', max_length=100, verbose_name='ប្រភេទសៀវភៅ / Category')),
                ('quantity', models.IntegerField(default=1, verbose_name='ចំនួនសរុប / Total Quantity')),
                ('available_quantity', models.IntegerField(default=1, verbose_name='ចំនួននៅសល់ / Available Quantity')),
                ('shelf_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='ទីតាំងធ្នើសៀវភៅ / Shelf Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'សៀវភៅបណ្ណាល័យ / Library Book',
                'verbose_name_plural': 'សៀវភៅបណ្ណាល័យទាំងអស់ / Library Books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True, verbose_name='កូដសម្ភារៈ / Item Code')),
                ('name', models.CharField(max_length=150, verbose_name='ឈ្មោះសម្ភារៈ / Item Name')),
                ('category', models.CharField(choices=[('UNIFORM', 'ឯកសណ្ឋានសាលា / Uniform'), ('TEXTBOOK', 'សៀវភៅពុម្ព / Textbooks'), ('STATIONERY', 'សម្ភារៈសិក្សា / Stationery'), ('EQUIPMENT', 'ឧបករណ៍ & សម្ភារៈបង្រៀន / Equipment'), ('OTHER', 'ផ្សេងៗ / Other')], default='UNIFORM', max_length=30, verbose_name='ប្រភេទ / Category')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='តម្លៃឯកតា ($) / Unit Price')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='ចំនួនក្នុងស្តុក / Stock Quantity')),
                ('min_alert_level', models.IntegerField(default=10, verbose_name='កម្រិតផ្តល់ដំណឹងជិតអស់ / Min Alert Level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ស្តុកសម្ភារៈ / Inventory Item',
                'verbose_name_plural': 'ស្តុកសម្ភារៈទាំងអស់ / Inventory Items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BookBorrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True, verbose_name='ថ្ងៃខ្ចី / Borrow Date')),
                ('due_date', models.DateField(verbose_name='ថ្ងៃត្រូវសង / Due Date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='ថ្ងៃបានសង / Return Date')),
                ('status', models.CharField(choices=[('BORROWED', 'កំពុងខ្ចី / Borrowed'), ('RETURNED', 'សងរួចរាល់ / Returned'), ('OVERDUE', 'ហួសកំណត់ / Overdue')], default='BORROWED', max_length=20, verbose_name='ស្ថានភាព / Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='កំណត់ចំណាំ / Notes')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='extras.book', verbose_name='សៀវភៅ / Book')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_books', to='students.student', verbose_name='សិស្សខ្ចី / Student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_books', to='teachers.teacher', verbose_name='គ្រូខ្ចី / Teacher')),
            ],
            options={
                'verbose_name': 'ការខ្ចី-សងសៀវភៅ / Book Borrowing',
                'verbose_name_plural': 'ការខ្ចី-សងសៀវភៅទាំងអស់ / Book Borrowings',
                'ordering': ['-borrow_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'នាំចូលស្តុក / Stock In'), ('SALE_OUT', 'លក់/ចែកជូនសិស្ស / Sale Out'), ('ADJUSTMENT', 'កែសម្រួលស្តុក / Stock Adjustment')], default='SALE_OUT', max_length=20, verbose_name='ប្រភេទប្រតិបត្តិការ / Type')),
                ('quantity', models.IntegerField(verbose_name='ចំនួន / Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='តម្លៃឯកតា ($) / Unit Price')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទ / Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='កំណត់ចំណាំ / Notes')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='extras.inventoryitem', verbose_name='សម្ភារៈ / Item')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student', verbose_name='សិស្សទិញ / Student')),
            ],
            options={
                'verbose_name': 'ប្រតិបត្តិការស្តុក / Inventory Transaction',
                'verbose_name_plural': 'ប្រតិបត្តិការស្តុកទាំងអស់ / Inventory Transactions',
                'ordering': ['-date'],
            },
        ),
    ]
