# Generated by Django 6.1 on 2026-08-20 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ចំណងជើងសេចក្តីជូនដំណឹង / Announcement Title')),
                ('category', models.CharField(choices=[('GENERAL', 'ដំណឹងទូទៅ / General Notice'), ('PARENT_MEETING', 'ការប្រជុំមាតាបិតា / Parent Meeting'), ('HOLIDAY', 'ថ្ងៃឈប់សម្រាកបុណ្យ / Holiday Notice'), ('EXAM_SCHEDULE', 'កាលវិភាគប្រឡង / Exam Schedule'), ('EVENT', 'ព្រឹត្តិការណ៍ & កម្មវិធីសាលា / School Event')], default='GENERAL', max_length=30, verbose_name='ប្រភេទ / Category')),
                ('target_audience', models.CharField(choices=[('ALL', 'ទាំងអស់គ្នា (All Users)'), ('TEACHERS', 'គ្រូបង្រៀន (Teachers Only)'), ('STUDENTS_PARENTS', 'សិស្ស & មាតាបិតា (Students & Parents)'), ('PARENTS_ONLY', 'មាតាបិតាសិស្ស (Parents Only)')], default='ALL', max_length=30, verbose_name='ក្រុមគោលដៅ / Target Audience')),
                ('priority', models.CharField(choices=[('NORMAL', 'ធម្មតា (Normal)'), ('IMPORTANT', 'សំខាន់ (Important)'), ('URGENT', 'បន្ទាន់ (Urgent)')], default='NORMAL', max_length=20, verbose_name='កម្រិតអាទិភាព / Priority')),
                ('content', models.TextField(verbose_name='ខ្លឹមសារលម្អិត / Content')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/docs/', verbose_name='ឯកសារភ្ជាប់ / Attachment')),
                ('is_published', models.BooleanField(default=True, verbose_name='ផ្សាយជាសាធារណៈ / Is Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទផ្សាយ / Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកបង្កើត / Created By')),
            ],
            options={
                'verbose_name': 'សេចក្តីជូនដំណឹង / Announcement',
                'verbose_name_plural': 'សេចក្តីជូនដំណឹងទាំងអស់ / Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
