# Generated by Django 6.1 on 2026-09-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='ខ្លឹមសារភាសាអង់គ្លេស / English Content'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ចំណងជើងភាសាអង់គ្លេស / English Title'),
        ),
    ]
