# Generated by Django 6.1 on 2026-08-20 09:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ចំណងជើង / Title')),
                ('message', models.TextField(verbose_name='ខ្លឹមសារសារ / Message')),
                ('recipient_type', models.CharField(default='Parent', max_length=50, verbose_name='អ្នកទទួល / Recipient Type')),
                ('recipient_name', models.CharField(max_length=150, verbose_name='ឈ្មោះអ្នកទទួល / Recipient Name')),
                ('recipient_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='លេខទូរស័ព្ទ / Phone')),
                ('channel', models.CharField(choices=[('TELEGRAM', 'Telegram Bot'), ('SYSTEM', 'System Alert'), ('SMS', 'SMS Gateway')], default='TELEGRAM', max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'ផ្ញើរួច / Sent'), ('SIMULATED', 'គំរូសាកល្បង / Simulated'), ('FAILED', 'បរាជ័យ / Failed')], default='SIMULATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទ / Date')),
            ],
            options={
                'verbose_name': 'កំណត់ត្រាការជូនដំណឹង / Notification Log',
                'verbose_name_plural': 'កំណត់ត្រាការជូនដំណឹង / Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Bot Token')),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Default Channel / Chat ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='បើកដំណើរការ / Is Active')),
                ('notify_on_absence', models.BooleanField(default=True, verbose_name='ជូនដំណឹងអវត្តមាន / Absence Alert')),
                ('notify_on_exam', models.BooleanField(default=True, verbose_name='ជូនដំណឹងពិន្ទុ / Exam Results Alert')),
                ('notify_on_fee', models.BooleanField(default=True, verbose_name='ជូនដំណឹងបង់ប្រាក់ / Fee Due Alert')),
            ],
            options={
                'verbose_name': 'ការកំណត់ Telegram / Telegram Config',
                'verbose_name_plural': 'ការកំណត់ Telegram / Telegram Configs',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Super Admin / អ្នកគ្រប់គ្រងប្រព័ន្ធ'), ('ACCOUNTANT', 'Accountant / គណនេយ្យករ'), ('TEACHER', 'Teacher / គ្រូបង្រៀន'), ('STUDENT', 'Student/Parent / សិស្ស-អាណាព្យាបាល')], default='ADMIN', max_length=20, verbose_name='តួនាទី / Role')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='លេខទូរស័ព្ទ / Phone')),
                ('khmer_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះខ្មែរ / Khmer Name')),
                ('latin_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះឡាតាំង / Latin Name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='រូបថត / Avatar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
