# Generated by Django 6.1 on 2026-08-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kh', models.CharField(default='វិទ្យាល័យអន្តរជាតិ សាលារៀន SM', max_length=200, verbose_name='ឈ្មោះសាលា (ខ្មែរ) / School Name (Khmer)')),
                ('name_en', models.CharField(default='SchoolSM International High School', max_length=200, verbose_name='ឈ្មោះសាលា (ឡាតាំង/អង់គ្លេស) / School Name (English)')),
                ('short_name', models.CharField(default='សាលារៀន SM', max_length=100, verbose_name='ឈ្មោះកាត់សាលា / Short Name')),
                ('school_code', models.CharField(default='080101', max_length=50, verbose_name='លេខកូដសាលា / EMIS School Code')),
                ('school_type', models.CharField(default='វិទ្យាល័យ / General High School', max_length=100, verbose_name='កម្រិត/ប្រភេទសាលា / School Level & Type')),
                ('motto', models.CharField(blank=True, default='ចំណេះដឹង វិន័យ សីលធម៌ គុណធម៌', max_length=255, verbose_name='បាវចនាសាលា / School Motto')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/', verbose_name='រូបសញ្ញាសាលា (Logo) / School Logo')),
                ('seal', models.ImageField(blank=True, null=True, upload_to='school/', verbose_name='ត្រាសាលាផ្លូវការ / Official Stamp & Seal')),
                ('principal_signature', models.ImageField(blank=True, null=True, upload_to='school/', verbose_name='ហត្ថលេខានាយកសាលា / Principal Signature')),
                ('ministry_name', models.CharField(default='ក្រសួងអប់រំ យុវជន និងកីឡា', max_length=200, verbose_name='ក្រសួងសាមី / Ministry Name')),
                ('poe_name', models.CharField(default='មន្ទីរអប់រំ យុវជន និងកីឡា រាជធានីភ្នំពេញ', max_length=200, verbose_name='មន្ទីរអប់រំ / Provincial/Municipal Dept of Education (PoE)')),
                ('doe_name', models.CharField(blank=True, default='ការិយាល័យអប់រំ យុវជន និងកីឡា ខណ្ឌដូនពេញ', max_length=200, verbose_name='ការិយាល័យអប់រំ / District Office of Education (DoE)')),
                ('province', models.CharField(default='រាជធានីភ្នំពេញ', max_length=100, verbose_name='រាជធានី/ខេត្ត / Province/City')),
                ('district', models.CharField(default='ខណ្ឌដូនពេញ', max_length=100, verbose_name='ក្រុង/ស្រុក/ខណ្ឌ / District/Khan')),
                ('commune', models.CharField(default='សង្កាត់វត្តភ្នំ', max_length=100, verbose_name='ឃុំ/សង្កាត់ / Commune/Sangkat')),
                ('village', models.CharField(blank=True, default='ភូមិ១', max_length=100, verbose_name='ភូមិ / Village')),
                ('street_address', models.CharField(blank=True, default='មហាវិថីព្រះនរោត្តម សង្កាត់វត្តភ្នំ', max_length=255, verbose_name='អាសយដ្ឋានលម្អិត / Street Address')),
                ('principal_name', models.CharField(default='លោកបណ្ឌិត សុខ ចាន់ថន', max_length=150, verbose_name='ឈ្មោះនាយក/នាយិកាសាលា / Principal Name')),
                ('phone', models.CharField(default='023 888 999 / 012 345 678', max_length=100, verbose_name='លេខទូរស័ព្ទ / Phone Number')),
                ('email', models.EmailField(blank=True, default='info@schoolsm.edu.kh', max_length=254, verbose_name='អ៊ីមែល / Email Address')),
                ('website', models.CharField(blank=True, default='https://schoolsm.edu.kh', max_length=200, verbose_name='គេហទំព័រ / Website')),
                ('facebook_page', models.CharField(blank=True, default='https://facebook.com/schoolsm', max_length=200, verbose_name='ទំព័រហ្វេសប៊ុក / Facebook Page')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='កែប្រែចុងក្រោយ / Updated At')),
            ],
            options={
                'verbose_name': 'ព័ត៌មានសាលារៀន / School Profile',
                'verbose_name_plural': 'ព័ត៌មានសាលារៀន / School Profile',
            },
        ),
    ]
