# Generated by Django 6.1 on 2026-08-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_schoolprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Super Admin / អ្នកគ្រប់គ្រងប្រព័ន្ធ'), ('ACCOUNTANT', 'Accountant / គណនេយ្យករ'), ('TEACHER', 'Teacher / គ្រូបង្រៀន'), ('STUDENT', 'Student/Parent / សិស្ស-អាណាព្យាបាល')], max_length=20, verbose_name='តួនាទី / Role')),
                ('menu_key', models.CharField(max_length=100, verbose_name='កូដម៉ឺនុយ / Menu Key')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='អនុញ្ញាត / Is Allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'សិទ្ធិម៉ឺនុយតាមតួនាទី / Role Menu Permission',
                'verbose_name_plural': 'សិទ្ធិម៉ឺនុយតាមតួនាទី / Role Menu Permissions',
                'indexes': [models.Index(fields=['role', 'menu_key'], name='accounts_ro_role_ccf839_idx')],
                'unique_together': {('role', 'menu_key')},
            },
        ),
    ]
