# Generated by Django 6.1 on 2026-08-25 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rolemenupermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='កូដផ្នែក / Section Code')),
                ('name_kh', models.CharField(max_length=150, verbose_name='ឈ្មោះខ្មែរ / Name (Khmer)')),
                ('name_en', models.CharField(max_length=150, verbose_name='ឈ្មោះឡាតាំង / Name (English)')),
                ('icon', models.CharField(default='fa-solid fa-folder', max_length=100, verbose_name='រូបតំណាង / Icon Class')),
                ('color', models.CharField(default='secondary', max_length=50, verbose_name='ពណ៌ / Color Class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='លំដាប់លំដោយ / Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='បើកដំណើរការ / Is Active')),
                ('is_system', models.BooleanField(default=False, verbose_name='ប្រព័ន្ធដើម / Is System')),
                ('default_roles', models.CharField(default='ADMIN,TEACHER,STUDENT,ACCOUNTANT', max_length=255, verbose_name='តួនាទីលំនាំដើម / Default Roles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ផ្នែកម៉ឺនុយ / Menu Section',
                'verbose_name_plural': 'ផ្នែកម៉ឺនុយ / Menu Sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='កូដម៉ឺនុយ / Submenu Code')),
                ('name_kh', models.CharField(max_length=150, verbose_name='ឈ្មោះខ្មែរ / Name (Khmer)')),
                ('name_en', models.CharField(max_length=150, verbose_name='ឈ្មោះឡាតាំង / Name (English)')),
                ('icon', models.CharField(default='fa-solid fa-circle-dot', max_length=100, verbose_name='រូបតំណាង / Icon Class')),
                ('url_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ឈ្មោះ URL (Django URL Name)')),
                ('custom_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL ផ្ទាល់ / Custom URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='លំដាប់លំដោយ / Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='បើកដំណើរការ / Is Active')),
                ('is_admin_only', models.BooleanField(default=False, verbose_name='សម្រាប់តែ Admin / Admin Only')),
                ('is_system', models.BooleanField(default=False, verbose_name='ប្រព័ន្ធដើម / Is System')),
                ('default_roles', models.CharField(default='ADMIN', max_length=255, verbose_name='តួនាទីលំនាំដើម / Default Roles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.menusection', verbose_name='ផ្នែកម៉ឺនុយ / Section')),
            ],
            options={
                'verbose_name': 'ម៉ឺនុយរង / Menu Item',
                'verbose_name_plural': 'ម៉ឺនុយរង / Menu Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
