# Generated by Django 6.1 on 2026-08-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_menusection_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='education_levels',
            field=models.CharField(default='មត្តេយ្យ, បឋមសិក្សា, អនុវិទ្យាល័យ, វិទ្យាល័យ', max_length=255, verbose_name='កម្រិតសិក្សា / Education Levels'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='google_maps_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Link ផែនទី Google Maps'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='gps_radius_meters',
            field=models.PositiveIntegerField(default=100, verbose_name='រង្វង់សុពលភាព GPS (Geofencing Radius - Meters)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='institution_type',
            field=models.CharField(choices=[('PUBLIC', 'សាលារដ្ឋ / Public School'), ('PRIVATE', 'សាលាឯកជន / Private School'), ('INTERNATIONAL', 'សាលាអន្តរជាតិ / International School'), ('NGO', 'អង្គការមិនមែនរដ្ឋាភិបាល / NGO School')], default='PUBLIC', max_length=30, verbose_name='ប្រភេទគ្រឹះស្ថាន / Institution Type'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='latitude',
            field=models.FloatField(default=11.5564, verbose_name='រយៈទទឹង GPS (Latitude)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='longitude',
            field=models.FloatField(default=104.9282, verbose_name='រយៈបណ្តោយ GPS (Longitude)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='telegram_channel',
            field=models.CharField(blank=True, max_length=200, verbose_name='Telegram Channel / Group សាលា'),
        ),
    ]
