# Generated by Django 6.1 on 2026-08-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_schoolprofile_education_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='education_levels',
            field=models.CharField(blank=True, default='មត្តេយ្យ, បឋមសិក្សា, អនុវិទ្យាល័យ, វិទ្យាល័យ', max_length=255, verbose_name='កម្រិតសិក្សា / Education Levels'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='gps_radius_meters',
            field=models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='រង្វង់សុពលភាព GPS (Geofencing Radius - Meters)'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('PUBLIC', 'សាលារដ្ឋ / Public School'), ('PRIVATE', 'សាលាឯកជន / Private School'), ('INTERNATIONAL', 'សាលាអន្តរជាតិ / International School'), ('NGO', 'អង្គការមិនមែនរដ្ឋាភិបាល / NGO School')], default='PUBLIC', max_length=30, verbose_name='ប្រភេទគ្រឹះស្ថាន / Institution Type'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='latitude',
            field=models.FloatField(blank=True, default=11.5564, null=True, verbose_name='រយៈទទឹង GPS (Latitude)'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='longitude',
            field=models.FloatField(blank=True, default=104.9282, null=True, verbose_name='រយៈបណ្តោយ GPS (Longitude)'),
        ),
    ]
