# Generated by Django 6.1 on 2026-08-28 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_schoolprofile_education_levels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='ខ្លឹមសារសារ / Message Content')),
                ('category', models.CharField(choices=[('profile_correction', 'ស្នើសុំកែប្រែព័ត៌មានអត្តសញ្ញាណ'), ('general_inquiry', 'សាកសួររដ្ឋបាល/ប្រាក់ខែ'), ('technical_help', 'បញ្ហាបច្ចេកទេស'), ('admin_response', 'សារឆ្លើយតបពីរដ្ឋបាល'), ('other', 'សារទូទៅ')], default='profile_correction', max_length=50, verbose_name='ប្រភេទសារ / Category')),
                ('is_from_admin', models.BooleanField(default=False, verbose_name='ផ្ញើដោយ Admin / From Admin')),
                ('is_read', models.BooleanField(default=False, verbose_name='បានអាន / Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទ / Created At')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកទទួល / Recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកផ្ញើ / Sender')),
            ],
            options={
                'verbose_name': 'សារជជែកផ្ទាល់ / Direct Chat Message',
                'verbose_name_plural': 'សារជជែកផ្ទាល់ / Direct Chat Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
