# Generated by Django 6.1 on 2026-08-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_directchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='directchatmessage',
            name='voice_duration',
            field=models.IntegerField(default=0, verbose_name='រយៈពេលសំឡេង (វិនាទី) / Duration (seconds)'),
        ),
        migrations.AddField(
            model_name='directchatmessage',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_voice/', verbose_name='ឯកសារសំឡេង / Voice File'),
        ),
        migrations.AlterField(
            model_name='directchatmessage',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='ខ្លឹមសារសារ / Message Content'),
        ),
    ]
