# Generated by Django 6.1 on 2026-08-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_directchatmessage_voice_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramconfig',
            name='auto_backup_enabled',
            field=models.BooleanField(default=True, verbose_name='បើកដំណើរការ Auto Backup ស្វ័យប្រវត្តិតាមម៉ោង'),
        ),
        migrations.AddField(
            model_name='telegramconfig',
            name='backup_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Chat ID ជាក់លាក់សម្រាប់ Backup'),
        ),
        migrations.AddField(
            model_name='telegramconfig',
            name='backup_day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ចន្ទ / Mon'), (1, 'អង្គារ / Tue'), (2, 'ពុធ / Wed'), (3, 'ព្រហស្បតិ៍ / Thu'), (4, 'សុក្រ / Fri'), (5, 'សៅរ៍ / Sat'), (6, 'អាទិត្យ / Sun')], default=6, verbose_name='ថ្ងៃក្នុងសប្តាហ៍សម្រាប់ Weekly Backup'),
        ),
        migrations.AddField(
            model_name='telegramconfig',
            name='backup_format',
            field=models.CharField(choices=[('json', 'Full JSON Dump (.json)'), ('sqlite3', 'Live SQLite Snapshot (.sqlite3)')], default='json', max_length=20, verbose_name='ទម្រង់ឯកសារ Backup'),
        ),
        migrations.AddField(
            model_name='telegramconfig',
            name='backup_frequency',
            field=models.CharField(choices=[('DAILY', 'រៀងរាល់ថ្ងៃ (Daily)'), ('WEEKLY', 'រៀងរាល់សប្តាហ៍ (Weekly)'), ('MONTHLY', 'រៀងរាល់ខែ (Monthly)')], default='DAILY', max_length=20, verbose_name='ប្រេកង់ Backup'),
        ),
        migrations.AddField(
            model_name='telegramconfig',
            name='backup_time',
            field=models.TimeField(default='00:00', verbose_name='ម៉ោងដែលត្រូវ Backup (Time of Day)'),
        ),
        migrations.AddField(
            model_name='telegramconfig',
            name='last_backup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទ Backup ស្វ័យប្រវត្តិចុងក្រោយ'),
        ),
    ]
