# Generated by Django 6.1 on 2026-09-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_telegramconfig_auto_backup_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('km', 'ភាសាខ្មែរ (Khmer)'), ('en', 'English')], default='km', max_length=10, verbose_name='ជម្រើសភាសា / Language Preference'),
        ),
    ]
