# Generated by Django 6.1 on 2026-09-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_language_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='date_format',
            field=models.CharField(blank=True, choices=[('dd-mm-yyyy', 'dd-mm-yyyy (ឧ. 02-09-2026) - លំនាំដើម'), ('dd/mm/yyyy', 'dd/mm/yyyy (ឧ. 02/09/2026)'), ('yyyy-mm-dd', 'yyyy-mm-dd (ឧ. 2026-09-02)'), ('dd.mm.yyyy', 'dd.mm.yyyy (ឧ. 02.09.2026)')], default='dd-mm-yyyy', max_length=20, verbose_name='ទម្រង់កាលបរិច្ឆេទ / Date Format'),
        ),
    ]
