# Generated by Django 6.1 on 2026-09-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_schoolprofile_time_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='student_id_custom_template',
            field=models.CharField(blank=True, default='{PREFIX}-{YEAR2}-{SEQ}', max_length=100, verbose_name='រូបមន្តអត្តលេខផ្ទាល់ខ្លួន (Custom Template)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='student_id_digits',
            field=models.PositiveSmallIntegerField(choices=[(4, '៤ ខ្ទង់ (ឧ. 0001)'), (5, '៥ ខ្ទង់ (ឧ. 00001)'), (6, '៦ ខ្ទង់ (ឧ. 000001)')], default=4, verbose_name='ចំនួនខ្ទង់លេខរៀងរត់ / Sequence Digits'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='student_id_include_grade',
            field=models.BooleanField(default=False, verbose_name='បញ្ចូលលេខកម្រិតថ្នាក់ក្នុងអត្តលេខ / Include Grade Level in ID'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='student_id_pattern',
            field=models.CharField(choices=[('YEAR_END_4D', 'ឆ្នាំបញ្ចប់ + លេខ ៤ ខ្ទង់ (ឧ. 270001) - ស្តង់ដារជាតិ MoEYS'), ('YEAR_END_5D', 'ឆ្នាំបញ្ចប់ + លេខ ៥ ខ្ទង់ (ឧ. 2700001)'), ('PREFIX_YEAR_4D', 'Prefix + ឆ្នាំបញ្ចប់ + លេខ ៤ ខ្ទង់ (ឧ. STU-27-0001)'), ('PREFIX_YEAR_5D', 'Prefix + ឆ្នាំបញ្ចប់ + លេខ ៥ ខ្ទង់ (ឧ. STU-27-00001)'), ('GRADE_YEAR_4D', 'កម្រិតថ្នាក់ + ឆ្នាំបញ្ចប់ + លេខ ៤ ខ្ទង់ (ឧ. 7-27-0001)'), ('CUSTOM_PATTERN', 'ទម្រង់ផ្ទាល់ខ្លួន (Custom Template) ឧ. {PREFIX}-{YEAR2}-{SEQ}')], default='YEAR_END_4D', max_length=50, verbose_name='ទម្រង់អត្តលេខសិស្ស / Student ID Pattern'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='student_id_prefix',
            field=models.CharField(blank=True, default='STU', max_length=20, verbose_name='អក្សរកាត់អត្តលេខ (Prefix)'),
        ),
    ]
