# Generated by Django 6.1 on 2026-09-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_schoolprofile_student_id_custom_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='body_bg_color',
            field=models.CharField(default='#f8fafc', max_length=20, verbose_name='ពណ៌ផ្ទៃទំព័រ (Page Background)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='display_font',
            field=models.CharField(choices=[('Kantumruy Pro', 'Kantumruy Pro (លំនាំដើម - ទំនើប ទាន់សម័យ)'), ('Khmer OS Siemreap', 'Khmer OS Siemreap (ស្តង់ដាររដ្ឋបាល MoEYS)'), ('Khmer OS Battambang', 'Khmer OS Battambang (ងាយអាន អក្សរមូលច្បាស់)'), ('Hanuman', 'Hanuman (ក្បូរក្បាច់ ស្រទន់ បុរាណ)'), ('Koh Santepheap', 'Koh Santepheap (ទាន់សម័យ ជ្រុងស្អាត)'), ('Noto Sans Khmer', 'Noto Sans Khmer (Google Standard)'), ('Nokora', 'Nokora (ស្រាល ស្រស់ស្អាត)')], default='Kantumruy Pro', max_length=100, verbose_name='ពុម្ពអក្សរទូទៅក្នុងប្រព័ន្ធ (Display Font)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='footer_bg_color',
            field=models.CharField(default='#0b1329', max_length=20, verbose_name='ពណ៌បាតទំព័រ Footer (Footer Background)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='header_bg_color',
            field=models.CharField(default='#0f172a', max_length=20, verbose_name='ពណ៌ក្បាលទំព័រ Header (Header Background)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='report_header_font',
            field=models.CharField(choices=[('Moul', 'Moul / Khmer OS Muol Light (ក្បាលលិខិត & របាយការណ៍ MoEYS)'), ('Kantumruy Pro', 'Kantumruy Pro Bold (ទំនើប)'), ('Khmer OS Battambang', 'Khmer OS Battambang Bold'), ('Khmer OS Siemreap', 'Khmer OS Siemreap Bold')], default='Moul', max_length=100, verbose_name='ពុម្ពអក្សរចំណងជើង & របាយការណ៍ (Report Header Font)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='theme_primary_color',
            field=models.CharField(default='#1e40af', max_length=20, verbose_name='ពណ៌ចម្បង (Primary Brand Color)'),
        ),
    ]
