# Generated by Django 6.1 on 2026-09-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_schoolprofile_body_bg_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='បើកដំណើរការ Google Sheets Sync')),
                ('admin_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gmail Admin សម្រាប់ទទួលសិទ្ធិមើលឯកសារ (Admin Only)')),
                ('service_account_json_path', models.CharField(blank=True, default='google_service_account.json', max_length=500, verbose_name='ទីតាំងឯកសារ JSON Credentials (Path)')),
                ('service_account_json_content', models.TextField(blank=True, null=True, verbose_name='ឬបិទភ្ជាប់ខ្លឹមសារ JSON Credentials ដោយផ្ទាល់')),
                ('drive_folder_name', models.CharField(default='SchoolSM_Cloud_Sync', max_length=200, verbose_name='ឈ្មោះ Folder លើ Google Drive')),
                ('drive_folder_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Google Drive Folder ID')),
                ('sync_students_with_photos', models.BooleanField(default=True, verbose_name='Upload រូបថតសិស្សទៅ Drive & បង្ហាញក្នុង Sheet (=IMAGE)')),
                ('spreadsheets_registry', models.JSONField(blank=True, default=dict, verbose_name='បញ្ជីតំណភ្ជាប់ Google Sheets តាមឆ្នាំសិក្សា')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទ Sync ចុងក្រោយ')),
                ('last_sync_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='ស្ថានភាព Sync ចុងក្រោយ')),
                ('last_sync_message', models.TextField(blank=True, null=True, verbose_name='កំណត់ត្រា Sync ចុងក្រោយ')),
            ],
            options={
                'verbose_name': 'ការកំណត់ Google Sheets / Google Sheets Config',
                'verbose_name_plural': 'ការកំណត់ Google Sheets / Google Sheets Configs',
            },
        ),
    ]
