# Generated by Django 6.1 on 2026-09-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_googlesheetsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='registration_mode',
            field=models.CharField(choices=[('ADMIN_CUSTOM', 'ចុះឈ្មោះតាមដែល Admin បានកំណត់ (ទូទៅ / Standard)'), ('MOEYS_INDIVIDUAL', 'ចុះឈ្មោះតាមសម្រង់ព័ត៌មានសិស្សម្នាក់ៗ (MoEYS Census 35 Columns)'), ('BOTH', 'បើកជម្រើសទាំង២ (អនុញ្ញាតឱ្យជ្រើសរើសវិធីណាក៏បាន)')], default='BOTH', help_text='កំណត់វិធីចុះឈ្មោះសិស្ស៖ តាមទម្រង់ Admin កំណត់ ឬ តាមសម្រង់ព័ត៌មានសិស្សម្នាក់ៗ ឬ បើកទាំងពីរ', max_length=30, verbose_name='វិធីសាស្ត្រចុះឈ្មោះសិស្ស / Student Registration Mode'),
        ),
    ]
