# Generated by Django 6.1 on 2026-09-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_schoolprofile_registration_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='is_registration_open',
            field=models.BooleanField(default=True, help_text='អនុញ្ញាត ឬ ផ្អាក ការចុះឈ្មោះសិស្សថ្មីទាំងនៅលើ Portal និង Mobile App', verbose_name='បើកដំណើរការចុះឈ្មោះសិស្ស / Enable Student Registration'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='registration_closed_message',
            field=models.CharField(blank=True, default='ការចុះឈ្មោះសិស្សថ្មីត្រូវបានបិទជាបណ្តោះអាសន្ន ឬផុតកំណត់កាលបរិច្ឆេទកំណត់ដោយរដ្ឋបាលសាលា។ សូមទាក់ទងរដ្ឋបាលសាលាសម្រាប់ព័ត៌មានបន្ថែម។', max_length=500, verbose_name='សារជូនដំណឹងពេលបិទការចុះឈ្មោះ / Closed Notice Message'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='registration_end_date',
            field=models.DateTimeField(blank=True, help_text='ពេលវេលាបញ្ចប់/ផុតកំណត់ការចុះឈ្មោះ (ទុកទទេ ប្រសិនបើគ្មានកំណត់)', null=True, verbose_name='កាលបរិច្ឆេទផុតកំណត់ចុះឈ្មោះ / Registration End Date & Time'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='registration_start_date',
            field=models.DateTimeField(blank=True, help_text='ពេលវេលាចាប់ផ្តើមអនុញ្ញាតឱ្យសិស្សចុះឈ្មោះ (ទុកទទេ ប្រសិនបើបើកភ្លាមៗ)', null=True, verbose_name='កាលបរិច្ឆេទចាប់ផ្តើមចុះឈ្មោះ / Registration Start Date & Time'),
        ),
    ]
