# Generated by Django 6.1 on 2026-09-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_schoolprofile_is_registration_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='registration_mode',
            field=models.CharField(choices=[('ADMIN_CUSTOM', 'ចុះឈ្មោះតាមដែល Admin បានកំណត់ (ទូទៅ / Standard)'), ('MOEYS_INDIVIDUAL', 'ចុះឈ្មោះតាមសម្រង់ព័ត៌មានសិស្សម្នាក់ៗ (MoEYS Census 35 Columns)'), ('BOTH', 'តាមការកំណត់របស់ Admin តាមកម្រិតថ្នាក់ (Admin Grade-Level Config)')], default='ADMIN_CUSTOM', help_text='កំណត់វិធីចុះឈ្មោះសិស្ស៖ តាមទម្រង់ Admin កំណត់ ឬ តាមសម្រង់ព័ត៌មានសិស្សម្នាក់ៗ ឬ តាមកម្រិតថ្នាក់ (សិស្សមិនអាចជ្រើសរើសនៅលើ Portal ឬ Mobile បានទេ គឺ Admin ជាអ្នកកំណត់)', max_length=30, verbose_name='វិធីសាស្ត្រចុះឈ្មោះសិស្ស / Student Registration Mode'),
        ),
    ]
