# Generated by Django 6.1 on 2026-09-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_schoolprofile_registration_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiAiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_keys', models.TextField(blank=True, default='', help_text='បញ្ចូល API Key មួយ ឬច្រើន (៣ ទៅ ៥ Keys សម្រាប់ Free Tier)។ ប្រព័ន្ធនឹងធ្វើ Auto Key Rotation ដោយស្វ័យប្រវត្តិ។', verbose_name='បញ្ជី Gemini API Keys (១ Key ក្នុងមួយបន្ទាត់ ឬខណ្ឌដោយក្បៀស)')),
                ('model_name', models.CharField(default='gemini-3.8-flash', help_text='ឧទាហរណ៍៖ gemini-3.8-flash, gemini-2.5-flash, gemini-flash-latest', max_length=100, verbose_name='ម៉ូដែល Gemini AI ចម្បង (Primary Model)')),
                ('thinking_level', models.CharField(choices=[('low', '⚡ Low (លឿនរហ័ស)'), ('medium', '⚖️ Medium (លំនឹងស្តង់ដារ)'), ('high', '🧠 High (ស៊ីជម្រៅបំផុត)')], default='medium', max_length=20, verbose_name='កម្រិតគិតពិចារណា (Thinking Level)')),
                ('is_active', models.BooleanField(default=True, verbose_name='បើកដំណើរការ Generative AI ក្នុងប្រព័ន្ធ')),
                ('rotation_enabled', models.BooleanField(default=True, verbose_name='បើកដំណើរការ Multi-Key Rotation (ចែកវេនគ្នាស្មើៗ & Auto Failover)')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទតេស្តចុងក្រោយ')),
                ('last_test_status', models.CharField(blank=True, default='', max_length=50, verbose_name='ស្ថានភាពតេស្ត')),
                ('last_test_message', models.TextField(blank=True, default='', verbose_name='លទ្ធផលតេស្ត')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ការកំណត់ Gemini AI / Gemini AI Config',
                'verbose_name_plural': 'ការកំណត់ Gemini AI / Gemini AI Configs',
            },
        ),
    ]
