# Generated by Django 6.1 on 2026-09-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_geminiaiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='registration_form_config',
            field=models.JSONField(blank=True, default=dict, help_text='រក្សាទុកការកំណត់ Ticking លើផ្នែកធំៗ និងចំណុចតូចៗនីមួយៗនៃបែបបទចុះឈ្មោះ', verbose_name='ការកំណត់ផ្នែក & ប្រអប់ចុះឈ្មោះ / Registration Sections & Fields Config'),
        ),
    ]
