# Generated by Django 6.1 on 2026-09-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_schoolprofile_registration_form_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='about_school',
            field=models.TextField(blank=True, null=True, verbose_name='អំពីសាលារៀន (Khmer)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='about_school_en',
            field=models.TextField(blank=True, null=True, verbose_name='អំពីសាលារៀន (English)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='motto_en',
            field=models.CharField(blank=True, default='Knowledge, Discipline, Morality, Virtue', max_length=255, null=True, verbose_name='បាវចនាសាលា (English)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='school_type_en',
            field=models.CharField(blank=True, default='General High School', max_length=100, null=True, verbose_name='កម្រិត/ប្រភេទសាលា (English)'),
        ),
    ]
