# Generated by Django 6.1 on 2026-09-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_schoolprofile_about_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='principal_name_en',
            field=models.CharField(blank=True, default='Dr. Sok Chanthorn', max_length=150, null=True, verbose_name='ឈ្មោះនាយក/នាយិកា (English) / Principal Name (English)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='short_name_en',
            field=models.CharField(blank=True, default='SchoolSM', max_length=100, null=True, verbose_name='ឈ្មោះកាត់សាលា (English) / Short Name (English)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='street_address_en',
            field=models.CharField(blank=True, default='Preah Norodom Blvd, Sangkat Wat Phnom', max_length=255, null=True, verbose_name='អាសយដ្ឋាន (English) / Street Address (English)'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='about_school',
            field=models.TextField(blank=True, null=True, verbose_name='អំពីសាលារៀន (Khmer) / About School (Khmer)'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='about_school_en',
            field=models.TextField(blank=True, null=True, verbose_name='អំពីសាលារៀន (English) / About School (English)'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='motto_en',
            field=models.CharField(blank=True, default='Knowledge, Discipline, Morality, Virtue', max_length=255, null=True, verbose_name='បាវចនាសាលា (English) / School Motto (English)'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_type_en',
            field=models.CharField(blank=True, default='General High School', max_length=100, null=True, verbose_name='កម្រិត/ប្រភេទសាលា (English) / School Level & Type (English)'),
        ),
    ]
