# Generated by Django 6.1 on 2026-09-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_schoolprofile_principal_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geminiaiconfig',
            name='model_name',
            field=models.CharField(default='gemini-3.5-flash', help_text='ឧទាហរណ៍៖ gemini-3.5-flash, gemini-3.5-flash-lite, gemini-flash-latest', max_length=100, verbose_name='ម៉ូដែល Gemini AI ចម្បង (Primary Model)'),
        ),
    ]
