# Generated by Django 6.1 on 2026-09-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_geminiaiconfig_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='commune_en',
            field=models.CharField(blank=True, default='Barkou Commune', max_length=100, verbose_name='ឃុំ/សង្កាត់ / Commune (English)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='doe_name_en',
            field=models.CharField(blank=True, default='Kandal Stueng District Office of Education', max_length=200, verbose_name='ការិយាល័យអប់រំ / DoE (English)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='education_levels_en',
            field=models.CharField(blank=True, default='Secondary & High School', max_length=255, verbose_name='កម្រិតសិក្សា / Education Levels (English)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='ministry_name_en',
            field=models.CharField(blank=True, default='Ministry of Education, Youth and Sport', max_length=200, verbose_name='ក្រសួងសាមី / Ministry Name (English)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='poe_name_en',
            field=models.CharField(blank=True, default='Kandal Provincial Department of Education', max_length=200, verbose_name='មន្ទីរអប់រំ / PoE (English)'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='village_en',
            field=models.CharField(blank=True, default='Svay Ming Village', max_length=100, verbose_name='ភូមិ / Village (English)'),
        ),
    ]
