# Generated by Django 6.1 on 2026-09-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_schoolprofile_commune_en_schoolprofile_doe_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='allow_student_self_update',
            field=models.BooleanField(default=True, help_text='បើក ឬ បិទ សិទ្ធិឱ្យសិស្សអាចចូលកែប្រែព័ត៌មានផ្ទាល់ខ្លួនរបស់ពួកគេបាននៅលើ Web Portal និង Mobile App (សិស្សអាចកែបានតែព័ត៌មានផ្ទាល់ខ្លួនរបស់ពួកគេប៉ុណ្ណោះ)', verbose_name='អនុញ្ញាតឱ្យសិស្សកែប្រែព័ត៌មានផ្ទាល់ខ្លួន / Allow Student Self-Update'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='student_update_closed_message',
            field=models.CharField(blank=True, default='ការកែប្រែព័ត៌មានសិស្សត្រូវបានបិទជាបណ្តោះអាសន្នដោយរដ្ឋបាលសាលា។ ប្រសិនបើមានព័ត៌មានចាំបាច់ត្រូវកែប្រែ សូមទាក់ទងមកការិយាល័យរដ្ឋបាលសាលា។', max_length=500, verbose_name='សារជូនដំណឹងពេលបិទការកែប្រែព័ត៌មានសិស្ស / Student Update Closed Message'),
        ),
    ]
