# Generated by Django 6.1 on 2026-08-20 09:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ឈ្មោះកម្រៃសិក្សា / Fee Title')),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('250.00'), max_digits=10, verbose_name='តម្លៃលំនាំដើម ($) / Default Amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នា / Description')),
            ],
            options={
                'verbose_name': 'ប្រភេទកម្រៃសិក្សា / Fee Category',
                'verbose_name_plural': 'ប្រភេទកម្រៃសិក្សាទាំងអស់ / Fee Categories',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ចំណងជើងចំណាយ / Expense Title')),
                ('category', models.CharField(choices=[('UTILITIES', 'ថ្លៃទឹក ភ្លើង អ៊ីនធឺណិត / Utilities'), ('SUPPLIES', 'សម្ភារៈការិយាល័យ & បង្រៀន / Supplies'), ('RENT', 'ថ្លៃជួលទីតាំង & អាគារ / Building Rent'), ('MAINTENANCE', 'ការជួសជុល & ថែទាំ / Repairs & Maintenance'), ('EVENTS', 'កម្មវិធី & កីឡាសាលា / School Events & Sports'), ('SALARY', 'ប្រាក់ខែ & ប្រាក់រង្វាន់ / Salaries & Bonuses'), ('OTHER', 'ចំណាយផ្សេងៗ / Other Expenses')], default='UTILITIES', max_length=30, verbose_name='ប្រភេទចំណាយ / Category')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ចំនួនទឹកប្រាក់ ($) / Amount')),
                ('date', models.DateField(verbose_name='កាលបរិច្ឆេទចំណាយ / Expense Date')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/', verbose_name='បង្កាន់ដៃ/វិក្កយបត្រចំណាយ / Voucher/Receipt')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='កំណត់ចំណាំ / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកកត់ត្រា / Recorded By')),
            ],
            options={
                'verbose_name': 'ចំណាយ / Expense',
                'verbose_name_plural': 'ចំណាយទាំងអស់ / Expenses',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=50, unique=True, verbose_name='លេខវិក្កយបត្រ / Invoice No')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='តម្លៃដើម ($) / Original Amount')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='បញ្ចុះតម្លៃ (%) / Discount/Scholarship %')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='តម្លៃត្រូវទូទាត់ ($) / Final Payable Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ចំនួនបានបង់ ($) / Paid Amount')),
                ('due_date', models.DateField(verbose_name='កាលបរិច្ឆេទទូទាត់ចុងក្រោយ / Due Date')),
                ('status', models.CharField(choices=[('PAID', 'បង់រួចរាល់ / Paid'), ('PARTIAL', 'បង់បានខ្លះ / Partially Paid'), ('UNPAID', 'មិនទាន់បង់ / Unpaid'), ('OVERDUE', 'ហួសកាលកំណត់ / Overdue')], default='UNPAID', max_length=20, verbose_name='ស្ថានភាពទូទាត់ / Payment Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='កំណត់ចំណាំ / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.feecategory', verbose_name='ប្រភេទកម្រៃ / Fee Category')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.student', verbose_name='សិស្ស / Student')),
            ],
            options={
                'verbose_name': 'វិក្កយបត្រ / Invoice',
                'verbose_name_plural': 'វិក្កយបត្រទាំងអស់ / Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ចំនួនទឹកប្រាក់បង់ ($) / Amount Paid')),
                ('payment_method', models.CharField(choices=[('CASH', 'សាច់ប្រាក់សុទ្ធ / Cash'), ('KHQR_BAKONG', 'KHQR (Bakong / គ្រប់ធនាគារ)'), ('ABA_BANK', 'ABA Bank Pay'), ('BANK_TRANSFER', 'ផ្ទេរប្រាក់ធនាគារ / Bank Transfer')], default='KHQR_BAKONG', max_length=30, verbose_name='វិធីសាស្ត្រទូទាត់ / Payment Method')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='លេខកូដប្រតិបត្តិការ / Ref No')),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='លេខបង្កាន់ដៃ / Receipt No')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទទូទាត់ / Payment Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='កំណត់ចំណាំ / Notes')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice', verbose_name='វិក្កយបត្រ / Invoice')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកទទួលប្រាក់ / Cashier/Accountant')),
            ],
            options={
                'verbose_name': 'ប្រតិបត្តិការបង់ប្រាក់ / Payment Transaction',
                'verbose_name_plural': 'ប្រតិបត្តិការបង់ប្រាក់ទាំងអស់ / Payment Transactions',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='ប្រចាំខែ (1-12) / Month')),
                ('year', models.IntegerField(verbose_name='ប្រចាំឆ្នាំ / Year')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ប្រាក់ខែគោល ($) / Base Salary')),
                ('bonus_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ប្រាក់បន្ថែម ($) / Bonus/Allowance')),
                ('unexcused_days', models.IntegerField(default=0, verbose_name='ចំនួនថ្ងៃអវត្តមានឥតច្បាប់ / Unexcused Absences')),
                ('absence_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='កាត់ប្រាក់អវត្តមាន ($) / Absence Deductions')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ប្រាក់ខែសុទ្ធត្រូវបើក ($) / Net Salary')),
                ('status', models.CharField(choices=[('PENDING', 'រង់ចាំបើក / Pending'), ('PAID', 'បើករួចរាល់ / Paid')], default='PENDING', max_length=20, verbose_name='ស្ថានភាព / Status')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='ថ្ងៃបើកប្រាក់ / Payment Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='កំណត់ចំណាំ / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='teachers.teacher', verbose_name='គ្រូបង្រៀន/បុគ្គលិក / Teacher/Staff')),
            ],
            options={
                'verbose_name': 'ប្រាក់ខែបុគ្គលិក / Payroll Record',
                'verbose_name_plural': 'ប្រាក់ខែបុគ្គលិកទាំងអស់ / Payroll Records',
                'ordering': ['-year', '-month', 'teacher'],
                'unique_together': {('teacher', 'month', 'year')},
            },
        ),
    ]
