# Generated by Django 6.1 on 2026-08-21 10:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_commune_code_alter_district_code_and_more'),
        ('finance', '0001_initial'),
        ('students', '0002_studentcategory_student_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ថ្លៃទឹកភ្លើង និងសេវាសិក្សាប្រចាំខែ', max_length=200, verbose_name='ចំណងជើងកម្រៃ / Fee Title')),
                ('start_month', models.PositiveSmallIntegerField(default=10, verbose_name='ខែចាប់ផ្តើម (1-12) / Start Month')),
                ('end_month', models.PositiveSmallIntegerField(default=8, verbose_name='ខែបញ្ចប់ (1-12) / End Month')),
                ('ticked_months', models.JSONField(blank=True, default=list, verbose_name='ខែដែលបាន Tick ត្រូវបង់ / Ticked Due Months')),
                ('currency_symbol', models.CharField(default='៛', max_length=10, verbose_name='រូបិយប័ណ្ណ / Currency Symbol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_fee_config', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
            ],
            options={
                'verbose_name': 'ការកំណត់ថ្លៃទឹកភ្លើងប្រចាំខែ / Monthly Fee Config',
                'verbose_name_plural': 'ការកំណត់ថ្លៃទឹកភ្លើងប្រចាំខែ / Monthly Fee Configs',
            },
        ),
        migrations.CreateModel(
            name='MonthlyFeeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='ខែ (1-12) / Month')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('20000.00'), max_digits=12, verbose_name='ចំនួនទឹកប្រាក់ / Amount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rates', to='students.studentcategory', verbose_name='ប្រភេទសិស្ស / Category')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='finance.monthlyfeeconfig', verbose_name='ការកំណត់ / Config')),
            ],
            options={
                'verbose_name': 'តម្លៃប្រចាំខែតាមប្រភេទសិស្ស / Monthly Fee Rate',
                'verbose_name_plural': 'តម្លៃប្រចាំខែតាមប្រភេទសិស្សទាំងអស់ / Monthly Fee Rates',
                'ordering': ['category__display_order', 'month'],
                'unique_together': {('config', 'category', 'month')},
            },
        ),
        migrations.CreateModel(
            name='StudentMonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='ខែ (1-12) / Month')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ចំនួនត្រូវបង់ / Expected Amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ចំនួនបានបង់ / Paid Amount')),
                ('status', models.CharField(choices=[('PAID', 'បង់គ្រប់ / Paid Full'), ('PARTIAL', 'បង់បានខ្លះ / Partial'), ('UNPAID', 'មិនទាន់បង់ / Unpaid')], default='UNPAID', max_length=20, verbose_name='ស្ថានភាព / Status')),
                ('is_on_time', models.BooleanField(default=True, verbose_name='បង់ទាន់ពេល / Paid On Time')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='ថ្ងៃបង់ប្រាក់ / Payment Date')),
                ('payment_method', models.CharField(choices=[('CASH', 'សាច់ប្រាក់សុទ្ធ / Cash'), ('KHQR_BAKONG', 'KHQR (Bakong)'), ('ABA_BANK', 'ABA Bank Pay'), ('BANK_TRANSFER', 'ផ្ទេរប្រាក់ធនាគារ / Bank Transfer')], default='CASH', max_length=30, verbose_name='វិធីសាស្ត្រទូទាត់ / Payment Method')),
                ('receipt_no', models.CharField(blank=True, max_length=50, verbose_name='លេខបង្កាន់ដៃ / Receipt No')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='កំណត់ចំណាំ / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកប្រមូល / Collector')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payments', to='students.student', verbose_name='សិស្ស / Student')),
            ],
            options={
                'verbose_name': 'កំណត់ត្រាបង់ប្រាក់ប្រចាំខែ / Student Monthly Payment',
                'verbose_name_plural': 'កំណត់ត្រាបង់ប្រាក់ប្រចាំខែទាំងអស់ / Student Monthly Payments',
                'ordering': ['student', 'month'],
                'unique_together': {('student', 'academic_year', 'month')},
            },
        ),
    ]
