# Generated by Django 6.1 on 2026-08-23 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_classroom_telegram_chat_id'),
        ('finance', '0002_monthlyfeeconfig_monthlyfeerate_and_more'),
        ('students', '0004_student_fee_end_month_alter_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMonthlyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='ខែ (1-12) / Month')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentcategory', verbose_name='ប្រភេទសិស្ស / Category')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_category_assignments', to='students.student', verbose_name='សិស្ស / Student')),
            ],
            options={
                'verbose_name': 'ប្រភេទសិស្សតាមខែជាក់ស្តែង / Student Monthly Category',
                'verbose_name_plural': 'ប្រភេទសិស្សតាមខែជាក់ស្តែងទាំងអស់ / Student Monthly Categories',
                'ordering': ['student', 'month'],
                'unique_together': {('student', 'academic_year', 'month')},
            },
        ),
    ]
