# Generated by Django 6.1 on 2026-09-02 05:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_alter_classroom_code_alter_classroom_name'),
        ('finance', '0003_studentmonthlycategory'),
        ('students', '0010_alter_student_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_type', models.CharField(choices=[('ABA', 'ABA Bank (ABA Pay / KHQR)'), ('BAKONG', 'Bakong KHQR (គ្រប់ធនាគារ)'), ('ACLEDA', 'ACLEDA Bank Plc.'), ('CANADIA', 'Canadia Bank'), ('WING', 'Wing Bank'), ('OTHER', 'ធនាគារផ្សេងៗ / Other Bank')], default='ABA', max_length=30, verbose_name='ប្រភេទធនាគារ / Bank')),
                ('bank_name', models.CharField(default='ABA Bank', max_length=150, verbose_name='ឈ្មោះធនាគារ / Bank Name')),
                ('account_name', models.CharField(max_length=150, verbose_name='ឈ្មោះម្ចាស់គណនី / Account Name')),
                ('account_number', models.CharField(max_length=100, verbose_name='លេខគណនី / Account Number')),
                ('currency', models.CharField(choices=[('KHR', 'រៀល (KHR ៛)'), ('USD', 'ដុល្លារ (USD $)'), ('BOTH', 'ទាំងពីរ (KHR / USD)')], default='KHR', max_length=10, verbose_name='រូបិយប័ណ្ណ / Currency')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='bank_qr/', verbose_name='រូបភាព QR Code / Bank QR Code Image')),
                ('khqr_payload', models.TextField(blank=True, null=True, verbose_name='ទិន្នន័យ Bakong KHQR String / Payload')),
                ('instructions', models.TextField(blank=True, default='សូមស្កេន QR Code ខាងលើដើម្បីបង់ប្រាក់។ បន្ទាប់មក សូមដាក់កំណត់សម្គាល់ (Memo) ជា «អត្តលេខសិស្ស» ហើយផ្ញើរូបថតបង្កាន់ដៃ (Receipt) មកទីនេះ។', null=True, verbose_name='ការណែនាំសម្រាប់ការបង់ប្រាក់ / Payment Instructions')),
                ('is_active', models.BooleanField(default=True, verbose_name='សកម្ម / Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='គណនីលំនាំដើម / Default Account')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='លំដាប់លំដោយ / Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'គណនីធនាគារ & QR Code / School Payment Method',
                'verbose_name_plural': 'គណនីធនាគារ & QR Code ទាំងអស់ / School Payment Methods',
                'ordering': ['-is_default', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FirestorePaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INQUIRY', 'សាកសួរព័ត៌មានកម្រៃ / Student Fee Inquiry'), ('QR_DISPATCH', 'បង្ហាញ QR Code / Bank QR Dispatched'), ('SLIP_SUBMISSION', 'ផ្ញើបង្កាន់ដៃបង់ប្រាក់ / Slip Submitted'), ('PAYMENT_CONFIRMED', 'បញ្ជាក់ការបង់ប្រាក់ / Payment Confirmed'), ('CLOUD_SYNC', 'Sync Cloud Firestore / Cloud Sync')], default='INQUIRY', max_length=30, verbose_name='ប្រភេទព្រឹត្តិការណ៍ / Event Type')),
                ('student_id_str', models.CharField(blank=True, max_length=50, null=True, verbose_name='អត្តលេខសិស្ស / Student ID')),
                ('student_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះសិស្ស / Student Name')),
                ('classroom_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ថ្នាក់ / Classroom')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ចំនួនទឹកប្រាក់ / Amount')),
                ('currency', models.CharField(default='៛', max_length=10, verbose_name='រូបិយប័ណ្ណ / Currency')),
                ('fee_category_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ប្រភេទកម្រៃ / Fee Category')),
                ('channel', models.CharField(default='TELEGRAM_BOT', max_length=50, verbose_name='ប៉ុស្តិ៍ទាក់ទង / Channel')),
                ('telegram_user_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='ព័ត៌មានអ្នកប្រើប្រាស់ Telegram')),
                ('firestore_doc_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Firestore Doc ID')),
                ('is_synced_to_firestore', models.BooleanField(default=False, verbose_name='បាន Sync ទៅ Firestore / Synced to Firestore')),
                ('payload_data', models.JSONField(blank=True, default=dict, verbose_name='ទិន្នន័យលម្អិត / Payload Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទ / Created At')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student', verbose_name='សិស្ស / Student')),
            ],
            options={
                'verbose_name': 'កំណត់ត្រា Firestore Payment Log / Payment Audit Log',
                'verbose_name_plural': 'កំណត់ត្រា Firestore Payment Logs ទាំងអស់ / Payment Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSlipSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('MONTHLY_UTILITY', 'ថ្លៃទឹកភ្លើងប្រចាំខែ / Monthly Utilities'), ('EARLY_YEAR_INVOICE', 'ថវិកាដើមឆ្នាំ/វិក្កយបត្រ / Early Year Invoice'), ('ALL_DUE', 'ទូទាត់ជំពាក់ទាំងអស់ / All Due Fees'), ('OTHER', 'ផ្សេងៗ / Other')], default='MONTHLY_UTILITY', max_length=30, verbose_name='ប្រភេទកម្រៃ / Fee Type')),
                ('target_months', models.JSONField(blank=True, default=list, verbose_name='ខែដែលបានបង់ / Target Months')),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ចំនួនទឹកប្រាក់បង់ ($ / ៛) / Amount')),
                ('currency', models.CharField(default='៛', max_length=10, verbose_name='រូបិយប័ណ្ណ / Currency')),
                ('slip_image', models.ImageField(blank=True, null=True, upload_to='payment_slips/%Y/%m/', verbose_name='រូបថតបង្កាន់ដៃ / Slip Image')),
                ('telegram_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram File ID')),
                ('telegram_user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram User ID')),
                ('telegram_username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram Username')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Chat ID')),
                ('status', models.CharField(choices=[('PENDING', 'រង់ចាំផ្ទៀងផ្ទាត់ / Pending Verification'), ('APPROVED', 'បានយល់ព្រម / Approved'), ('REJECTED', 'បដិសេធ / Rejected')], default='PENDING', max_length=20, verbose_name='ស្ថានភាព / Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទផ្ទៀងផ្ទាត់ / Reviewed At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='កំណត់ចំណាំ / Notes')),
                ('firestore_doc_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Firestore Doc ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slip_submissions', to='finance.invoice', verbose_name='វិក្កយបត្រ / Invoice')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកផ្ទៀងផ្ទាត់ / Reviewed By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_slips', to='students.student', verbose_name='សិស្ស / Student')),
            ],
            options={
                'verbose_name': 'បង្កាន់ដៃបង់ប្រាក់អាណាព្យាបាល / Payment Slip Submission',
                'verbose_name_plural': 'បង្កាន់ដៃបង់ប្រាក់អាណាព្យាបាលទាំងអស់ / Payment Slip Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
