# Generated by Django 6.1 on 2026-09-12 02:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_schoolpaymentmethod_firestorepaymentauditlog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feecategory',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': 'ប្រភេទកម្រៃសិក្សា / Fee Category', 'verbose_name_plural': 'ប្រភេទកម្រៃសិក្សាទាំងអស់ / Fee Categories'},
        ),
        migrations.AddField(
            model_name='feecategory',
            name='applicable_grade_note',
            field=models.CharField(blank=True, help_text='ឧទាហរណ៍៖ សម្រាប់តែថ្នាក់ទី ៧ ឬសិស្សចុះឈ្មោះថ្មី', max_length=200, null=True, verbose_name='កម្រិតថ្នាក់ដែលត្រូវអនុវត្ត / Applicable Grade Note'),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='category_type',
            field=models.CharField(choices=[('ENROLLMENT', 'ថ្លៃចុះឈ្មោះចូលរៀនដើមឆ្នាំ / Early Year Enrollment'), ('CONTRIBUTION', 'វិភាគទានសាលារៀន / School Contribution'), ('TUITION', 'កម្រៃសិក្សា / Tuition Fee'), ('UTILITIES', 'ថ្លៃទឹក-ភ្លើង / Utilities Billing'), ('UNIFORM', 'ថ្លៃឯកសណ្ឋាន / Uniform'), ('BOOKS', 'ថ្លៃសៀវភៅ & សម្ភារៈ / Books & Supplies'), ('OTHER', 'កម្រៃផ្សេងៗ / Other')], default='OTHER', max_length=30, verbose_name='ប្រភេទមុខចំណាយ / Category Type'),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='សកម្ម / Active'),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='default_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=10, verbose_name='តម្លៃលំនាំដើម ($) / Default Amount'),
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='អត្ថន័យចំណាយ / Description & Purpose'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.feecategory', verbose_name='ប្រភេទកម្រៃ / Fee Category'),
        ),
    ]
