# Generated by Django 6.1 on 2026-09-12 04:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_alter_gradeenrollmentoption_options_and_more'),
        ('finance', '0005_alter_feecategory_options_and_more'),
        ('teachers', '0014_teacher_phone2_alter_teacher_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherOvertimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_hour_khr', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10, verbose_name='អត្រាក្នុងមួយម៉ោង (រៀល ៛/h) / Rate (KHR)')),
                ('rate_per_hour_usd', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=8, verbose_name='អត្រាក្នុងមួយម៉ោង (ដុល្លារ $/h) / Rate (USD)')),
                ('standard_hours_weekly', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='ម៉ោងកាតព្វកិច្ចរដ្ឋក្នុងមួយសប្តាហ៍ / Standard Weekly Hours')),
                ('standard_hours_monthly', models.DecimalField(decimal_places=2, default=Decimal('64.00'), max_digits=5, verbose_name='ម៉ោងកាតព្វកិច្ចរដ្ឋក្នុងមួយខែ / Standard Monthly Hours')),
                ('notes', models.TextField(blank=True, default='អត្រាប្រាក់ឧបត្ថម្ភបង្រៀនលើសម៉ោងកំណត់សម្រាប់គ្រូបង្រៀនសាលារដ្ឋ', null=True, verbose_name='កំណត់ចំណាំ / Policy Notes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ការកំណត់អត្រាលើសម៉ោង / Overtime Rate Config',
                'verbose_name_plural': 'ការកំណត់អត្រាលើសម៉ោង / Overtime Rate Configs',
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='amount_khr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='ចំនួនទឹកប្រាក់ (រៀល ៛) / Amount (KHR)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ចំនួនទឹកប្រាក់ ($) / Amount (USD)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('UTILITIES', 'ថ្លៃទឹក ភ្លើង អ៊ីនធឺណិតសាលា / School Utilities'), ('SUPPLIES', 'សម្ភារៈការិយាល័យ & បង្រៀន (ដីស ហ្វឺត ក្រដាស) / Supplies'), ('RENT', 'ថ្លៃជួលទីតាំង & អាគារ / Building Rent'), ('MAINTENANCE', 'ការជួសជុល & ថែទាំអគារ/បន្ទប់ទឹក / Repairs & Maintenance'), ('EVENTS', 'កម្មវិធី & កីឡាសាលា / School Events & Sports'), ('TEACHER_OVERTIME', 'ប្រាក់ឧបត្ថម្ភគ្រូបង្រៀនលើសម៉ោង / Teacher Overtime Allowance'), ('SANITATION_ENV', 'អនាម័យ បរិស្ថាន & សួនច្បារ / Sanitation & Environment'), ('SALARY', 'ប្រាក់ខែ & ប្រាក់រង្វាន់ / Salaries & Bonuses'), ('OTHER', 'ចំណាយផ្សេងៗ / Other Expenses')], default='UTILITIES', max_length=30, verbose_name='ប្រភេទចំណាយ / Category'),
        ),
        migrations.CreateModel(
            name='SchoolRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ចំណងជើងចំណូល / Revenue Title')),
                ('source_type', models.CharField(choices=[('STATE_BUDGET', 'ថវិកាកម្មវិធីរដ្ឋ (MoEYS Program Budget / PB)'), ('PARENT_CONTRIBUTION', 'វិភាគទានសហគមន៍/អាណាព្យាបាល (Community & Parent Support)'), ('UTILITY_COLLECTION', 'ថ្លៃទឹកភ្លើងបន្ទប់រៀនប្រចាំខែ (Classroom Utilities)'), ('CANTEEN_RENT', 'ថ្លៃឈ្នួលអាហារដ្ឋាន/តូបលក់ដូរ (Canteen / Booth Rent)'), ('SCHOOL_SERVICES', 'ចំណូលសេវាកម្ម (ឯកសណ្ឋាន កាតសិស្ស សៀវភៅតាមដាន)'), ('DONATION', 'អំណោយ/សប្បុរសជន/អតីតសិស្ស (Donations & Grants)'), ('OTHER', 'ចំណូលផ្សេងៗ / Other Revenue')], default='STATE_BUDGET', max_length=40, verbose_name='ប្រភពចំណូល / Source')),
                ('amount_khr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='ចំនួនទឹកប្រាក់ (រៀល ៛) / Amount (KHR)')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ចំនួនទឹកប្រាក់ (ដុល្លារ $) / Amount (USD)')),
                ('date', models.DateField(verbose_name='កាលបរិច្ឆេទទទួល / Date Received')),
                ('receipt_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='លេខបង្កាន់ដៃ/លិខិតយោង / Voucher Ref')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='revenue/vouchers/', verbose_name='ឯកសារភ្ជាប់ / Receipt File')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='កំណត់ចំណាំ / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកកត់ត្រា / Recorded By')),
            ],
            options={
                'verbose_name': 'ចំណូលសាលា / School Revenue',
                'verbose_name_plural': 'ចំណូលសាលាទាំងអស់ / School Revenues',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherOvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='ប្រចាំខែ (1-12) / Month')),
                ('year', models.PositiveIntegerField(verbose_name='ប្រចាំឆ្នាំ / Year')),
                ('standard_hours', models.DecimalField(decimal_places=2, default=Decimal('64.00'), max_digits=6, verbose_name='ម៉ោងកាតព្វកិច្ចរដ្ឋ / Standard Hours')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=Decimal('64.00'), max_digits=6, verbose_name='ម៉ោងបង្រៀនជាក់ស្តែង / Actual Taught Hours')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='ម៉ោងបង្រៀនលើស / Overtime Hours')),
                ('rate_per_hour_khr', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10, verbose_name='អត្រា/ម៉ោង (រៀល ៛)')),
                ('rate_per_hour_usd', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=8, verbose_name='អត្រា/ម៉ោង (ដុល្លារ $)')),
                ('total_allowance_khr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='សរុបប្រាក់ឧបត្ថម្ភ (រៀល ៛)')),
                ('total_allowance_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='សរុបប្រាក់ឧបត្ថម្ភ (ដុល្លារ $)')),
                ('status', models.CharField(choices=[('PENDING', 'រង់ចាំបើក / Pending'), ('APPROVED', 'បានអនុម័ត / Approved'), ('PAID', 'បើករួចរាល់ / Paid')], default='PENDING', max_length=20, verbose_name='ស្ថានភាព / Status')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='ថ្ងៃបើកប្រាក់ / Payment Date')),
                ('voucher_ref', models.CharField(blank=True, max_length=100, null=True, verbose_name='លេខលិខិតទូទាត់ / Voucher Ref')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='កំណត់ចំណាំ / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកកត់ត្រា / Recorded By')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_records', to='teachers.teacher', verbose_name='គ្រូបង្រៀន / Teacher')),
            ],
            options={
                'verbose_name': 'ប្រាក់ឧបត្ថម្ភលើសម៉ោងគ្រូ / Teacher Overtime Allowance',
                'verbose_name_plural': 'ប្រាក់ឧបត្ថម្ភលើសម៉ោងគ្រូទាំងអស់ / Teacher Overtime Allowances',
                'ordering': ['-year', '-month', 'teacher__khmer_name'],
                'unique_together': {('teacher', 'month', 'year')},
            },
        ),
    ]
