# Generated by Django 6.1 on 2026-08-20 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ឆ្នាំសិក្សា / Academic Year Name (e.g. 2025-2026)')),
                ('start_date', models.DateField(verbose_name='ថ្ងៃចាប់ផ្តើម / Start Date')),
                ('end_date', models.DateField(verbose_name='ថ្ងៃបញ្ចប់ / End Date')),
                ('is_current', models.BooleanField(default=True, verbose_name='ឆ្នាំសិក្សាបច្ចុប្បន្ន / Is Current Year')),
            ],
            options={
                'verbose_name': 'ឆ្នាំសិក្សា / Academic Year',
                'verbose_name_plural': 'ឆ្នាំសិក្សាទាំងអស់ / Academic Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours', models.IntegerField(default=4, verbose_name='ម៉ោងក្នុងមួយសប្តាហ៍ / Weekly Hours')),
            ],
            options={
                'verbose_name': 'មុខវិជ្ជាប្រចាំថ្នាក់ / Class Subject Assignment',
                'verbose_name_plural': 'មុខវិជ្ជាប្រចាំថ្នាក់ / Class Subject Assignments',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kh', models.CharField(max_length=150, verbose_name='ឈ្មោះមុខវិជ្ជា (ខ្មែរ) / Subject Name (Khmer)')),
                ('name_en', models.CharField(max_length=150, verbose_name='ឈ្មោះមុខវិជ្ជា (អង់គ្លេស) / Subject Name (English)')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='កូដមុខវិជ្ជា / Subject Code (e.g. MATH-10)')),
                ('credit', models.IntegerField(default=2, verbose_name='ក្រេឌីត/ទម្ងន់ / Credit Hours/Weight')),
                ('color_code', models.CharField(default='#4f46e5', max_length=20, verbose_name='ពណ៌សម្គាល់ / Badge Color')),
            ],
            options={
                'verbose_name': 'មុខវិជ្ជា / Subject',
                'verbose_name_plural': 'មុខវិជ្ជាទាំងអស់ / Subjects',
                'ordering': ['name_kh'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'ថ្ងៃច័ន្ទ / Monday'), (2, 'ថ្ងៃអង្គារ / Tuesday'), (3, 'ថ្ងៃពុធ / Wednesday'), (4, 'ថ្ងៃព្រហស្បតិ៍ / Thursday'), (5, 'ថ្ងៃសុក្រ / Friday'), (6, 'ថ្ងៃសៅរ៍ / Saturday')], verbose_name='ថ្ងៃក្នុងសប្តាហ៍ / Day of Week')),
                ('start_time', models.TimeField(verbose_name='ម៉ោងចាប់ផ្តើម / Start Time')),
                ('end_time', models.TimeField(verbose_name='ម៉ោងបញ្ចប់ / End Time')),
                ('room', models.CharField(blank=True, max_length=100, null=True, verbose_name='បន្ទប់សិក្សា / Room (Optional)')),
            ],
            options={
                'verbose_name': 'កាលវិភាគ / Timetable Entry',
                'verbose_name_plural': 'កាលវិភាគទាំងអស់ / Timetable Entries',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ឈ្មោះថ្នាក់រៀន / Class Name (e.g. ថ្នាក់ទី១០A)')),
                ('code', models.CharField(max_length=20, verbose_name='កូដថ្នាក់ / Class Code (e.g. 10A)')),
                ('grade_level', models.IntegerField(default=10, verbose_name='កម្រិតថ្នាក់ / Grade Level (e.g. 10, 11, 12)')),
                ('room_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='បន្ទប់រៀន / Room Number (e.g. បន្ទប់ 201)')),
                ('capacity', models.IntegerField(default=40, verbose_name='ចំនួនសិស្សអតិបរមា / Capacity')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
            ],
            options={
                'verbose_name': 'ថ្នាក់រៀន / Classroom',
                'verbose_name_plural': 'ថ្នាក់រៀនទាំងអស់ / Classrooms',
                'ordering': ['grade_level', 'code'],
            },
        ),
    ]
