# Generated by Django 6.1 on 2026-08-20 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='teachers.teacher', verbose_name='គ្រូបន្ទុកថ្នាក់ / Homeroom Teacher'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_assignments', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.classroom', verbose_name='ថ្នាក់រៀន / Classroom'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject', verbose_name='មុខវិជ្ជា / Subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='teachers.teacher', verbose_name='គ្រូបង្រៀន / Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('code', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('classroom', 'subject')},
        ),
    ]
