# Generated by Django 6.1 on 2026-08-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='track',
            field=models.CharField(choices=[('GENERAL', 'កម្មវិធីទូទៅ (អនុវិទ្យាល័យ & ទី១០)'), ('SCIENCE', 'ថ្នាក់វិទ្យាសាស្ត្រពិត (Science Track)'), ('SOCIAL', 'ថ្នាក់វិទ្យាសាស្ត្រសង្គម (Social Science Track)')], default='GENERAL', max_length=20, verbose_name='ជំនាញសិក្សា / Academic Track'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(max_length=20, verbose_name='កូដថ្នាក់ / Class Code (e.g. 10A, 11-SCI)'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='grade_level',
            field=models.IntegerField(default=10, verbose_name='កម្រិតថ្នាក់ (៧-១២) / Grade Level (7-12)'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ឈ្មោះថ្នាក់រៀន / Class Name (e.g. ថ្នាក់ទី១០A, ទី១១ វិទ្យាសាស្ត្រ)'),
        ),
    ]
