# Generated by Django 6.1 on 2026-08-20 10:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classroom_track_alter_classroom_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['code'], 'verbose_name': 'មុខវិជ្ជា / Subject', 'verbose_name_plural': 'មុខវិជ្ជាទាំងអស់ / Subjects'},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(max_length=20, verbose_name='កូដថ្នាក់ / Class Code (e.g. 7A, 11-SCI)'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ឈ្មោះថ្នាក់រៀន / Class Name (e.g. ថ្នាក់ទី៧A, ទី១១ វិទ្យាសាស្ត្រ)'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='track',
            field=models.CharField(choices=[('GENERAL', 'កម្មវិធីទូទៅ (ថ្នាក់ទី ៧-១០)'), ('SCIENCE', 'ថ្នាក់វិទ្យាសាស្ត្រ (Science Track)'), ('SOCIAL', 'ថ្នាក់វិទ្យាសាស្ត្រសង្គម (Social Science Track)')], default='GENERAL', max_length=20, verbose_name='ជំនាញសិក្សា / Academic Track'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='កូដមុខវិជ្ជា / Subject Code (e.g. MATH-01)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credit',
            field=models.IntegerField(default=2, verbose_name='ក្រេឌីត/មេគុណ / Credit Hours/Weight'),
        ),
        migrations.CreateModel(
            name='GradeLevelRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField(verbose_name='កម្រិតថ្នាក់ (7-12) / Grade Level')),
                ('track', models.CharField(choices=[('GENERAL', 'កម្មវិធីទូទៅ (ថ្នាក់ទី ៧-១០)'), ('SCIENCE', 'ថ្នាក់វិទ្យាសាស្ត្រ (Science Track)'), ('SOCIAL', 'ថ្នាក់វិទ្យាសាស្ត្រសង្គម (Social Science Track)')], default='GENERAL', max_length=20, verbose_name='ជំនាញសិក្សា / Track')),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=6, verbose_name='ពិន្ទុអតិបរមា / Max Score')),
                ('order', models.IntegerField(default=1, verbose_name='លំដាប់លំដោយ / Sort Order')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_rules', to='academics.subject', verbose_name='មុខវិជ្ជា / Subject')),
            ],
            options={
                'verbose_name': 'ច្បាប់ពិន្ទុតាមកម្រិតថ្នាក់ / Grade Level Scoring Rule',
                'verbose_name_plural': 'ច្បាប់ពិន្ទុតាមកម្រិតថ្នាក់ទាំងអស់ / Grade Level Scoring Rules',
                'ordering': ['grade_level', 'track', 'order', 'subject__name_kh'],
                'unique_together': {('grade_level', 'track', 'subject')},
            },
        ),
    ]
