# Generated by Django 6.1 on 2026-08-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_subject_options_alter_classroom_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDefaultConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='custom_scoring_rules', max_length=50, unique=True)),
                ('data', models.JSONField(default=dict, verbose_name='ទិន្នន័យកំណត់លំនាំដើម / Default Config Data')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gradelevelrule',
            options={'ordering': ['grade_level', 'track', 'subject__order', 'order'], 'verbose_name': 'ច្បាប់ពិន្ទុតាមកម្រិតថ្នាក់ / Grade Level Scoring Rule', 'verbose_name_plural': 'ច្បាប់ពិន្ទុតាមកម្រិតថ្នាក់ទាំងអស់ / Grade Level Scoring Rules'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['order', 'id'], 'verbose_name': 'មុខវិជ្ជា / Subject', 'verbose_name_plural': 'មុខវិជ្ជាទាំងអស់ / Subjects'},
        ),
        migrations.AddField(
            model_name='subject',
            name='order',
            field=models.IntegerField(default=1, verbose_name='លំដាប់លំដោយ / Sort Order'),
        ),
        migrations.AlterField(
            model_name='gradelevelrule',
            name='track',
            field=models.CharField(choices=[('GENERAL', 'កម្មវិធីទូទៅ (ថ្នាក់ទី ៧-១០)'), ('SCIENCE', 'ថ្នាក់វិទ្យាសាស្ត្រ (Science Track)'), ('SOCIAL', 'ថ្នាក់វិទ្យាសាស្ត្រសង្គម (Social Science Track)')], default='GENERAL', max_length=20, verbose_name='មុខវិជ្ជា/ជំនាញ / Track'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='អក្សរកាត់/កូដ / Subject Short Code (e.g. R, D, K, M)'),
        ),
    ]
