# Generated by Django 6.1 on 2026-08-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_saveddefaultconfig_alter_gradelevelrule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevelrule',
            name='track',
            field=models.CharField(default='GENERAL', max_length=30, verbose_name='មុខវិជ្ជា/ជំនាញ / Track'),
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ឈ្មោះកម្រិតថ្នាក់ / Grade Level Name (e.g. ថ្នាក់ទី ១០ វិទ្យាសាស្ត្រ)')),
                ('grade_number', models.IntegerField(verbose_name='កម្រិតថ្នាក់លេខ / Grade Number (e.g. 7, 8, 9, 10, 11, 12)')),
                ('track', models.CharField(default='GENERAL', max_length=30, verbose_name='ជំនាញសិក្សា / Track (GENERAL, SCIENCE, SOCIAL)')),
                ('order', models.IntegerField(default=1, verbose_name='លំដាប់លំដោយ / Sort Order')),
            ],
            options={
                'verbose_name': 'កម្រិតថ្នាក់ / Grade Level',
                'verbose_name_plural': 'កម្រិតថ្នាក់ទាំងអស់ / Grade Levels',
                'ordering': ['order', 'grade_number', 'track', 'id'],
                'unique_together': {('grade_number', 'track')},
            },
        ),
    ]
