# Generated by Django 6.1 on 2026-08-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_gradelevelrule_track_gradelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradelevelrule',
            name='weekly_hours',
            field=models.IntegerField(default=2, verbose_name='ម៉ោងសិក្សាក្នុងមួយសប្តាហ៍ / Weekly Hours'),
        ),
    ]
