# Generated by Django 6.1 on 2026-08-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_gradelevelrule_weekly_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('SCIENCE', 'វិទ្យាសាស្ត្រពិត (Science / STEM)'), ('SOCIAL', 'វិទ្យាសាស្ត្រសង្គម (Social Science / Humanities)'), ('GENERAL', 'ចំណេះទូទៅ & ភាសា (General / Languages)')], default='GENERAL', max_length=30, verbose_name='ក្រុមមុខវិជ្ជា / Category'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_number',
            field=models.IntegerField(default=1, verbose_name='ម៉ោងទី / Period (1-8)'),
        ),
    ]
