# Generated by Django 6.1 on 2026-08-21 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_subject_category_timetable_period_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='កូដស្រុក / District Code')),
                ('name_kh', models.CharField(max_length=150, verbose_name='ឈ្មោះស្រុក/ខណ្ឌ/ក្រុង (ខ្មែរ)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='ឈ្មោះស្រុក/ខណ្ឌ/ក្រុង (ឡាតាំង)')),
            ],
            options={
                'verbose_name': 'ស្រុក/ខណ្ឌ/ក្រុង / District',
                'verbose_name_plural': 'ស្រុក/ខណ្ឌ/ក្រុងទាំងអស់ / Districts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='កូដខេត្ត / Province Code')),
                ('name_kh', models.CharField(max_length=150, verbose_name='ឈ្មោះខេត្ត/រាជធានី (ខ្មែរ)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='ឈ្មោះខេត្ត/រាជធានី (ឡាតាំង)')),
            ],
            options={
                'verbose_name': 'ខេត្ត/រាជធានី / Province',
                'verbose_name_plural': 'ខេត្ត/រាជធានីទាំងអស់ / Provinces',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='កូដឃុំ / Commune Code')),
                ('name_kh', models.CharField(max_length=150, verbose_name='ឈ្មោះឃុំ/សង្កាត់ (ខ្មែរ)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='ឈ្មោះឃុំ/សង្កាត់ (ឡាតាំង)')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='academics.district', verbose_name='ស្រុក/ខណ្ឌ/ក្រុង')),
            ],
            options={
                'verbose_name': 'ឃុំ/សង្កាត់ / Commune',
                'verbose_name_plural': 'ឃុំ/សង្កាត់ទាំងអស់ / Communes',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='academics.province', verbose_name='ខេត្ត/រាជធានី'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='កូដភូមិ / Village Code')),
                ('name_kh', models.CharField(max_length=150, verbose_name='ឈ្មោះភូមិ (ខ្មែរ)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='ឈ្មោះភូមិ (ឡាតាំង)')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='academics.commune', verbose_name='ឃុំ/សង្កាត់')),
            ],
            options={
                'verbose_name': 'ភូមិ / Village',
                'verbose_name_plural': 'ភូមិទាំងអស់ / Villages',
                'ordering': ['code'],
            },
        ),
    ]
