# Generated by Django 6.1 on 2026-08-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_district_province_commune_district_province_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='កូដឃុំ / Commune Code'),
        ),
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='កូដស្រុក / District Code'),
        ),
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='កូដខេត្ត / Province Code'),
        ),
        migrations.AlterField(
            model_name='village',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='កូដភូមិ / Village Code'),
        ),
    ]
