# Generated by Django 6.1 on 2026-08-22 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_commune_code_alter_district_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Group/Chat ID (សម្រាប់ផ្ញើវត្តមានថ្នាក់)'),
        ),
        migrations.CreateModel(
            name='AcademicCalendarRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_type', models.CharField(choices=[('VACATION', 'វិស្សមកាល / Vacation Period'), ('HOLIDAY', 'ថ្ងៃបុណ្យ/ឈប់សម្រាក / Public Holiday'), ('MAINTENANCE', 'បិទប្រព័ន្ធថែទាំ / System Maintenance')], default='HOLIDAY', max_length=20, verbose_name='ប្រភេទ / Type')),
                ('title', models.CharField(max_length=200, verbose_name='ឈ្មោះកម្មវិធី/មូលហេតុ / Title/Reason')),
                ('start_date', models.DateField(verbose_name='ថ្ងៃចាប់ផ្តើម / Start Date')),
                ('end_date', models.DateField(verbose_name='ថ្ងៃបញ្ចប់ / End Date')),
                ('block_attendance', models.BooleanField(default=True, verbose_name='ចាក់សោមិនឱ្យចុះវត្តមាន / Block Attendance')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ពិពណ៌នាបន្ថែម / Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='បើកដំណើរការ / Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកបង្កើត / Created By')),
            ],
            options={
                'verbose_name': 'ប្រតិទិនវិស្សមកាល និងថ្ងៃឈប់សម្រាក / Academic Calendar Restriction',
                'verbose_name_plural': 'ប្រតិទិនវិស្សមកាល និងថ្ងៃឈប់សម្រាកទាំងអស់ / Academic Calendar Restrictions',
                'ordering': ['-start_date', 'title'],
            },
        ),
    ]
