# Generated by Django 6.1 on 2026-08-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_classroom_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Telegram Group/Chat ID (សម្រាប់ផ្ញើវត្តមានថ្នាក់ អាចដាក់ច្រើន Chat ID)'),
        ),
    ]
