# Generated by Django 6.1 on 2026-08-23 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_classroom_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeEnrollmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='ឈ្មោះជម្រើស/សំណួរ (Label)')),
                ('field_name', models.CharField(help_text='e.g. primary_school, diploma_grade, elective_subject', max_length=100, verbose_name='កូដសម្គាល់ (Field Key)')),
                ('field_type', models.CharField(choices=[('TEXT', 'ប្រអប់អត្ថបទខ្លី (Short Text)'), ('TEXTAREA', 'ប្រអប់អត្ថបទវែង (Long Text / Notes)'), ('NUMBER', 'ប្រអប់លេខ (Number)'), ('SELECT', 'បញ្ជីជ្រើសរើស (Dropdown Select)'), ('CHECKBOX', 'ប្រអប់ធីក (Checkbox / Yes-No)'), ('FILE', 'ឯកសារភ្ជាប់/រូបភាព (File/Document Upload)')], default='TEXT', max_length=20, verbose_name='ប្រភេទប្រអប់ (Field Type)')),
                ('choices', models.TextField(blank=True, help_text='បំបែកដោយសញ្ញាក្បៀស (,) សម្រាប់ប្រភេទ Dropdown Select (ឧ. និទ្ទេស A, និទ្ទេស B, និទ្ទេស C, និទ្ទេស D, និទ្ទេស E)', null=True, verbose_name='ជម្រើស (Choices)')),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True, verbose_name='Placeholder/ណែនាំ')),
                ('is_required', models.BooleanField(default=False, verbose_name='តម្រូវឱ្យបំពេញ (Required)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='លំដាប់លំដោយ (Sort Order)')),
                ('is_active', models.BooleanField(default=True, verbose_name='សកម្ម (Active)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_options', to='academics.gradelevel', verbose_name='កម្រិតថ្នាក់ / Grade Level')),
            ],
            options={
                'verbose_name': 'ជម្រើសចុះឈ្មោះតាមកម្រិតថ្នាក់ / Grade Enrollment Option',
                'verbose_name_plural': 'ជម្រើសចុះឈ្មោះតាមកម្រិតថ្នាក់ទាំងអស់ / Grade Enrollment Options',
                'ordering': ['grade_level__order', 'order', 'id'],
            },
        ),
    ]
