# Generated by Django 6.1 on 2026-08-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_gradeenrollmentoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeenrollmentoption',
            name='col_width',
            field=models.PositiveSmallIntegerField(choices=[(12, 'ពេញជួរ (100% - col-12)'), (6, 'កន្លះជួរ (50% - col-6)'), (4, 'មួយភាគបី (33% - col-4)'), (3, 'មួយភាគបួន (25% - col-3)')], default=6, verbose_name='ទំហំទទឹងប្រអប់ (Column Width)'),
        ),
        migrations.AlterField(
            model_name='gradeenrollmentoption',
            name='choices',
            field=models.TextField(blank=True, help_text='បំបែកដោយសញ្ញាក្បៀស (,) សម្រាប់ប្រភេទ Dropdown Select, Radio, Multi-Select (ឧ. និទ្ទេស A, និទ្ទេស B, និទ្ទេស C)', null=True, verbose_name='ជម្រើស (Choices)'),
        ),
        migrations.AlterField(
            model_name='gradeenrollmentoption',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'ប្រអប់អត្ថបទខ្លី (Short Text)'), ('TEXTAREA', 'ប្រអប់អត្ថបទវែង (Long Text / Notes)'), ('NUMBER', 'ប្រអប់លេខ (Number)'), ('DATE', 'កាលបរិច្ឆេទ (Date Picker)'), ('TIME', 'ពេលវេលា/ម៉ោង (Time Picker)'), ('DATETIME', 'កាលបរិច្ឆេទ & ម៉ោង (Date & Time)'), ('PHONE', 'លេខទូរស័ព្ទ (Phone Number)'), ('EMAIL', 'អ៊ីមែល (Email Address)'), ('SELECT', 'បញ្ជីជ្រើសរើសទោល (Dropdown Select)'), ('RADIO', 'ជម្រើសមូលទោល (Radio Buttons)'), ('MULTISELECT', 'បញ្ជីជ្រើសរើសច្រើន (Multi-Select Checkboxes)'), ('CHECKBOX', 'ប្រអប់ធីក (Checkbox / Yes-No)'), ('FILE', 'ឯកសារភ្ជាប់/រូបភាព (File/Document Upload)'), ('SECTION', 'ចំណងជើងផ្នែក / ខណ្ឌស៊ុម (Section Header / Frame Divider)')], default='TEXT', max_length=20, verbose_name='ប្រភេទប្រអប់ (Field Type)'),
        ),
    ]
