# Generated by Django 6.1 on 2026-08-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_gradeenrollmentoption_col_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='កូដជំនាញ / Track Code (e.g. GENERAL, SCIENCE, SOCIAL, TECH)')),
                ('name_kh', models.CharField(max_length=150, verbose_name='ឈ្មោះជំនាញ (ខ្មែរ) / Track Name (Khmer)')),
                ('name_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះជំនាញ (អង់គ្លេស) / Track Name (English)')),
                ('is_default', models.BooleanField(default=False, verbose_name='ជំនាញស្តង់ដារ MoEYS / Is Standard')),
                ('order', models.IntegerField(default=1, verbose_name='លំដាប់លំដោយ / Sort Order')),
            ],
            options={
                'verbose_name': 'ជំនាញ/កម្មវិធីសិក្សា / Academic Track',
                'verbose_name_plural': 'ជំនាញ/កម្មវិធីសិក្សាទាំងអស់ / Academic Tracks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='classroom',
            name='track',
            field=models.CharField(default='GENERAL', max_length=50, verbose_name='ជំនាញសិក្សា / Academic Track'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='track',
            field=models.CharField(default='GENERAL', max_length=50, verbose_name='ជំនាញសិក្សា / Track (GENERAL, SCIENCE, SOCIAL...)'),
        ),
    ]
