# Generated by Django 6.1 on 2026-08-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_academictrack_alter_classroom_track_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='track',
            field=models.CharField(choices=[('GENERAL', 'កម្មវិធីទូទៅ (ថ្នាក់ទី ៧-១០)'), ('SCIENCE', 'ថ្នាក់វិទ្យាសាស្ត្រ (Science Track)'), ('SOCIAL', 'ថ្នាក់វិទ្យាសាស្ត្រសង្គម (Social Science Track)')], default='GENERAL', max_length=50, verbose_name='ជំនាញសិក្សា / Academic Track'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('SCIENCE', 'វិទ្យាសាស្ត្រពិត (Science / STEM)'), ('SOCIAL', 'វិទ្យាសាស្ត្រសង្គម (Social Science / Humanities)'), ('GENERAL', 'ចំណេះទូទៅ & ភាសា (General / Languages)'), ('TECH', 'បច្ចេកទេស & IT (Technical & ICT)'), ('SPECIALIZED', 'មុខវិជ្ជាឯកទេស & វិជ្ជាជីវៈ (Specialized & Vocational)')], default='GENERAL', max_length=30, verbose_name='ក្រុមមុខវិជ្ជា / Category'),
        ),
    ]
