# Generated by Django 6.1 on 2026-08-30 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_classroom_track_alter_subject_category'),
        ('teachers', '0014_teacher_phone2_alter_teacher_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDutySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'ថ្ងៃច័ន្ទ / Monday'), (2, 'ថ្ងៃអង្គារ / Tuesday'), (3, 'ថ្ងៃពុធ / Wednesday'), (4, 'ថ្ងៃព្រហស្បតិ៍ / Thursday'), (5, 'ថ្ងៃសុក្រ / Friday'), (6, 'ថ្ងៃសៅរ៍ / Saturday')], verbose_name='ថ្ងៃក្នុងសប្តាហ៍ / Day of Week')),
                ('period_number', models.IntegerField(default=1, verbose_name='ម៉ោងទី / Period (1-8)')),
                ('duty_type', models.CharField(choices=[('OFFICE', 'ប្រចាំការការិយាល័យ / Office Duty'), ('DISCIPLINE', 'សម្របសម្រួលវិន័យ / Discipline & Order'), ('LIBRARY', 'ប្រចាំការបណ្ណាល័យ / Library Duty'), ('ADMIN', 'រដ្ឋបាល & លិខិតស្នាម / Administration'), ('GENERAL', 'ប្រចាំការទូទៅ / General Duty')], default='OFFICE', max_length=30, verbose_name='ប្រភេទភារកិច្ច / Duty Type')),
                ('is_auto_assigned', models.BooleanField(default=False, verbose_name='បែងចែកស្វ័យប្រវត្តិ / Auto Assigned')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='កំណត់ចំណាំ/ទីតាំង / Notes/Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_schedules', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_schedules', to='teachers.teacher', verbose_name='គ្រូបង្រៀន/បុគ្គលិក / Teacher/Staff')),
            ],
            options={
                'verbose_name': 'ម៉ោងប្រចាំការ / Duty Schedule',
                'verbose_name_plural': 'ម៉ោងប្រចាំការទាំងអស់ / Duty Schedules',
                'ordering': ['academic_year', 'day_of_week', 'period_number', 'teacher'],
                'unique_together': {('academic_year', 'teacher', 'day_of_week', 'period_number')},
            },
        ),
    ]
