# Generated by Django 6.1 on 2026-08-30 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_teacherdutyschedule'),
        ('students', '0007_studentstatusconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_classrooms', to='students.student', verbose_name='ប្រធានថ្នាក់ / Class Monitor'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='vice_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_monitor_classrooms', to='students.student', verbose_name='អនុប្រធានថ្នាក់ / Vice Class Monitor'),
        ),
    ]
