# Generated by Django 6.1 on 2026-08-30 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_classroom_class_monitor_classroom_vice_monitor'),
        ('teachers', '0014_teacher_phone2_alter_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='assembly_duty_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_duty_classes', to='teachers.teacher', verbose_name='គ្រូទទួលបន្ទុកស្រង់វត្តមានគោរពទង់ជាតិ / Assembly Duty Teacher'),
        ),
    ]
