# Generated by Django 6.1 on 2026-08-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_classroom_assembly_duty_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDutyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='កូដសម្គាល់ / Code')),
                ('name', models.CharField(max_length=150, verbose_name='ឈ្មោះភារកិច្ច / Name')),
                ('icon', models.CharField(default='fa-clock', max_length=50, verbose_name='រូបតំណាង / FontAwesome Icon')),
                ('color', models.CharField(default='#4f46e5', max_length=20, verbose_name='ពណ៌ / Color (Hex)')),
                ('order', models.IntegerField(default=0, verbose_name='លំដាប់លំដោយ / Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ប្រភេទប្រចាំការ / Duty Type',
                'verbose_name_plural': 'ប្រភេទប្រចាំការទាំងអស់ / Duty Types',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='teacherdutyschedule',
            name='duty_type',
            field=models.CharField(default='OFFICE', max_length=50, verbose_name='ប្រភេទភារកិច្ច / Duty Type'),
        ),
    ]
