# Generated by Django 6.1 on 2026-08-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_teacherdutytype_alter_teacherdutyschedule_duty_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(blank=True, default=40, null=True, verbose_name='ចំនួនសិស្សអតិបរមា / Capacity'),
        ),
    ]
