# Generated by Django 6.1 on 2026-09-01 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_alter_classroom_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1, verbose_name='លើកទី / Version Number')),
                ('title', models.CharField(max_length=200, verbose_name='ឈ្មោះកាលវិភាគ/ចំណងជើង / Version Title')),
                ('note', models.TextField(blank=True, null=True, verbose_name='កំណត់សម្គាល់ / Note/Description')),
                ('matrix_data', models.JSONField(default=list, verbose_name='ទិន្នន័យកាលវិភាគ / Matrix Data')),
                ('blocked_slots', models.JSONField(blank=True, default=list, verbose_name='ម៉ោងបិទ / Blocked Slots')),
                ('class_subject_assignments', models.JSONField(blank=True, default=dict, verbose_name='ការចាត់តាំងគ្រូតាមថ្នាក់ / Class Subject Assignments')),
                ('total_slots', models.IntegerField(default=0, verbose_name='ចំនួនម៉ោងសរុប / Total Hours')),
                ('total_classrooms', models.IntegerField(default=0, verbose_name='ចំនួនថ្នាក់ / Total Classrooms')),
                ('is_active_applied', models.BooleanField(default=False, verbose_name='កំពុងប្រើប្រាស់ / Currently Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទបង្កើត / Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='កាលបរិច្ឆេទកែប្រែ / Updated At')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_versions', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetable_versions', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកបង្កើត / Created By')),
            ],
            options={
                'verbose_name': 'កំណែកាលវិភាគប្រចាំឆ្នាំ / Annual Timetable Version',
                'verbose_name_plural': 'កំណែកាលវិភាគប្រចាំឆ្នាំទាំងអស់ / Annual Timetable Versions',
                'ordering': ['academic_year', '-version_number', '-created_at'],
                'unique_together': {('academic_year', 'version_number')},
            },
        ),
    ]
