# Generated by Django 6.1 on 2026-09-01 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_timetableversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportPrintConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'ចន្ទ / Monday'), (2, 'អង្គារ / Tuesday'), (3, 'ពុធ / Wednesday'), (4, 'ព្រហស្បតិ៍ / Thursday'), (5, 'សុក្រ / Friday'), (6, 'សៅរ៍ / Saturday'), (7, 'អាទិត្យ / Sunday')], verbose_name='ថ្ងៃនៃសប្តាហ៍ / Day of Week')),
                ('session', models.CharField(choices=[('morning', 'ពេលព្រឹក (Morning)'), ('afternoon', 'ពេលរសៀល (Afternoon)')], default='morning', max_length=20, verbose_name='វេន / ពេលសិក្សា / Session')),
                ('target_pages', models.PositiveIntegerField(default=1, verbose_name='ចំនួនទំព័រ A4 / Target A4 Pages')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='កំណត់សម្គាល់ / Note')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report_print_configs', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
            ],
            options={
                'verbose_name': 'ការកំណត់ទំព័រព្រីនរបាយការណ៍ប្រចាំថ្ងៃ / Daily Report Print Config',
                'verbose_name_plural': 'ការកំណត់ទំព័រព្រីនរបាយការណ៍ប្រចាំថ្ងៃទាំងអស់ / Daily Report Print Configs',
                'ordering': ['academic_year', 'day_of_week', 'session'],
                'unique_together': {('academic_year', 'day_of_week', 'session')},
            },
        ),
    ]
