# Generated by Django 6.1 on 2026-09-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_dailyreportprintconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(max_length=100, verbose_name='កូដថ្នាក់ / Class Code (e.g. 7A, 11-SCI)'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=150, verbose_name='ឈ្មោះថ្នាក់រៀន / Class Name (e.g. ថ្នាក់ទី៧A, ទី១១ វិទ្យាសាស្ត្រ)'),
        ),
    ]
