# Generated by Django 6.1 on 2026-09-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0027_delete_classrooms_under_10_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradeenrollmentoption',
            options={'ordering': ['grade_level__order', 'form_category', 'order', 'id'], 'verbose_name': 'ជម្រើសចុះឈ្មោះតាមកម្រិតថ្នាក់ / Grade Enrollment Option', 'verbose_name_plural': 'ជម្រើសចុះឈ្មោះតាមកម្រិតថ្នាក់ទាំងអស់ / Grade Enrollment Options'},
        ),
        migrations.AddField(
            model_name='gradeenrollmentoption',
            name='form_category',
            field=models.CharField(choices=[('GENERAL', 'បែបបទចុះឈ្មោះទូទៅ (Admin បានកំណត់)'), ('MOEYS_INDIVIDUAL', 'បែបបទសម្រង់ព័ត៌មានសិស្សម្នាក់ៗ')], default='GENERAL', help_text='បែបបទចុះឈ្មោះទូទៅ (Admin កំណត់) ឬ បែបបទសម្រង់ព័ត៌មានសិស្សម្នាក់ៗ (MoEYS)', max_length=30, verbose_name='ប្រភេទបែបបទ / Form Category'),
        ),
    ]
