# Generated by Django 6.1 on 2026-09-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_alter_gradeenrollmentoption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='teacher_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដគ្រូតាមមុខវិជ្ជា / Teacher Subject Code'),
        ),
    ]
