# Generated by Django 6.1 on 2026-09-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_classsubject_teacher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradelevel',
            name='is_registration_open',
            field=models.BooleanField(default=True, help_text='កំណត់បើក ឬបិទការចុះឈ្មោះសម្រាប់កម្រិតថ្នាក់នេះ', verbose_name='បើកឱ្យចុះឈ្មោះ / Registration Open'),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='registration_closed_message',
            field=models.CharField(blank=True, default='', help_text='សារជូនដំណឹងទៅកាន់សិស្ស/អាណាព្យាបាលនៅពេលកម្រិតថ្នាក់នេះត្រូវបានបិទមិនឱ្យចុះឈ្មោះ', max_length=500, verbose_name='សារជូនដំណឹងពេលបិទការចុះឈ្មោះ / Registration Closed Notice'),
        ),
    ]
