# Generated by Django 6.1 on 2026-08-20 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='កូដសម្គាល់សិស្ស / Student ID')),
                ('khmer_name', models.CharField(max_length=150, verbose_name='ឈ្មោះខ្មែរ / Khmer Name')),
                ('latin_name', models.CharField(max_length=150, verbose_name='ឈ្មោះឡាតាំង / Latin Name')),
                ('gender', models.CharField(choices=[('M', 'ប្រុស / Male'), ('F', 'ស្រី / Female')], default='M', max_length=5, verbose_name='ភេទ / Gender')),
                ('date_of_birth', models.DateField(verbose_name='ថ្ងៃខែឆ្នាំកំណើត / Date of Birth')),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True, verbose_name='ទីកន្លែងកំណើត / Place of Birth')),
                ('current_address', models.TextField(blank=True, null=True, verbose_name='អាសយដ្ឋានបច្ចុប្បន្ន / Current Address')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='លេខទូរស័ព្ទសិស្ស / Student Phone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='រូបថតសិស្ស (៤x៦) / Student Photo')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='students/docs/', verbose_name='សំបុត្រកំណើត / Birth Certificate')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='ថ្ងៃចុះឈ្មោះ / Enrollment Date')),
                ('status', models.CharField(choices=[('ACTIVE', 'កំពុងសិក្សា / Active'), ('GRADUATED', 'បញ្ចប់ការសិក្សា / Graduated'), ('TRANSFERRED', 'ផ្ទេរការសិក្សា / Transferred'), ('DROPPED', 'បោះបង់ការសិក្សា / Dropped')], default='ACTIVE', max_length=20, verbose_name='ស្ថានភាព / Status')),
                ('scholarship_type', models.CharField(choices=[('FULL_PAY', 'បង់ពេញ ១០០% / Full Pay (100%)'), ('SCHOLARSHIP_50', 'អាហារូបករណ៍ ៥០% / Scholarship (50%)'), ('SCHOLARSHIP_100', 'អាហារូបករណ៍ ១០០% (ឥតគិតថ្លៃ) / Free (100%)'), ('INSTALLMENT', 'បង់រំលស់ប្រចាំខែ / Monthly Installment')], default='FULL_PAY', max_length=25, verbose_name='ប្រភេទកម្រៃសិក្សា / Fee Type')),
                ('father_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះឪពុក / Father Name')),
                ('father_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='លេខទូរស័ព្ទឪពុក / Father Phone')),
                ('father_job', models.CharField(blank=True, max_length=150, null=True, verbose_name='មុខរបរឪពុក / Father Occupation')),
                ('mother_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះម្តាយ / Mother Name')),
                ('mother_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='លេខទូរស័ព្ទម្តាយ / Mother Phone')),
                ('mother_job', models.CharField(blank=True, max_length=150, null=True, verbose_name='មុខរបរម្តាយ / Mother Occupation')),
                ('guardian_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះអាណាព្យាបាលជំនួស / Guardian Name')),
                ('emergency_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='លេខទាក់ទងបន្ទាន់ / Emergency Phone')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID អាណាព្យាបាល')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.classroom', verbose_name='ថ្នាក់រៀន / Classroom')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'សិស្ស / Student',
                'verbose_name_plural': 'សិស្សទាំងអស់ / Students',
                'ordering': ['classroom__grade_level', 'classroom__code', 'student_id'],
            },
        ),
    ]
