# Generated by Django 6.1 on 2026-08-21 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='ឈ្មោះប្រភេទសិស្ស / Category Name')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='កូដសម្គាល់ / Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នា / Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='សកម្ម / Active')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='លំដាប់លំដោយ / Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ប្រភេទសិស្ស / Student Category',
                'verbose_name_plural': 'ប្រភេទសិស្សទាំងអស់ / Student Categories',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.studentcategory', verbose_name='ប្រភេទសិស្ស / Student Category'),
        ),
    ]
