# Generated by Django 6.1 on 2026-08-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentcategory_student_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_start_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ខែ ១ - មករា (January)'), (2, 'ខែ ២ - កុម្ភៈ (February)'), (3, 'ខែ ៣ - មីនា (March)'), (4, 'ខែ ៤ - មេសា (April)'), (5, 'ខែ ៥ - ឧសភា (May)'), (6, 'ខែ ៦ - មិថុនា (June)'), (7, 'ខែ ៧ - កក្កដា (July)'), (8, 'ខែ ៨ - សីហា (August)'), (9, 'ខែ ៩ - កញ្ញា (September)'), (10, 'ខែ ១០ - តុលា (October)'), (11, 'ខែ ១១ - វិច្ឆិកា (November)'), (12, 'ខែ ១២ - ធ្នូ (December)')], help_text='ខែដែលសិស្សត្រូវចាប់ផ្តើមបង់ប្រាក់ (ទុកទទេដើម្បីគិតចាប់ពីដើមឆ្នាំសិក្សា)', null=True, verbose_name='ខែចាប់ផ្តើមបង់ប្រាក់ / Fee Start Month'),
        ),
    ]
