# Generated by Django 6.1 on 2026-08-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_fee_start_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_end_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ខែ ១ - មករា (January)'), (2, 'ខែ ២ - កុម្ភៈ (February)'), (3, 'ខែ ៣ - មីនា (March)'), (4, 'ខែ ៤ - មេសា (April)'), (5, 'ខែ ៥ - ឧសភា (May)'), (6, 'ខែ ៦ - មិថុនា (June)'), (7, 'ខែ ៧ - កក្កដា (July)'), (8, 'ខែ ៨ - សីហា (August)'), (9, 'ខែ ៩ - កញ្ញា (September)'), (10, 'ខែ ១០ - តុលា (October)'), (11, 'ខែ ១១ - វិច្ឆិកា (November)'), (12, 'ខែ ១២ - ធ្នូ (December)')], help_text='ខែចុងក្រោយដែលសិស្សត្រូវបង់ប្រាក់ (សម្រាប់សិស្សឈប់រៀន ឬផ្អាកការសិក្សា ទុកទទេដើម្បីបង់ដល់ចប់ឆ្នាំ)', null=True, verbose_name='ខែបញ្ចប់/ផ្អាកការបង់ប្រាក់ / Fee End Month'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'កំពុងសិក្សា / Active'), ('SUSPENDED', 'ផ្អាកការសិក្សា / Suspended'), ('DROPPED', 'បោះបង់ការសិក្សា / Dropped'), ('TRANSFERRED', 'ផ្ទេរការសិក្សា / Transferred'), ('GRADUATED', 'បញ្ចប់ការសិក្សា / Graduated')], default='ACTIVE', max_length=20, verbose_name='ស្ថានភាព / Status'),
        ),
    ]
