# Generated by Django 6.1 on 2026-08-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_fee_end_month_alter_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='ឈ្មោះកម្រៃ/អាហារូបករណ៍ / Name (Khmer)')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='កូដសម្គាល់ / Code (e.g. FULL_PAY, SCHOLARSHIP_50)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='ភាគរយបញ្ចុះតម្លៃ (%) / Discount (%)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នា / Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='សកម្ម / Active')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='លំដាប់លំដោយ / Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ប្រភេទកម្រៃ & អាហារូបករណ៍ / Scholarship & Fee Type',
                'verbose_name_plural': 'ប្រភេទកម្រៃ & អាហារូបករណ៍ទាំងអស់ / Scholarship & Fee Types',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='ទិន្នន័យបន្ថែមតាមកម្រិតថ្នាក់ / Grade Specific Data'),
        ),
        migrations.AlterField(
            model_name='student',
            name='scholarship_type',
            field=models.CharField(default='FULL_PAY', max_length=50, verbose_name='ប្រភេទកម្រៃសិក្សា / Fee Type'),
        ),
    ]
