# Generated by Django 6.1 on 2026-08-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_scholarshiptype_student_enrollment_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_suspension_notes',
            field=models.TextField(blank=True, null=True, verbose_name='កំណត់សម្គាល់ដកសិទ្ធិប្រឡង / Exam Suspension Notes'),
        ),
        migrations.AddField(
            model_name='student',
            name='exam_suspension_reason',
            field=models.CharField(blank=True, choices=[('DISCIPLINARY', 'បញ្ហាវិន័យ / ជាប់កិច្ចសន្យា / Disciplinary'), ('SUSPENDED', 'ផ្អាកការសិក្សា / Suspended'), ('DROPPED', 'ឈប់រៀន / Dropped Out'), ('UNEXCUSED_ABSENCE', 'អវត្តមានច្រើនឥតច្បាប់ / Unexcused Absence'), ('FEE_OVERDUE', 'ជំពាក់ប្រាក់កម្រៃ / Fee Overdue'), ('HEALTH', 'បញ្ហាសុខភាព / សម្រាកព្យាបាល / Health Issue'), ('OTHER', 'ផ្សេងៗ / Other')], default='DISCIPLINARY', max_length=50, null=True, verbose_name='មូលហេតុដកសិទ្ធិប្រឡង / Exam Exclusion Reason'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_exam_suspended',
            field=models.BooleanField(default=False, help_text='កំណត់ដកសិទ្ធិមិនឱ្យសិស្សចូលរួមការប្រឡង', verbose_name='ដកចេញពីការប្រឡង / Disqualified from Exam'),
        ),
    ]
