# Generated by Django 6.1 on 2026-08-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_exam_suspension_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='ឈ្មោះស្ថានភាព (ខ្មែរ) / Name (Khmer)')),
                ('name_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះជាអង់គ្លេស / Name (English)')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='កូដសម្គាល់ / Code (e.g. ACTIVE, SUSPENDED)')),
                ('badge_color', models.CharField(choices=[('success', '🟢 បៃតង (Green)'), ('warning', '🟡 លឿង (Yellow)'), ('danger', '🔴 ក្រហម (Red)'), ('info', '🔵 ខៀវស្រាល (Cyan)'), ('primary', '🟣 ខៀវចាស់ (Blue)'), ('secondary', '⚪ ប្រផេះ (Gray)'), ('dark', '⚫ ខ្មៅ (Dark)')], default='success', max_length=30, verbose_name='ពណ៌សម្គាល់ (Badge Color)')),
                ('category_type', models.CharField(choices=[('ACTIVE_STUDY', 'កំពុងសិក្សា (Active - រាប់ក្នុងបញ្ជីវត្តមាន និងប្រឡង)'), ('SUSPENDED', 'ផ្អាកការសិក្សា (Suspended - ផ្អាកទារប្រាក់ខែ និងដកពីប្រឡង)'), ('LEFT_SCHOOL', 'ឈប់រៀន / ផ្ទេរចេញ (Left / Transferred Out)'), ('COMPLETED', 'បញ្ចប់ការសិក្សា (Graduated / Completed)')], default='ACTIVE_STUDY', max_length=30, verbose_name='ប្រភេទឥរិយាបថ (Behavior Category)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នា / Description')),
                ('is_system_default', models.BooleanField(default=False, verbose_name='ស្ថានភាពគោលរបស់ប្រព័ន្ធ / System Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='សកម្ម / Active')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='លំដាប់លំដោយ / Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ការកំណត់ស្ថានភាពសិក្សា / Student Status Config',
                'verbose_name_plural': 'ការកំណត់ស្ថានភាពសិក្សាទាំងអស់ / Student Status Configs',
                'ordering': ['order', 'id'],
            },
        ),
    ]
