# Generated by Django 6.1 on 2026-08-31 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_alter_classroom_capacity'),
        ('students', '0007_studentstatusconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_repeating_grade',
            field=models.BooleanField(default=False, help_text='សិស្សដែលរៀនត្រួតថ្នាក់ក្នុងកម្រិតថ្នាក់ដដែល', verbose_name='ជាសិស្សត្រួតថ្នាក់ / Is Repeating Grade'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_promotion_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='មូលហេតុឡើង/ត្រួតថ្នាក់ចុងក្រោយ / Last Promotion Reason'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_promotion_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ស្ថានភាពឡើង/ត្រួតថ្នាក់ចុងក្រោយ / Last Promotion Status'),
        ),
        migrations.CreateModel(
            name='StudentPromotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PROMOTE', 'ឡើងថ្នាក់ / Promoted to Next Grade'), ('RETAIN', 'ត្រួតថ្នាក់ / Retained in Same Grade'), ('GRADUATE', 'បញ្ចប់ការសិក្សា / Graduated'), ('TRANSFER', 'ផ្ទេរចេញ / Transferred Out'), ('DROP', 'ឈប់រៀន / Dropped Out')], default='PROMOTE', max_length=20, verbose_name='សកម្មភាព / Action')),
                ('standard_reason', models.CharField(choices=[('PASSED_YEAR', 'ជាប់មធ្យមភាគប្រចាំឆ្នាំ (Passed Yearly Average)'), ('FAILED_YEAR', 'ធ្លាក់មធ្យមភាគប្រចាំឆ្នាំ (< ៥០.០០) (Failed Yearly Average)'), ('EXCESSIVE_ABSENCE', 'អវត្តមានច្រើនហួសកម្រិតកំណត់ (Excessive Absences)'), ('VOLUNTARY_RETENTION', 'សុំត្រួតថ្នាក់ដោយស្ម័គ្រចិត្ត (Voluntary Grade Retention)'), ('DISCIPLINARY_BOARD', 'សេចក្តីសម្រេចក្រុមប្រឹក្សាវិន័យ (Disciplinary Board Decision)'), ('TEST_SCORE_LOW', 'លទ្ធផលតេស្តសមត្ថភាពមិនគ្រប់ (Low Standardized Test Score)'), ('EXCELLENT_DOUBLE_PROMOTION', 'លទ្ធផលសិក្សាឆ្នើម / លោតថ្នាក់ (Double Promotion)'), ('OTHER', 'ផ្សេងៗ (Other Reason)')], default='PASSED_YEAR', max_length=50, verbose_name='មូលហេតុស្តង់ដារ / Standard Reason')),
                ('custom_notes', models.TextField(blank=True, null=True, verbose_name='កំណត់សម្គាល់ & មូលហេតុលម្អិត / Notes & Reason Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទ & ម៉ោង / Created At')),
                ('from_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_from', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សាដើម / From Year')),
                ('from_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_from_class', to='academics.classroom', verbose_name='ថ្នាក់ដើម / From Class')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_promotions', to=settings.AUTH_USER_MODEL, verbose_name='ចាត់ចែងដោយ / Processed By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='students.student', verbose_name='សិស្ស / Student')),
                ('to_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_to', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សាថ្មី / To Year')),
                ('to_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_to_class', to='academics.classroom', verbose_name='ថ្នាក់ថ្មី / To Class')),
            ],
            options={
                'verbose_name': 'កំណត់ត្រាឡើង/ត្រួតថ្នាក់ / Student Promotion Record',
                'verbose_name_plural': 'កំណត់ត្រាឡើង/ត្រួតថ្នាក់ទាំងអស់ / Student Promotion Records',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
