# Generated by Django 6.1 on 2026-09-01 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_dailyreportprintconfig'),
        ('students', '0008_student_is_repeating_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYearStudentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year_name', models.CharField(max_length=150, verbose_name='ឈ្មោះឆ្នាំសិក្សា / Academic Year Name')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទរក្សាទុក / Archived At')),
                ('action_type', models.CharField(choices=[('SOFT_UNENROLL', 'ដកសិស្សចេញពីឆ្នាំ (Soft Unenroll & Clear)'), ('PURGE_DELETE', 'លុបសិស្សចេញពីប្រព័ន្ធ (Full Purge & Delete)')], default='SOFT_UNENROLL', max_length=30, verbose_name='ប្រភេទប្រតិបត្តិការ / Action Type')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name='ចំនួនសិស្ស / Students Count')),
                ('classrooms_count', models.PositiveIntegerField(default=0, verbose_name='ចំនួនថ្នាក់ / Classrooms Count')),
                ('grades_count', models.PositiveIntegerField(default=0, verbose_name='ចំនួនកំណត់ត្រាពិន្ទុ / Grades Count')),
                ('attendances_count', models.PositiveIntegerField(default=0, verbose_name='ចំនួនកំណត់ត្រាវត្តមាន / Attendances Count')),
                ('fees_count', models.PositiveIntegerField(default=0, verbose_name='ចំនួនវិក្កយបត្រ / Fees Count')),
                ('archive_payload', models.JSONField(blank=True, default=dict, verbose_name='ទិន្នន័យ Snapshot (JSON) / Archive Payload')),
                ('archive_excel', models.FileField(blank=True, null=True, upload_to='archives/students/', verbose_name='ឯកសារ Excel ប័ណ្ណសារ / Archive Excel File')),
                ('confirmation_note', models.TextField(blank=True, null=True, verbose_name='កំណត់សម្គាល់សុវត្ថិភាព / Confirmation Note')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_archives', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_archives_created', to=settings.AUTH_USER_MODEL, verbose_name='រៀបចំដោយ / Archived By')),
            ],
            options={
                'verbose_name': 'ប័ណ្ណសារសិស្សប្រចាំឆ្នាំ / Student Year Archive',
                'verbose_name_plural': 'ប័ណ្ណសារសិស្សប្រចាំឆ្នាំទាំងអស់ / Student Year Archives',
                'ordering': ['-archived_at'],
            },
        ),
    ]
