# Generated by Django 6.1 on 2026-09-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_academicyearstudentarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'កំពុងសិក្សា / Active'), ('SUSPENDED', 'ផ្អាកការសិក្សា / Suspended'), ('DROPPED', 'បោះបង់ការសិក្សា / Dropped'), ('TRANSFERRED', 'ផ្ទេរការសិក្សា / Transferred'), ('GRADUATED', 'បញ្ចប់ការសិក្សា / Graduated')], default='ACTIVE', max_length=50, verbose_name='ស្ថានភាព / Status'),
        ),
        migrations.AlterField(
            model_name='studentpromotionrecord',
            name='action',
            field=models.CharField(choices=[('PROMOTE', 'ឡើងថ្នាក់ / Promoted to Next Grade'), ('RETAIN', 'ត្រួតថ្នាក់ / Retained in Same Grade'), ('GRADUATE', 'បញ្ចប់ការសិក្សា / Graduated'), ('TRANSFER', 'ផ្ទេរចេញ / Transferred Out'), ('DROP', 'ឈប់រៀន / Dropped Out')], default='PROMOTE', max_length=50, verbose_name='សកម្មភាព / Action'),
        ),
        migrations.AlterField(
            model_name='studentpromotionrecord',
            name='standard_reason',
            field=models.CharField(choices=[('PASSED_YEAR', 'ជាប់មធ្យមភាគប្រចាំឆ្នាំ (Passed Yearly Average)'), ('FAILED_YEAR', 'ធ្លាក់មធ្យមភាគប្រចាំឆ្នាំ (< ៥០.០០) (Failed Yearly Average)'), ('EXCESSIVE_ABSENCE', 'អវត្តមានច្រើនហួសកម្រិតកំណត់ (Excessive Absences)'), ('VOLUNTARY_RETENTION', 'សុំត្រួតថ្នាក់ដោយស្ម័គ្រចិត្ត (Voluntary Grade Retention)'), ('DISCIPLINARY_BOARD', 'សេចក្តីសម្រេចក្រុមប្រឹក្សាវិន័យ (Disciplinary Board Decision)'), ('TEST_SCORE_LOW', 'លទ្ធផលតេស្តសមត្ថភាពមិនគ្រប់ (Low Standardized Test Score)'), ('EXCELLENT_DOUBLE_PROMOTION', 'លទ្ធផលសិក្សាឆ្នើម / លោតថ្នាក់ (Double Promotion)'), ('OTHER', 'ផ្សេងៗ (Other Reason)')], default='PASSED_YEAR', max_length=100, verbose_name='មូលហេតុស្តង់ដារ / Standard Reason'),
        ),
    ]
