# Generated by Django 6.1 on 2026-09-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo_drive_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='រូបថតលើ Google Drive (URL) / Google Drive Photo URL'),
        ),
    ]
