# Generated by Django 6.1 on 2026-09-14 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_classsubject_teacher_code'),
        ('students', '0011_student_photo_drive_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='បានផ្ទៀងផ្ទាត់ព័ត៌មាន / Is Verified'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទផ្ទៀងផ្ទាត់ចុងក្រោយ / Last Verified At'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_verified_by_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះអ្នកផ្ទៀងផ្ទាត់ចុងក្រោយ / Last Verified By Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_verified_by_role',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='តួនាទីអ្នកផ្ទៀងផ្ទាត់ចុងក្រោយ / Last Verified By Role'),
        ),
        migrations.AddField(
            model_name='student',
            name='verification_round',
            field=models.PositiveIntegerField(default=0, verbose_name='ជុំផ្ទៀងផ្ទាត់ / Verification Round'),
        ),
        migrations.CreateModel(
            name='StudentVerificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='ឧ. ការបំពេញ និងផ្ទៀងផ្ទាត់ព័ត៌មានសិស្សដើមឆ្នាំ ២០២៦-២០២៧ (ជុំទី១)', max_length=200, verbose_name='ឈ្មោះយុទ្ធនាការ / ជុំផ្ទៀងផ្ទាត់ (Campaign Title)')),
                ('round_number', models.PositiveIntegerField(default=1, help_text='លេខជុំ (១, ២, ៣...) អនុញ្ញាតឱ្យធ្វើច្រើនដងដើម្បីផ្ទៀងផ្ទាត់ព័ត៌មានសិស្ស', verbose_name='ជុំទី / Round Number')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទចាប់ផ្តើម / Start Date & Time')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទផុតកំណត់ / End Date & Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='បើកដំណើរការ / Active Status')),
                ('require_confirmation_for_existing', models.BooleanField(default=True, help_text='តម្រូវឱ្យសិស្ស អាណាព្យាបាល ឬគ្រូដែលកំពុងបញ្ចូល ធ្វើការបញ្ជាក់ (Confirm) មុនពេលកែប្រែទិន្នន័យ', verbose_name='ទាមទារការបញ្ជាក់ពេលកែប្រែសិស្សចាស់ / Require Confirmation for Existing Students')),
                ('allow_student_self_confirm', models.BooleanField(default=True, verbose_name='អនុញ្ញាតឱ្យសិស្សបញ្ជាក់ / Allow Student Confirmation')),
                ('allow_parent_confirm', models.BooleanField(default=True, verbose_name='អនុញ្ញាតឱ្យអាណាព្យាបាលបញ្ជាក់ / Allow Parent Confirmation')),
                ('allow_teacher_confirm', models.BooleanField(default=True, verbose_name='អនុញ្ញាតឱ្យគ្រូបង្រៀនបញ្ជាក់ / Allow Teacher Confirmation')),
                ('instructions', models.TextField(blank=True, help_text='សេចក្តីណែនាំបង្ហាញដល់សិស្ស អាណាព្យាបាល និងគ្រូពេលបំពេញទិន្នន័យ', null=True, verbose_name='សេចក្តីណែនាំ / Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_campaigns', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_verification_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='បង្កើតដោយ / Created By')),
                ('target_grades', models.ManyToManyField(blank=True, help_text='ទុកទទេដើម្បីអនុវត្តចំពោះគ្រប់កម្រិតថ្នាក់ទាំងអស់', related_name='verification_campaigns', to='academics.gradelevel', verbose_name='កម្រិតថ្នាក់គោលដៅ / Target Grade Levels')),
            ],
            options={
                'verbose_name': 'យុទ្ធនាការផ្ទៀងផ្ទាត់ព័ត៌មានសិស្ស / Student Verification Campaign',
                'verbose_name_plural': 'យុទ្ធនាការផ្ទៀងផ្ទាត់ព័ត៌មានសិស្សទាំងអស់ / Student Verification Campaigns',
                'ordering': ['-academic_year__start_date', '-round_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeVerificationFormConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_template', models.CharField(choices=[('GENERAL', 'បែបបទចុះឈ្មោះទូទៅ (Admin កំណត់) / General Form'), ('MOEYS_INDIVIDUAL', 'បែបបទសម្រង់ព័ត៌មានសិស្សម្នាក់ៗ (MoEYS Census 35 Columns)'), ('CUSTOM_COMBINED', 'បែបបទរួមបញ្ចូល (General + MoEYS Census)')], default='GENERAL', help_text='ជ្រើសរើសបែបបទដែលត្រូវឱ្យសិស្សកម្រិតថ្នាក់នេះបំពេញ', max_length=30, verbose_name='បែបបទតម្រូវឱ្យសិស្សបំពេញ / Required Form Template')),
                ('custom_instructions', models.TextField(blank=True, null=True, verbose_name='សេចក្តីណែនាំបន្ថែមសម្រាប់កម្រិតនេះ / Grade Instructions')),
                ('is_active', models.BooleanField(default=True, verbose_name='សកម្ម / Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_configurations', to='academics.gradelevel', verbose_name='កម្រិតថ្នាក់ / Grade Level')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_form_configs', to='students.studentverificationcampaign', verbose_name='យុទ្ធនាការ / Campaign (ទុកទទេសម្រាប់ទូទៅ)')),
            ],
            options={
                'verbose_name': 'ការកំណត់បែបបទតាមកម្រិតថ្នាក់ / Grade Form Configuration',
                'verbose_name_plural': 'ការកំណត់បែបបទតាមកម្រិតថ្នាក់ទាំងអស់ / Grade Form Configurations',
                'ordering': ['grade_level__order', 'grade_level__grade_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_by_role', models.CharField(choices=[('STUDENT', 'សិស្ស (Student)'), ('PARENT', 'អាណាព្យាបាល / មាតាបិតា (Parent/Guardian)'), ('TEACHER', 'គ្រូបង្រៀន / គ្រូបន្ទុកថ្នាក់ (Teacher)'), ('ADMIN', 'រដ្ឋបាលសាលា (School Admin)')], default='STUDENT', help_text='តួនាទីអ្នកដែលបានបញ្ជាក់ការកែប្រែទិន្នន័យ (សិស្ស, អាណាព្យាបាល, ឬ គ្រូ)', max_length=20, verbose_name='អ្នកបញ្ជាក់ / Confirmed By Role')),
                ('confirmed_by_name', models.CharField(max_length=150, verbose_name='ឈ្មោះអ្នកបញ្ជាក់ / Confirmer Name')),
                ('confirmed_by_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='លេខទូរស័ព្ទអ្នកបញ្ជាក់ / Confirmer Phone')),
                ('relationship_to_student', models.CharField(blank=True, help_text='ឧ. ខ្លួនឯង (សិស្ស), ឪពុក, ម្តាយ, អាណាព្យាបាល, គ្រូបន្ទុកថ្នាក់', max_length=100, null=True, verbose_name='ទំនាក់ទំនង / មុខងារ (Relationship / Role)')),
                ('is_existing_student', models.BooleanField(default=True, verbose_name='ជាសិស្សមានទិន្នន័យស្រាប់ / Is Existing Student')),
                ('confirmation_notes', models.TextField(blank=True, null=True, verbose_name='កំណត់សម្គាល់ការកែប្រែ / Confirmation Notes / Reason')),
                ('channel', models.CharField(choices=[('PORTAL', 'គេហទំព័រ / Web Portal'), ('MOBILE_APP', 'កម្មវិធីទូរស័ព្ទ / Mobile App')], default='PORTAL', max_length=20, verbose_name='មធ្យោបាយបញ្ចូល / Channel (Portal / Mobile App)')),
                ('changes_diff', models.JSONField(blank=True, default=dict, verbose_name='សង្ខេបទិន្នន័យកែប្រែ / Changes Diff (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='អាសយដ្ឋាន IP / IP Address')),
                ('verified_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទ & ម៉ោង / Verified At')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='students.studentverificationcampaign', verbose_name='យុទ្ធនាការ / Verification Campaign')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='students.student', verbose_name='សិស្ស / Student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_verification_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='គណនីអ្នកបញ្ចូល / Logged-in User')),
            ],
            options={
                'verbose_name': 'កំណត់ត្រាបញ្ជាក់ព័ត៌មានសិស្ស / Student Verification Log',
                'verbose_name_plural': 'កំណត់ត្រាបញ្ជាក់ព័ត៌មានសិស្សទាំងអស់ / Student Verification Logs',
                'ordering': ['-verified_at', '-id'],
            },
        ),
    ]
