# Generated by Django 6.1 on 2026-09-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_is_verified_student_last_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, help_text='សាលារៀន និងឆ្នាំសិក្សាចាស់ដែលសិស្សបានរៀនពីមុន (ឧ. បឋមសិក្សា ហ៊ុន សែន ២០២៤-២០២៥)', max_length=255, null=True, verbose_name='ឆ្នាំសិក្សាចាស់មកពីសាលា / Previous School & Academic Year'),
        ),
    ]
