# Generated by Django 6.1 on 2026-08-30 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True, verbose_name='FCM Token')),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20, verbose_name='ប្រភេទឧបករណ៍')),
                ('device_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះឧបករណ៍')),
                ('app_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='ជំនាន់ App')),
                ('is_active', models.BooleanField(default=True, verbose_name='ដំណើរការ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទបង្កើត')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='កែប្រែចុងក្រោយ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកប្រើប្រាស់')),
            ],
            options={
                'verbose_name': 'Device FCM Token',
                'verbose_name_plural': 'Device FCM Tokens',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ចំណងជើង')),
                ('body', models.TextField(verbose_name='ខ្លឹមសារ')),
                ('data_payload', models.JSONField(blank=True, default=dict, verbose_name='Data Payload')),
                ('is_read', models.BooleanField(default=False, verbose_name='បានអាន')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទផ្ញើ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_notifications', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកទទួល')),
            ],
            options={
                'verbose_name': 'Mobile Notification',
                'verbose_name_plural': 'Mobile Notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
