# Generated by Django 6.1 on 2026-08-20 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='កាលបរិច្ឆេទ / Date')),
                ('session', models.CharField(choices=[('FULL_DAY', 'ពេញមួយថ្ងៃ / Full Day'), ('MORNING', 'ពេលព្រឹក / Morning'), ('AFTERNOON', 'ពេលរសៀល / Afternoon')], default='FULL_DAY', max_length=20, verbose_name='វេនសិក្សា / Session')),
                ('status', models.CharField(choices=[('PRESENT', 'វត្តមាន / Present'), ('ABSENT', 'អវត្តមានឥតច្បាប់ / Absent (Unexcused)'), ('PERMISSION', 'អវត្តមានមានច្បាប់ / Excused Permission'), ('LATE', 'មកយឺត / Late')], default='PRESENT', max_length=20, verbose_name='ស្ថានភាពវត្តមាន / Status')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='មូលហេតុ / កំណត់ចំណាំ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='academics.classroom', verbose_name='ថ្នាក់រៀន / Classroom')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកស្រង់វត្តមាន / Recorded By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='សិស្ស / Student')),
            ],
            options={
                'verbose_name': 'វត្តមានសិស្ស / Student Attendance',
                'verbose_name_plural': 'វត្តមានសិស្សទាំងអស់ / Student Attendances',
                'ordering': ['-date', 'student'],
                'unique_together': {('student', 'date', 'session')},
            },
        ),
    ]
