# Generated by Django 6.1 on 2026-08-21 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_commune_code_alter_district_code_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='period_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ម៉ោងទី / Period Number'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attendances', to='academics.subject', verbose_name='មុខវិជ្ជា / Subject'),
        ),
    ]
