# Generated by Django 6.1 on 2026-08-21 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_commune_code_alter_district_code_and_more'),
        ('attendance', '0002_studentattendance_period_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='session',
            field=models.CharField(choices=[('MORNING', 'ពេលព្រឹក / Morning'), ('AFTERNOON', 'ពេលរសៀល / Afternoon')], default='MORNING', max_length=20, verbose_name='វេនសិក្សា / Session'),
        ),
        migrations.CreateModel(
            name='AttendanceSubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='កាលបរិច្ឆេទ / Date')),
                ('session', models.CharField(choices=[('MORNING', 'ពេលព្រឹក / Morning'), ('AFTERNOON', 'ពេលរសៀល / Afternoon')], max_length=20, verbose_name='វេនសិក្សា / Session')),
                ('period_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ម៉ោងទី / Period Number')),
                ('submission_count', models.PositiveIntegerField(default=1, verbose_name='ចំនួនដងដែលបានបញ្ជូន / Submission Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='academics.classroom', verbose_name='ថ្នាក់រៀន / Classroom')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកស្រង់វត្តមាន / Recorded By')),
            ],
            options={
                'verbose_name': 'កំណត់ត្រាការបញ្ជូនវត្តមាន / Attendance Submission Log',
                'verbose_name_plural': 'កំណត់ត្រាការបញ្ជូនវត្តមានទាំងអស់ / Attendance Submission Logs',
                'ordering': ['-date', 'classroom', 'period_number'],
                'unique_together': {('classroom', 'date', 'session', 'period_number')},
            },
        ),
    ]
