# Generated by Django 6.1 on 2026-08-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_studentattendance_session_and_more'),
        ('students', '0002_studentcategory_student_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'date', 'session', 'period_number')},
        ),
    ]
