# Generated by Django 6.1 on 2026-08-22 04:12

import apps.attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_studentattendance_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_grace_minutes', models.PositiveIntegerField(default=30, verbose_name='កំឡុងពេល Deadline អនុញ្ញាតឱ្យចុះវត្តមាន (នាទី) / Submission Grace Window (Mins)')),
                ('management_chat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Group គណៈគ្រប់គ្រងសាលា / Management Telegram Chat ID')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='បិទប្រព័ន្ធជាបណ្តោះអាសន្នសម្រាប់ថែទាំ / Maintenance Mode Lockout')),
                ('maintenance_message', models.TextField(default='ប្រព័ន្ធស្រង់វត្តមានកំពុងបិទដំណើរការជាបណ្តោះអាសន្នដើម្បីធ្វើបច្ចុប្បន្នភាព និងថែទាំបច្ចេកទេស។ សូមអភ័យទោសចំពោះការរំខាន!', verbose_name='សារជូនដំណឹងពេលបិទថែទាំ / Maintenance Notice')),
                ('auto_daily_dispatch_enabled', models.BooleanField(default=True, verbose_name='បើកដំណើរការផ្ញើរបាយការណ៍ស្វ័យប្រវត្តិតាម Telegram / Auto Daily Telegram Dispatch')),
                ('daily_dispatch_schedule', models.JSONField(default=apps.attendance.models.get_default_dispatch_schedule, verbose_name='កាលវិភាគម៉ោងផ្ញើប្រចាំថ្ងៃ (១=ច័ន្ទ ... ៧=អាទិត្យ) / Daily Dispatch Schedule')),
                ('auto_send_student_summary', models.BooleanField(default=True, verbose_name='ផ្ញើសង្ខេបអវត្តមានសិស្សប្រចាំថ្ងៃ / Auto Send Student Summary')),
                ('auto_send_teacher_summary', models.BooleanField(default=True, verbose_name='ផ្ញើសង្ខេបវត្តមានគ្រូប្រចាំថ្ងៃ / Auto Send Teacher Summary')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ការកំណត់ប្រព័ន្ធវត្តមាន និង Telegram / Attendance & Telegram Setting',
                'verbose_name_plural': 'ការកំណត់ប្រព័ន្ធវត្តមាន និង Telegram / Attendance & Telegram Settings',
            },
        ),
    ]
