# Generated by Django 6.1 on 2026-08-22 05:42

import apps.attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesetting',
            name='period_grace_minutes',
            field=models.JSONField(default=apps.attendance.models.get_default_period_grace_minutes, verbose_name='កំឡុងពេល Deadline តាមម៉ោងនីមួយៗ (ម៉ោងទី១-៨) / Period Grace Minutes (P1-P8)'),
        ),
        migrations.AlterField(
            model_name='attendancesetting',
            name='submission_grace_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='កំឡុងពេល Deadline អនុញ្ញាតឱ្យចុះវត្តមានទូទៅ (នាទី) / Global Submission Grace Window (Mins)'),
        ),
    ]
