# Generated by Django 6.1 on 2026-08-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancesetting_period_grace_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesetting',
            name='management_chat_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Telegram Group គណៈគ្រប់គ្រងសាលា (អាចដាក់ច្រើន Chat ID) / Management Telegram Chat IDs'),
        ),
    ]
