# Generated by Django 6.1 on 2026-08-26 06:32

import apps.attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendancesetting_management_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesetting',
            name='custom_dispatch_groups',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Group Telegram ផ្សេងៗទៀត (ដាក់ Chat IDs ដោយខណ្ឌសញ្ញាក្បៀស) / Additional Custom Group Chat IDs'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='dispatch_to_guardians',
            field=models.BooleanField(default=True, verbose_name='ផ្ញើទៅអាណាព្យាបាលផ្ទាល់ / Send to Direct Guardians'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='dispatch_to_homeroom',
            field=models.BooleanField(default=True, verbose_name='ផ្ញើទៅគ្រូបន្ទុកថ្នាក់ & Group ថ្នាក់ / Send to Homeroom Teachers & Class Groups'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='dispatch_to_management',
            field=models.BooleanField(default=True, verbose_name='ផ្ញើទៅ Group គណៈគ្រប់គ្រងសាលា / Send to Management Group'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='hourly_dispatch_enabled',
            field=models.BooleanField(default=True, verbose_name='បើកដំណើរការផ្ញើបញ្ជីអវត្តមានស្វ័យប្រវត្តិតាមម៉ោង / Enable Hourly Auto Dispatch'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='period_dispatch_times',
            field=models.JSONField(default=apps.attendance.models.get_default_period_dispatch_times, verbose_name='ម៉ោងកំណត់ (Deadline) សម្រាប់ផ្ញើអវត្តមានតាមម៉ោងនីមួយៗ (P1-P8) / Period Dispatch Deadlines'),
        ),
    ]
