# Generated by Django 6.1 on 2026-08-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendancesetting_custom_dispatch_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesetting',
            name='custom_dispatch_groups',
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='allow_monitor_assembly_recording',
            field=models.BooleanField(default=True, verbose_name='អនុញ្ញាតឱ្យប្រធានថ្នាក់/អនុប្រធានថ្នាក់ស្រង់វត្តមានតាមទូរស័ព្ទ / Allow Class Monitors to record via Mobile/Tablet'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='assembly_afternoon_end',
            field=models.TimeField(default='12:50', verbose_name='ម៉ោងបញ្ចប់ស្រង់វត្តមានពេលរសៀល (ឧ. 12:50)'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='assembly_afternoon_start',
            field=models.TimeField(default='12:30', verbose_name='ម៉ោងចាប់ផ្តើមស្រង់វត្តមានពេលរសៀល (ឧ. 12:30)'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='assembly_morning_end',
            field=models.TimeField(default='06:50', verbose_name='ម៉ោងបញ្ចប់ស្រង់វត្តមានពេលព្រឹក (ឧ. 06:50)'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='assembly_morning_start',
            field=models.TimeField(default='06:30', verbose_name='ម៉ោងចាប់ផ្តើមស្រង់វត្តមានពេលព្រឹក (ឧ. 06:30)'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='assembly_telegram_alert',
            field=models.BooleanField(default=True, verbose_name='ជូនដំណឹង Telegram ទៅគណៈគ្រប់គ្រងភ្លាមៗក្រោយគោរពទង់ជាតិ / Instant Management Telegram Alert'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='enable_assembly_attendance',
            field=models.BooleanField(default=True, verbose_name='បើកដំណើរការស្រង់វត្តមានពេលគោរពទង់ជាតិ/មុនម៉ោងចូលរៀន / Enable Assembly Attendance'),
        ),
    ]
