# Generated by Django 6.1 on 2026-08-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_remove_attendancesetting_custom_dispatch_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesetting',
            name='allow_all_teachers_assembly_recording',
            field=models.BooleanField(default=True, verbose_name='អនុញ្ញាតឱ្យគ្រូបង្រៀនទាំងអស់អាចស្រង់វត្តមានគោរពទង់ជាតិ / Allow All Teachers to record Assembly Attendance'),
        ),
    ]
