# Generated by Django 6.1 on 2026-08-30 16:08

import apps.attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendancesetting_allow_all_teachers_assembly_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesetting',
            name='assembly_active_days',
            field=models.JSONField(default=apps.attendance.models.get_default_assembly_active_days, verbose_name='ថ្ងៃក្នុងសប្តាហ៍ដែលត្រូវស្រង់វត្តមានគោរពទង់ជាតិ (១=ច័ន្ទ ... ៦=សៅរ៍) / Active Weekdays'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='assembly_alarm_enabled',
            field=models.BooleanField(default=True, verbose_name='បើកដំណើរការ Alarm ដាស់តឿនដល់ម៉ោងស្រង់វត្តមាន / Enable Assembly Alarm'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='assembly_alarm_message',
            field=models.CharField(default='⏰ ដល់ម៉ោងស្រង់វត្តមានពេលគោរពទង់ជាតិហើយ! សូមស្រង់ឱ្យបានមុនម៉ោងកំណត់', max_length=300, verbose_name='សារដាស់តឿន Alarm / Custom Alarm Message'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='assembly_disabled_date',
            field=models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទដែលបានផ្អាក / Cancelled Date'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='assembly_disabled_reason',
            field=models.TextField(blank=True, default='', verbose_name='មូលហេតុផ្អាកការស្រង់វត្តមាន (ផ្ញើជា Pop-Chat / Live Notice) / Cancellation Reason'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='assembly_last_alarm_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទដែលបានបន្លឺ Alarm ចុងក្រោយ / Last Alarm Sent At'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='is_assembly_disabled_today',
            field=models.BooleanField(default=False, verbose_name='ផ្អាកការស្រង់វត្តមានសម្រាប់ថ្ងៃនេះ (Emergency Cancel for Today)'),
        ),
    ]
