# Generated by Django 6.1 on 2026-08-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendancesetting_assembly_active_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesetting',
            name='assembly_auto_alarm_enabled',
            field=models.BooleanField(default=True, verbose_name='បន្លឺ Alarm និងដាស់តឿនដោយស្វ័យប្រវត្តិតាមម៉ោងចាប់ផ្តើម / Auto-Alarm on Session Start Time'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='enable_assembly_afternoon',
            field=models.BooleanField(default=True, verbose_name='បើកដំណើរការស្រង់វត្តមានពេលរសៀល / Enable Afternoon Assembly Attendance'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='enable_assembly_morning',
            field=models.BooleanField(default=True, verbose_name='បើកដំណើរការស្រង់វត្តមានពេលព្រឹក / Enable Morning Assembly Attendance'),
        ),
    ]
