# Generated by Django 6.1 on 2026-09-08 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendancesetting_assembly_auto_alarm_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesetting',
            name='assembly_afternoon_end',
            field=models.TimeField(default=datetime.time(12, 50), verbose_name='ម៉ោងបញ្ចប់ស្រង់វត្តមានពេលរសៀល (ឧ. 12:50)'),
        ),
        migrations.AlterField(
            model_name='attendancesetting',
            name='assembly_afternoon_start',
            field=models.TimeField(default=datetime.time(12, 30), verbose_name='ម៉ោងចាប់ផ្តើមស្រង់វត្តមានពេលរសៀល (ឧ. 12:30)'),
        ),
        migrations.AlterField(
            model_name='attendancesetting',
            name='assembly_morning_end',
            field=models.TimeField(default=datetime.time(6, 50), verbose_name='ម៉ោងបញ្ចប់ស្រង់វត្តមានពេលព្រឹក (ឧ. 06:50)'),
        ),
        migrations.AlterField(
            model_name='attendancesetting',
            name='assembly_morning_start',
            field=models.TimeField(default=datetime.time(6, 30), verbose_name='ម៉ោងចាប់ផ្តើមស្រង់វត្តមានពេលព្រឹក (ឧ. 06:30)'),
        ),
    ]
