# Generated by Django 6.1 on 2026-09-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_attendancesetting_assembly_afternoon_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesetting',
            name='custom_dispatch_groups',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Group Telegram ផ្សេងៗទៀត (Custom Group Chat IDs) / Other Telegram Groups'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='homeroom_group_chat_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Telegram Group គ្រូបន្ទុកថ្នាក់ (អាចដាក់ច្រើន Chat ID) / Homeroom Teachers Group Chat IDs'),
        ),
    ]
