# Generated by Django 6.1 on 2026-09-06 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ឈ្មោះអ្នកផ្ញើ / Sender Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='អ៊ីមែល / Email')),
                ('phone', models.CharField(max_length=50, verbose_name='លេខទូរស័ព្ទ / Phone Number')),
                ('subject', models.CharField(max_length=200, verbose_name='ប្រធានបទ / Subject')),
                ('message', models.TextField(verbose_name='ខ្លឹមសារសារ / Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='បានអានរួច / Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទផ្ញើ / Sent Date')),
            ],
            options={
                'verbose_name': 'សារទំនាក់ទំនងពីភ្ញៀវ / Contact Inquiry',
                'verbose_name_plural': 'សារទំនាក់ទំនងពីភ្ញៀវទាំងអស់ / Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ឈ្មោះអាល់ប៊ុម / Album Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នា / Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='website/gallery/covers/', verbose_name='រូបភាពតំណាង / Cover Photo')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទកម្មវិធី / Event Date')),
                ('is_published', models.BooleanField(default=True, verbose_name='ផ្សាយជាសាធារណៈ / Is Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទបង្កើត / Created At')),
            ],
            options={
                'verbose_name': 'អាល់ប៊ុមរូបភាព / Gallery Album',
                'verbose_name_plural': 'អាល់ប៊ុមរូបភាពទាំងអស់ / Gallery Albums',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ចំណងជើងបដា / Banner Title')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='ចំណងជើងរង / Subtitle')),
                ('badge_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='ស្លាកចំណាំ (Badge) / Badge Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/banners/', verbose_name='រូបភាពបដា / Banner Background Image')),
                ('primary_btn_text', models.CharField(blank=True, default='ស្វែងយល់បន្ថែម', max_length=100, verbose_name='ប៊ូតុងទី១ / Primary Button Text')),
                ('primary_btn_url', models.CharField(blank=True, default='#about', max_length=255, verbose_name='តំណភ្ជាប់ប៊ូតុងទី១ / Primary Button URL')),
                ('secondary_btn_text', models.CharField(blank=True, default='ចូលប្រព័ន្ធគ្រប់គ្រង', max_length=100, verbose_name='ប៊ូតុងទី២ / Secondary Button Text')),
                ('secondary_btn_url', models.CharField(blank=True, default='/accounts/login/', max_length=255, verbose_name='តំណភ្ជាប់ប៊ូតុងទី២ / Secondary Button URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='លំដាប់បង្ហាញ / Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='សកម្ម / Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ថ្ងៃបង្កើត / Created At')),
            ],
            options={
                'verbose_name': 'ផ្ទាំងបដាទំព័រដើម / Homepage Banner',
                'verbose_name_plural': 'ផ្ទាំងបដាទំព័រដើមទាំងអស់ / Homepage Banners',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='website/gallery/photos/', verbose_name='រូបថត / Photo')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='ចំណងជើងរូបភាព / Caption')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='លំដាប់រៀប / Order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='ថ្ងៃបញ្ចូល / Uploaded At')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.galleryalbum', verbose_name='អាល់ប៊ុម / Album')),
            ],
            options={
                'verbose_name': 'រូបថត / Photo',
                'verbose_name_plural': 'រូបថតទាំងអស់ / Photos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ចំណងជើងអត្ថបទ / Article Title')),
                ('category', models.CharField(choices=[('NEWS', 'ព័ត៌មានទូទៅ / General News'), ('EVENT', 'ព្រឹត្តិការណ៍ & កម្មវិធីសាលា / School Event'), ('ACADEMICS', 'កម្មវិធីសិក្សា & អប់រំ / Academics'), ('ACHIEVEMENT', 'ស្នាដៃ & មោទនភាព / Achievements'), ('SPORTS', 'កីឡា & សុខភាព / Sports & Health'), ('OTHER', 'ផ្សេងៗ / Other')], default='NEWS', max_length=30, verbose_name='ប្រភេទ / Category')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='ខ្លឹមសារសង្ខេប / Short Excerpt')),
                ('content', models.TextField(verbose_name='ខ្លឹមសារលម្អិត / Full Content')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='website/news/', verbose_name='រូបភាព Cover / Featured Image')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='ចំនួនអ្នកអាន / Views Count')),
                ('is_featured', models.BooleanField(default=False, verbose_name='អត្ថបទលេចធ្លោ (Hero/Pinned) / Featured')),
                ('is_published', models.BooleanField(default=True, verbose_name='ផ្សាយជាសាធារណៈ / Is Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទបង្កើត / Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='កាលបរិច្ឆេទកែប្រែ / Updated At')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកនិពន្ធ / Author')),
            ],
            options={
                'verbose_name': 'អត្ថបទព័ត៌មានសាលា / News Article',
                'verbose_name_plural': 'អត្ថបទព័ត៌មានសាលាទាំងអស់ / News Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
