# Generated by Django 6.1 on 2026-09-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='ខ្លឹមសារលម្អិតភាសាអង់គ្លេស / English Content'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='ខ្លឹមសារសង្ខេបភាសាអង់គ្លេស / English Excerpt'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ចំណងជើងភាសាអង់គ្លេស / English Title'),
        ),
        migrations.AddField(
            model_name='websitebanner',
            name='badge_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ស្លាកចំណាំ (Badge - English)'),
        ),
        migrations.AddField(
            model_name='websitebanner',
            name='primary_btn_text_en',
            field=models.CharField(blank=True, default='Learn More', max_length=100, verbose_name='ប៊ូតុងទី១ (English)'),
        ),
        migrations.AddField(
            model_name='websitebanner',
            name='secondary_btn_text_en',
            field=models.CharField(blank=True, default='Portal Login', max_length=100, verbose_name='ប៊ូតុងទី២ (English)'),
        ),
        migrations.AddField(
            model_name='websitebanner',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ចំណងជើងរង (English)'),
        ),
        migrations.AddField(
            model_name='websitebanner',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ចំណងជើងបដា (English)'),
        ),
    ]
