# Generated by Django 6.1 on 2026-09-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_newsarticle_content_en_newsarticle_excerpt_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitebanner',
            name='primary_btn_text',
            field=models.CharField(blank=True, default='ឈ្វេងយល់បន្ថែម', max_length=100, verbose_name='ប៊ូតុងទី១ / Primary Button Text'),
        ),
    ]
