# Generated by Django 6.1 on 2026-09-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_websitebanner_primary_btn_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryalbum',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នា (English) / English Description'),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ឈ្មោះអាល់ប៊ុម (English) / English Album Title'),
        ),
    ]
