# Generated by Django 6.1 on 2026-08-20 09:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=50, unique=True, verbose_name='កូដសម្គាល់គ្រូ / Teacher ID')),
                ('khmer_name', models.CharField(max_length=150, verbose_name='ឈ្មោះខ្មែរ / Khmer Name')),
                ('latin_name', models.CharField(max_length=150, verbose_name='ឈ្មោះឡាតាំង / Latin Name')),
                ('gender', models.CharField(choices=[('M', 'ប្រុស / Male'), ('F', 'ស្រី / Female')], default='M', max_length=5, verbose_name='ភេទ / Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='ថ្ងៃខែឆ្នាំកំណើត / Date of Birth')),
                ('phone', models.CharField(max_length=30, verbose_name='លេខទូរស័ព្ទ / Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='អ៊ីមែល / Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='អាសយដ្ឋានបច្ចុប្បន្ន / Current Address')),
                ('qualification', models.CharField(blank=True, max_length=200, null=True, verbose_name='កម្រិតវប្បធម៌ / Qualification')),
                ('specialization', models.CharField(max_length=200, verbose_name='ឯកទេសបង្រៀន / Specialization')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, verbose_name='ប្រាក់ខែគោល ($) / Base Salary')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទចូលបម្រើការ / Hire Date')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/', verbose_name='រូបថត / Photo')),
                ('resume', models.FileField(blank=True, null=True, upload_to='teachers/docs/', verbose_name='ឯកសារប្រវត្តិរូប / Resume/CV')),
                ('status', models.CharField(choices=[('ACTIVE', 'កំពុងបង្រៀន / Active'), ('ON_LEAVE', 'សម្រាកច្បាប់ / On Leave'), ('RESIGNED', 'លាឈប់ / Resigned')], default='ACTIVE', max_length=20, verbose_name='ស្ថានភាព / Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'គ្រូបង្រៀន / Teacher',
                'verbose_name_plural': 'គ្រូបង្រៀនទាំងអស់ / Teachers',
                'ordering': ['teacher_id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='កាលបរិច្ឆេទ / Date')),
                ('status', models.CharField(choices=[('PRESENT', 'វត្តមាន / Present'), ('LATE', 'មកយឺត / Late'), ('EXCUSED_LEAVE', 'ច្បាប់អនុញ្ញាត / Excused Leave'), ('UNEXCUSED_ABSENCE', 'អវត្តមានឥតច្បាប់ / Unexcused Absence')], default='PRESENT', max_length=30, verbose_name='ស្ថានភាព / Status')),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='ចំនួនកាត់ប្រាក់ ($) / Deduction Amount')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='កំណត់ចំណាំ / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'វត្តមានគ្រូបង្រៀន / Teacher Attendance',
                'verbose_name_plural': 'វត្តមានគ្រូបង្រៀន / Teacher Attendances',
                'ordering': ['-date', 'teacher'],
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
