# Generated by Django 6.1 on 2026-08-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='max_weekly_hours',
            field=models.PositiveIntegerField(default=18, verbose_name='ម៉ោងបង្រៀនអតិបរមា/សប្តាហ៍ / Max Weekly Teaching Hours'),
        ),
    ]
