# Generated by Django 6.1 on 2026-08-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_max_weekly_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_fee_collector',
            field=models.BooleanField(default=False, verbose_name='អនុញ្ញាតឱ្យប្រមូលថវិកា / Fee Collector Permission'),
        ),
    ]
