# Generated by Django 6.1 on 2026-08-22 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_is_fee_collector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', 'ច្បាប់ឈឺ / Sick Leave'), ('PERSONAL', 'ធុរៈផ្ទាល់ខ្លួន / Personal Leave'), ('MISSION', 'បេសកកម្មការងារ / Official Mission'), ('MATERNITY', 'លំហែមាតុភាព / Maternity Leave'), ('OTHER', 'ផ្សេងៗ / Other')], default='PERSONAL', max_length=20, verbose_name='ប្រភេទច្បាប់ / Leave Type')),
                ('start_date', models.DateField(verbose_name='ថ្ងៃចាប់ផ្តើម / Start Date')),
                ('end_date', models.DateField(verbose_name='ថ្ងៃបញ្ចប់ / End Date')),
                ('reason', models.TextField(verbose_name='មូលហេតុសុំច្បាប់ / Reason')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='teachers/leaves/', verbose_name='ឯកសារភ្ជាប់ (បើមាន) / Attachment')),
                ('status', models.CharField(choices=[('PENDING', 'រង់ចាំពិនិត្យ / Pending'), ('APPROVED', 'បានអនុម័ត / Approved'), ('REJECTED', 'បានបដិសេធ / Rejected'), ('CANCELLED', 'បានបោះបង់ / Cancelled')], default='PENDING', max_length=20, verbose_name='ស្ថានភាព / Status')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='មូលហេតុបដិសេធ / Rejection Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_teacher_leaves', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកអនុម័ត / Approved By')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='teachers.teacher', verbose_name='គ្រូបង្រៀន / Teacher')),
            ],
            options={
                'verbose_name': 'ពាក្យសុំច្បាប់គ្រូបង្រៀន / Teacher Leave Request',
                'verbose_name_plural': 'ពាក្យសុំច្បាប់គ្រូបង្រៀនទាំងអស់ / Teacher Leave Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
