# Generated by Django 6.1 on 2026-08-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacherleaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='collector_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Collector Pass Token'),
        ),
    ]
