# Generated by Django 6.1 on 2026-08-26 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_collector_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_qr_checkin', models.BooleanField(default=True, verbose_name='បើកដំណើរការស្កេន Dynamic QR Code')),
                ('enable_face_ai_checkin', models.BooleanField(default=True, verbose_name='បើកដំណើរការ Webcam Face Recognition AI')),
                ('enable_biometric_device', models.BooleanField(default=True, verbose_name='បើកដំណើរការម៉ាស៊ីន Biometric (ZKTeco/Hikvision)')),
                ('enable_usb_fingerprint', models.BooleanField(default=True, verbose_name='បើកដំណើរការឧបករណ៍ USB Fingerprint Reader')),
                ('enable_file_import', models.BooleanField(default=True, verbose_name='បើកដំណើរការ Import File ពី USB Flash Drive')),
                ('enable_timetable_sync', models.BooleanField(default=True, verbose_name='បើកដំណើរការ Sync ពីការស្រង់វត្តមានសិស្ស')),
                ('require_gps_validation', models.BooleanField(default=True, verbose_name='តម្រូវឱ្យផ្ទៀងផ្ទាត់ទីតាំង GPS')),
                ('require_device_binding', models.BooleanField(default=True, verbose_name='តម្រូវឱ្យចងភ្ជាប់ទូរស័ព្ទ (១ គណនី = ១ ទូរស័ព្ទ)')),
                ('require_selfie_snap', models.BooleanField(default=False, verbose_name='តម្រូវឱ្យថតរូប Selfie បញ្ជាក់ពេលស្កេន')),
                ('rolling_qr_interval_seconds', models.PositiveIntegerField(default=20, verbose_name='រយៈពេលផ្លាស់ប្តូរ Dynamic QR Code (វិនាទី)')),
                ('morning_checkin_start', models.TimeField(default='06:30', verbose_name='ម៉ោងចាប់ផ្តើម Check-in ពេលព្រឹក')),
                ('morning_checkin_end', models.TimeField(default='08:30', verbose_name='ម៉ោងផុតកំណត់ Check-in ពេលព្រឹក')),
                ('morning_late_threshold', models.TimeField(default='07:15', verbose_name='ម៉ោងចាត់ទុកថាមកយឺតពេលព្រឹក (Late Cutoff)')),
                ('afternoon_checkin_start', models.TimeField(default='12:30', verbose_name='ម៉ោងចាប់ផ្តើម Check-in ពេលរសៀល')),
                ('afternoon_checkin_end', models.TimeField(default='14:30', verbose_name='ម៉ោងផុតកំណត់ Check-in ពេលរសៀល')),
                ('afternoon_late_threshold', models.TimeField(default='13:15', verbose_name='ម៉ោងចាត់ទុកថាមកយឺតពេលរសៀល (Late Cutoff)')),
                ('biometric_device_ip', models.CharField(default='192.168.1.201', max_length=50, verbose_name='IP ម៉ាស៊ីន Biometric')),
                ('biometric_device_port', models.PositiveIntegerField(default=4370, verbose_name='Port ម៉ាស៊ីន (ZKTeco=4370, Hik=8000)')),
                ('biometric_device_type', models.CharField(choices=[('ZKTECO', 'ZKTeco Standalone (UDP/TCP 4370)'), ('HIKVISION', 'Hikvision ISAPI Terminal (HTTP 80/8000)'), ('GENERIC_PUSH', 'Generic ADMS / Cloud Webhook Push')], default='ZKTECO', max_length=30, verbose_name='ប្រភេទម៉ាស៊ីន Biometric')),
                ('biometric_push_secret', models.CharField(blank=True, max_length=64, null=True, verbose_name='Secret Token សម្រាប់ Push Webhook')),
                ('notify_telegram_on_punch', models.BooleanField(default=True, verbose_name='ជូនដំណឹង Telegram ពេលគ្រូ Check-in')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ការកំណត់វត្តមានគ្រូ & ឧបករណ៍ / Teacher Attendance & Biometric Config',
                'verbose_name_plural': 'ការកំណត់វត្តមានគ្រូ & ឧបករណ៍ / Teacher Attendance & Biometric Config',
            },
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='check_in_method',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='វិធីសាស្ត្រ Check-in'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ម៉ោង Check-In'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ម៉ោង Check-Out'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='មកយឺត / Late'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='នាទីដែលមកយឺត / Late Minutes'),
        ),
        migrations.CreateModel(
            name='TeacherBiometricProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.CharField(blank=True, max_length=120, null=True, verbose_name='កូដឧបករណ៍ដែលបានភ្ជាប់ (Device Binding UUID)')),
                ('device_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះឧបករណ៍ / Device Model')),
                ('face_photo', models.ImageField(blank=True, null=True, upload_to='teachers/faces/', verbose_name='រូបថតគំរូផ្ទៃមុខ / Enrolled Face Photo')),
                ('face_descriptor', models.JSONField(blank=True, null=True, verbose_name='Face Embedding Descriptors Vector')),
                ('card_rfid', models.CharField(blank=True, max_length=50, null=True, verbose_name='លេខកាត RFID / NFC / QR Pass Token')),
                ('zk_pin', models.CharField(blank=True, max_length=50, null=True, verbose_name='លេខកូដសម្គាល់លើម៉ាស៊ីន (Biometric PIN / ID)')),
                ('fingerprint_template', models.TextField(blank=True, null=True, verbose_name='Fingerprint Template (Base64)')),
                ('is_enrolled_face', models.BooleanField(default=False, verbose_name='បានចុះឈ្មោះស្កេនមុខ / Enrolled Face')),
                ('is_enrolled_fingerprint', models.BooleanField(default=False, verbose_name='បានចុះឈ្មោះក្រយៅដៃ / Enrolled Fingerprint')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_profile', to='teachers.teacher', verbose_name='គ្រូបង្រៀន / Teacher')),
            ],
            options={
                'verbose_name': 'ទិន្នន័យ Biometric គ្រូ / Teacher Biometric Profile',
                'verbose_name_plural': 'ទិន្នន័យ Biometric គ្រូទាំងអស់ / Teacher Biometric Profiles',
            },
        ),
        migrations.CreateModel(
            name='TeacherPunchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_time', models.DateTimeField(verbose_name='ពេលវេលាស្កេន / Punch Timestamp')),
                ('date', models.DateField(verbose_name='កាលបរិច្ឆេទ / Date')),
                ('punch_type', models.CharField(choices=[('CHECK_IN', 'ចូល / Check In'), ('CHECK_OUT', 'ចេញ / Check Out'), ('AUTO', 'ស្វ័យប្រវត្តិ / Auto Punch')], default='CHECK_IN', max_length=20, verbose_name='ប្រភេទស្កេន / Punch Type')),
                ('method', models.CharField(choices=[('QR_SCAN', 'Dynamic QR Code (ទូរស័ព្ទ / Mobile QR)'), ('FACE_AI', 'Webcam Face AI Recognition'), ('BIOMETRIC_DEVICE', 'ម៉ាស៊ីន Biometric (ZKTeco/Hikvision)'), ('USB_FINGERPRINT', 'ឧបករណ៍ USB Fingerprint Reader'), ('USB_FILE_IMPORT', 'Import ពី USB Flash Drive'), ('TIMETABLE_SYNC', 'ស្រង់វត្តមានសិស្សតាមកាលវិភាគ'), ('MANUAL_ADMIN', 'រដ្ឋបាលចុះដោយដៃ')], default='QR_SCAN', max_length=30, verbose_name='វិធីសាស្ត្រ / Method')),
                ('status_result', models.CharField(choices=[('ON_TIME', 'ទាន់ពេល / On Time'), ('LATE', 'មកយឺត / Late'), ('EARLY_LEAVE', 'ចេញមុន / Left Early'), ('NORMAL', 'ធម្មតា / Normal')], default='ON_TIME', max_length=30, verbose_name='ស្ថានភាព / Status')),
                ('gps_lat', models.FloatField(blank=True, null=True, verbose_name='រយៈទទឹង GPS (Latitude)')),
                ('gps_lng', models.FloatField(blank=True, null=True, verbose_name='រយៈបណ្តោយ GPS (Longitude)')),
                ('is_within_geofence', models.BooleanField(default=True, verbose_name='ក្នុងបរិវេណសាលា (Within Geofence)')),
                ('device_uuid', models.CharField(blank=True, max_length=120, null=True, verbose_name='កូដឧបករណ៍ / Device UUID')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP Address')),
                ('snapshot_photo', models.ImageField(blank=True, null=True, upload_to='teachers/punch_snapshots/', verbose_name='រូបថត Selfie Snapshot')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='កំណត់ចំណាំ / Notes')),
                ('raw_payload', models.JSONField(blank=True, null=True, verbose_name='Raw Data Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_logs', to='teachers.teacher', verbose_name='គ្រូបង្រៀន / Teacher')),
            ],
            options={
                'verbose_name': 'កំណត់ត្រាស្កេនវត្តមានគ្រូ / Teacher Punch Log',
                'verbose_name_plural': 'កំណត់ត្រាស្កេនវត្តមានគ្រូទាំងអស់ / Teacher Punch Logs',
                'ordering': ['-punch_time', '-id'],
            },
        ),
    ]
