# Generated by Django 6.1 on 2026-08-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_teacherattendanceconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendanceconfig',
            name='active_daily_mode',
            field=models.CharField(choices=[('ALL', 'អនុញ្ញាតគ្រប់ជម្រើស (All Methods Allowed)'), ('OPTION_1_QR', 'ជម្រើសទី ១: ស្កេន Dynamic QR Code ប៉ុណ្ណោះ (Option 1 - QR Only)'), ('OPTION_2_FACE', 'ជម្រើសទី ២: ស្កេនផ្ទៃមុខ Webcam Face AI ប៉ុណ្ណោះ (Option 2 - Face AI Only)'), ('OPTION_3_BIOMETRIC', 'ជម្រើសទី ៣: ម៉ាស៊ីន Biometric ស្កេនមេដៃ/មុខ ប៉ុណ្ណោះ (Option 3 - Hardware Biometric Only)')], default='ALL', max_length=30, verbose_name='ជម្រើសស្កេនវត្តមានប្រចាំថ្ងៃដែលបានកំណត់ដោយ Admin'),
        ),
    ]
