# Generated by Django 6.1 on 2026-08-26 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_teacherattendanceconfig_active_daily_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendanceconfig',
            name='emergency_leave_cutoff_time',
            field=models.TimeField(default='17:00', verbose_name='ម៉ោងកំណត់ចុងក្រោយសម្រាប់សុំច្បាប់បន្ទាន់មុន១ថ្ងៃ'),
        ),
        migrations.AddField(
            model_name='teacherleaverequest',
            name='category',
            field=models.CharField(choices=[('EMERGENCY', 'ការសុំច្បាប់ភ្លាមៗ (បន្ទាន់ / Emergency Leave)'), ('PLANNED', 'ការសុំច្បាប់ទុកជាមុន (គ្រោងទុក / Planned Advance Leave)')], default='PLANNED', max_length=20, verbose_name='ប្រភេទនៃការដាក់ពាក្យសុំច្បាប់'),
        ),
        migrations.AddField(
            model_name='teacherleaverequest',
            name='leave_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='លេខកូដលិខិតសុំច្បាប់'),
        ),
        migrations.AddField(
            model_name='teacherleaverequest',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_leave_requests', to='teachers.teacher', verbose_name='គ្រូបង្រៀនជំនួស (បើមាន) / Substitute Teacher'),
        ),
    ]
