# Generated by Django 6.1 on 2026-08-26 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_teacherattendanceconfig_emergency_leave_cutoff_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherleaverequest',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_teacher_leaves', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកដាក់ពាក្យ / Submitted By'),
        ),
        migrations.AddField(
            model_name='teacherleaverequest',
            name='proxy_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='កំណត់សម្គាល់ការដាក់ពាក្យជំនួស (Proxy Note)'),
        ),
    ]
