# Generated by Django 6.1 on 2026-08-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_teacherleaverequest_applied_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='current_duty',
            field=models.CharField(blank=True, default='គ្រូបង្រៀន', max_length=150, null=True, verbose_name='ភារកិច្ចបច្ចុប្បន្ន / Current Duty'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='permanent_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃខែឆ្នាំតែងតាំងស៊ប់ / Permanent Confirmation Date'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='prakas_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ប្រភេទក្របខ័ណ្ឌ / Civil Servant Category'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='prakas_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ប្រកាសលេខ / Prakas Number'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='prakas_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ឆ្នាំទទួលប្រកាស / Decree Year'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='primary_subject',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='មុខវិជ្ជាឯកទេសទី១ / Subject Specialization 1'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='secondary_subject',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='មុខវិជ្ជាឯកទេសទី២ / Subject Specialization 2'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='state_hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='ថ្ងៃចូលបម្រើការងាររដ្ឋ / State Civil Service Entry Date'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='training_level',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='កម្រិតបណ្តុះបណ្តាល / Pedagogical Training Level'),
        ),
    ]
