# Generated by Django 6.1 on 2026-08-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_teacher_current_duty_teacher_permanent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last_profile_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទផ្ទៀងផ្ទាត់ព័ត៌មានចុងក្រោយ / Last Verified At'),
        ),
        migrations.CreateModel(
            name='TeacherProfileUpdateCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='យុទ្ធនាការផ្ទៀងផ្ទាត់ និងបំពេញព័ត៌មានគ្រូបង្រៀន', max_length=200, verbose_name='ចំណងជើងយុទ្ធនាការ')),
                ('instructions', models.TextField(blank=True, default='សូមលោកគ្រូ-អ្នកគ្រូ មេត្តាពិនិត្យ និងបំពេញព័ត៌មានដែលបានជ្រើសរើសខាងក្រោមឱ្យបានត្រឹមត្រូវ។', verbose_name='សេចក្តីណែនាំដល់គ្រូ')),
                ('is_active', models.BooleanField(default=True, verbose_name='បើកដំណើរការយុទ្ធនាការ / Active')),
                ('allowed_sections', models.JSONField(blank=True, default=list, verbose_name='ផ្នែកព័ត៌មានដែលតម្រូវឱ្យបំពេញ (Tick Selection)')),
                ('target_all', models.BooleanField(default=True, verbose_name='អនុវត្តចំពោះគ្រូទាំងអស់ / Target All Teachers')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទផុតកំណត់ / Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_teachers', models.ManyToManyField(blank=True, related_name='update_campaigns', to='teachers.teacher', verbose_name='គ្រូជាក់លាក់')),
            ],
            options={
                'verbose_name': 'យុទ្ធនាការបំពេញព័ត៌មានគ្រូ / Teacher Profile Update Campaign',
                'verbose_name_plural': 'យុទ្ធនាការបំពេញព័ត៌មានគ្រូទាំងអស់',
                'ordering': ['-created_at'],
            },
        ),
    ]
