# Generated by Django 6.1 on 2026-08-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_seed_moeys_119_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'កំពុងបង្រៀន (សកម្ម) / Active'), ('ON_LEAVE', 'សម្រាកច្បាប់ / On Leave'), ('RETIRED', 'ចូលនិវត្តន៍ / Retired'), ('TRANSFERRED', 'ផ្ទេរចេញ / Transferred'), ('RESIGNED', 'លាឈប់ / Resigned'), ('INACTIVE', 'អសកម្ម / Inactive')], default='ACTIVE', max_length=20, verbose_name='ស្ថានភាព / Status'),
        ),
    ]
