# Generated by Django 6.1 on 2026-08-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_alter_teacher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='លេខទូរស័ព្ទទី២ / Secondary Phone'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='លេខទូរស័ព្ទចម្បង / Primary Phone'),
        ),
    ]
