# Generated by Django 6.1 on 2026-09-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_teacher_phone2_alter_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដគ្រូតាមមុខវិជ្ជា / Teacher Subject Duty Code'),
        ),
    ]
