# Generated by Django 6.1 on 2026-08-20 09:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ឈ្មោះសម័យប្រឡង / Exam Term Name')),
                ('term_type', models.CharField(choices=[('MONTHLY', 'ប្រឡងប្រចាំខែ / Monthly Exam'), ('SEMESTER_1', 'ប្រឡងឆមាសទី១ / Semester 1 Final Exam'), ('SEMESTER_2', 'ប្រឡងឆមាសទី២ / Semester 2 Final Exam'), ('ANNUAL', 'ប្រឡងចុងឆ្នាំ / Annual Final Exam')], default='MONTHLY', max_length=30, verbose_name='ប្រភេទការប្រឡង / Exam Type')),
                ('start_date', models.DateField(verbose_name='ថ្ងៃចាប់ផ្តើម / Start Date')),
                ('end_date', models.DateField(verbose_name='ថ្ងៃបញ្ចប់ / End Date')),
                ('is_published', models.BooleanField(default=True, verbose_name='ប្រកាសលទ្ធផលជាសាធារណៈ / Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_terms', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
            ],
            options={
                'verbose_name': 'សម័យប្រឡង / Exam Term',
                'verbose_name_plural': 'សម័យប្រឡងទាំងអស់ / Exam Terms',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ពិន្ទុទទួលបាន / Score (0-100)')),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='ពិន្ទុពេញ / Max Score')),
                ('grade_letter', models.CharField(blank=True, max_length=5, null=True, verbose_name='និទ្ទេស / Letter Grade (A-F)')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='មតិយោបល់ / Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_grades', to='academics.classroom', verbose_name='ថ្នាក់រៀន / Classroom')),
                ('exam_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_grades', to='examinations.examterm', verbose_name='សម័យប្រឡង / Exam Term')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='សិស្ស / Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='academics.subject', verbose_name='មុខវិជ្ជា / Subject')),
            ],
            options={
                'verbose_name': 'ពិន្ទុ / Grade Entry',
                'verbose_name_plural': 'ពិន្ទុទាំងអស់ / Grade Entries',
                'ordering': ['classroom', 'student', 'subject'],
                'unique_together': {('student', 'subject', 'exam_term')},
            },
        ),
    ]
