# Generated by Django 6.1 on 2026-08-20 10:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6, verbose_name='ពិន្ទុពេញ / Max Score'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='ពិន្ទុទទួលបាន / Score'),
        ),
    ]
