# Generated by Django 6.1 on 2026-08-24 05:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_gradeenrollmentoption_col_width_and_more'),
        ('examinations', '0002_alter_grade_max_score_alter_grade_score'),
        ('students', '0005_scholarshiptype_student_enrollment_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardizedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ឈ្មោះសម័យប្រឡង / Exam Title')),
                ('grade_level', models.IntegerField(default=12, verbose_name='កម្រិតថ្នាក់ (7-12) / Grade Level')),
                ('track', models.CharField(choices=[('ALL', 'គ្រប់ជំនាញទាំងអស់ (All Tracks)'), ('GENERAL', 'កម្មវិធីទូទៅ (General Track)'), ('SCIENCE', 'ថ្នាក់វិទ្យាសាស្ត្រ (Science Track)'), ('SOCIAL', 'ថ្នាក់វិទ្យាសាស្ត្រសង្គម (Social Science Track)')], default='ALL', max_length=20, verbose_name='ជំនាញសិក្សា / Academic Track')),
                ('exam_date', models.DateField(verbose_name='កាលបរិច្ឆេទប្រឡង / Exam Date')),
                ('candidates_per_room', models.IntegerField(default=25, verbose_name='ចំនួនបេក្ខជនក្នុងមួយបន្ទប់ / Candidates Per Room')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នា/សេចក្តីណែនាំ / Description')),
                ('is_published', models.BooleanField(default=True, verbose_name='ប្រកាសលទ្ធផល / Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standardized_exams', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
            ],
            options={
                'verbose_name': 'ការប្រឡងតេស្តស្តង់ដា / Standardized Exam',
                'verbose_name_plural': 'ការប្រឡងតេស្តស្តង់ដាទាំងអស់ / Standardized Exams',
                'ordering': ['-exam_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=6, verbose_name='ពិន្ទុពេញ / Max Score')),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, verbose_name='មេគុណ / Weight / Coefficient')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='ថ្ងៃប្រឡង / Subject Exam Date')),
                ('session', models.CharField(choices=[('MORNING', 'ពេលព្រឹក (Morning Session)'), ('AFTERNOON', 'ពេលរសៀល (Afternoon Session)')], default='MORNING', max_length=20, verbose_name='ពេលប្រឡង / Session')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='ម៉ោងចាប់ផ្តើម / Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='ម៉ោងបញ្ចប់ / End Time')),
                ('order', models.IntegerField(default=1, verbose_name='លំដាប់មុខវិជ្ជា / Display Order')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standardized_exam_subjects', to='academics.subject', verbose_name='មុខវិជ្ជា / Subject')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='examinations.standardizedexam', verbose_name='សម័យប្រឡង / Exam')),
            ],
            options={
                'verbose_name': 'មុខវិជ្ជាប្រឡងតេស្ត / Exam Subject',
                'verbose_name_plural': 'មុខវិជ្ជាប្រឡងតេស្តទាំងអស់ / Exam Subjects',
                'ordering': ['order', 'id'],
                'unique_together': {('exam', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(default=1, verbose_name='បន្ទប់លេខ / Room Number (1, 2, 3...)')),
                ('room_name', models.CharField(max_length=100, verbose_name='ឈ្មោះបន្ទប់ / Room Display Name (e.g. បន្ទប់លេខ ០១)')),
                ('building', models.CharField(blank=True, max_length=100, null=True, verbose_name='អគារ / Building')),
                ('invigilator_1', models.CharField(blank=True, max_length=150, null=True, verbose_name='អនុរក្សទី១ / Chief Invigilator 1')),
                ('invigilator_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='អនុរក្សទី២ / Invigilator 2')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='examinations.standardizedexam', verbose_name='សម័យប្រឡង / Exam')),
            ],
            options={
                'verbose_name': 'បន្ទប់ប្រឡង / Exam Room',
                'verbose_name_plural': 'បន្ទប់ប្រឡងទាំងអស់ / Exam Rooms',
                'ordering': ['room_number', 'id'],
                'unique_together': {('exam', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='ExamCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=30, verbose_name='អត្តលេខបេក្ខជន / Candidate Roll No (e.g. 001)')),
                ('desk_number', models.IntegerField(default=1, verbose_name='លេខតុក្នុងបន្ទប់ / Desk No (1-25)')),
                ('candidate_name_kh', models.CharField(max_length=150, verbose_name='គោត្តនាម-នាម / Khmer Name')),
                ('candidate_name_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='ឈ្មោះឡាតាំង / Latin Name')),
                ('gender', models.CharField(choices=[('M', 'ប្រុស / Male'), ('F', 'ស្រី / Female')], default='M', max_length=5, verbose_name='ភេទ / Gender')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='ថ្ងៃខែឆ្នាំកំណើត / Date of Birth')),
                ('origin_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='ថ្នាក់ដើម / Origin Class (e.g. 12A1)')),
                ('student_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='អត្តលេខសិស្ស / Student ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='ពិន្ទុសរុប / Total Score')),
                ('average_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='មធ្យមភាគ / Weighted Average')),
                ('grade_letter', models.CharField(default='-', max_length=5, verbose_name='និទ្ទេស / Letter Grade (A-F)')),
                ('rank_in_room', models.IntegerField(blank=True, null=True, verbose_name='ចំណាត់ថ្នាក់ក្នុងបន្ទប់ / Room Rank')),
                ('rank_overall', models.IntegerField(blank=True, null=True, verbose_name='ចំណាត់ថ្នាក់ទូទាំងកម្រិត / Overall Rank')),
                ('is_present', models.BooleanField(default=True, verbose_name='មានវត្តមានប្រឡង / Present')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='ផ្សេងៗ / Remarks')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_exam_candidacies', to='students.student', verbose_name='សិស្សក្នុងប្រព័ន្ធ / Student')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='examinations.examroom', verbose_name='បន្ទប់ប្រឡង / Exam Room')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='examinations.standardizedexam', verbose_name='សម័យប្រឡង / Exam')),
            ],
            options={
                'verbose_name': 'បេក្ខជនប្រឡង / Exam Candidate',
                'verbose_name_plural': 'បេក្ខជនប្រឡងទាំងអស់ / Exam Candidates',
                'ordering': ['room__room_number', 'desk_number', 'roll_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CandidateSubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ពិន្ទុទទួលបាន / Score')),
                ('is_absent', models.BooleanField(default=False, verbose_name='អវត្តមាន / Absent')),
                ('signature_present', models.BooleanField(default=True, verbose_name='បានចុះហត្ថលេខា / Signed')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ចំណាំ / Notes')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_scores', to='examinations.examcandidate', verbose_name='បេក្ខជន / Candidate')),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_scores', to='examinations.examsubject', verbose_name='មុខវិជ្ជាប្រឡង / Exam Subject')),
            ],
            options={
                'verbose_name': 'ពិន្ទុមុខវិជ្ជាបេក្ខជន / Candidate Subject Score',
                'verbose_name_plural': 'ពិន្ទុមុខវិជ្ជាបេក្ខជនទាំងអស់ / Candidate Subject Scores',
                'ordering': ['exam_subject__order', 'id'],
                'unique_together': {('candidate', 'exam_subject')},
            },
        ),
    ]
