# Generated by Django 6.1 on 2026-08-24 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0003_standardizedexam_examsubject_examroom_examcandidate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examroom',
            name='secret_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='លេខកូដសម្ងាត់បន្ទប់ / Secret Room Code'),
        ),
        migrations.CreateModel(
            name='ExamRoomSubjectCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', models.CharField(max_length=50, unique=True, verbose_name='លេខកូដសម្ងាត់កញ្ចប់ / Secret Code')),
                ('is_graded', models.BooleanField(default=False, verbose_name='បានបញ្ចូលពិន្ទុរួច / Graded')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបញ្ចូល / Graded At')),
                ('exam_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_codes', to='examinations.examroom', verbose_name='បន្ទប់ប្រឡង / Exam Room')),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_codes', to='examinations.examsubject', verbose_name='មុខវិជ្ជាប្រឡង / Exam Subject')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='បញ្ចូលដោយ / Graded By')),
            ],
            options={
                'verbose_name': 'កូដសម្ងាត់កញ្ចប់វិញ្ញាសា / Envelope Secret Code',
                'verbose_name_plural': 'កូដសម្ងាត់កញ្ចប់វិញ្ញាសាទាំងអស់ / Envelope Secret Codes',
                'ordering': ['exam_room__room_number', 'exam_subject__order', 'id'],
                'unique_together': {('exam_room', 'exam_subject')},
            },
        ),
    ]
