# Generated by Django 6.1 on 2026-08-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0004_examroom_secret_code_examroomsubjectcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardizedexam',
            name='session',
            field=models.CharField(choices=[('MORNING', 'វេនពេលព្រឹក (Morning Session: 07:00 - 11:00)'), ('AFTERNOON', 'វេនពេលរសៀល (Afternoon Session: 13:00 - 17:00)'), ('FULL_DAY', 'ពេញមួយថ្ងៃ (Full Day / Both Sessions)')], default='MORNING', max_length=20, verbose_name='វេនប្រឡងចម្បង / Grade Exam Shift'),
        ),
    ]
