# Generated by Django 6.1 on 2026-08-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0005_standardizedexam_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='examterm',
            name='scoring_mode',
            field=models.CharField(choices=[('CLASSROOM', 'បញ្ចូលតាមថ្នាក់រៀន (Classroom-Based Matrix) - គ្រូប្រចាំមុខវិជ្ជា/បន្ទុកថ្នាក់'), ('STANDARDIZED_ROOM', 'បញ្ចូលតាមបន្ទប់ប្រឡង (Room-Based Matrix 1-25 នាក់) - គណៈកម្មការប្រឡង'), ('BOTH', 'អនុញ្ញាតទាំងពីរ (Both Classroom & Room Entry)')], default='CLASSROOM', max_length=30, verbose_name='របៀបបញ្ចូលពិន្ទុ / Scoring Mode'),
        ),
    ]
