# Generated by Django 6.1 on 2026-08-25 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_classroom_track_alter_subject_category'),
        ('examinations', '0006_examterm_scoring_mode'),
        ('students', '0005_scholarshiptype_student_enrollment_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examcandidate',
            name='disciplinary_blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទដាក់វិន័យ / Blocked At'),
        ),
        migrations.AddField(
            model_name='examcandidate',
            name='disciplinary_blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_blocked_candidates', to=settings.AUTH_USER_MODEL, verbose_name='ចាត់ចែងវិន័យដោយ / Blocked By'),
        ),
        migrations.AddField(
            model_name='examcandidate',
            name='disciplinary_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='មូលហេតុវិន័យ / Disciplinary Reason'),
        ),
        migrations.AddField(
            model_name='examcandidate',
            name='is_disciplinary_blocked',
            field=models.BooleanField(default=False, verbose_name='ជាប់កិច្ចសន្យាវិន័យ / Disciplinary Hold'),
        ),
        migrations.CreateModel(
            name='ExamStudentExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ខែ ១ - មករា (January)'), (2, 'ខែ ២ - កុម្ភៈ (February)'), (3, 'ខែ ៣ - មីនា (March)'), (4, 'ខែ ៤ - មេសា (April)'), (5, 'ខែ ៥ - ឧសភា (May)'), (6, 'ខែ ៦ - មិថុនា (June)'), (7, 'ខែ ៧ - កក្កដា (July)'), (8, 'ខែ ៨ - សីហា (August)'), (9, 'ខែ ៩ - កញ្ញា (September)'), (10, 'ខែ ១០ - តុលា (October)'), (11, 'ខែ ១១ - វិច្ឆិកា (November)'), (12, 'ខែ ១២ - ធ្នូ (December)')], null=True, verbose_name='ខែប្រឡង / Exam Month')),
                ('reason', models.CharField(choices=[('DROPPED', 'ឈប់រៀន / Dropped Out'), ('SUSPENDED', 'ផ្អាកការសិក្សា / Suspended'), ('DISCIPLINARY', 'បញ្ហាវិន័យ / ជាប់កិច្ចសន្យា / Disciplinary'), ('HEALTH', 'បញ្ហាសុខភាព / សម្រាកព្យាបាល / Health Issue'), ('UNEXCUSED_ABSENCE', 'អវត្តមានឥតច្បាប់ / Unexcused Absence'), ('FEE_OVERDUE', 'ជំពាក់ប្រាក់កម្រៃ / Fee Overdue'), ('OTHER', 'ផ្សេងៗ / Other')], default='DROPPED', max_length=30, verbose_name='មូលហេតុលើកលែង / Exclusion Reason')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='កំណត់សម្គាល់បន្ថែម / Reason Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='សកម្ម (កំពុងលើកលែង) / Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_exclusions', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('exam_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_exclusions', to='examinations.examterm', verbose_name='សម័យប្រឡងប្រចាំខែ/ឆមាស / Exam Term')),
                ('excluded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_exclusions_given', to=settings.AUTH_USER_MODEL, verbose_name='កំណត់ដោយ / Excluded By')),
                ('standardized_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_exclusions', to='examinations.standardizedexam', verbose_name='សម័យប្រឡងតេស្តស្តង់ដា / Standardized Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_exclusions', to='students.student', verbose_name='សិស្ស / Student')),
            ],
            options={
                'verbose_name': 'ការលើកលែងសិស្សមិនឱ្យប្រឡង / Student Exam Exclusion',
                'verbose_name_plural': 'ការលើកលែងសិស្សមិនឱ្យប្រឡងទាំងអស់ / Student Exam Exclusions',
                'ordering': ['-created_at', 'student__khmer_name'],
            },
        ),
    ]
