# Generated by Django 6.1 on 2026-08-25 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_classroom_track_alter_subject_category'),
        ('examinations', '0007_examcandidate_disciplinary_blocked_at_and_more'),
        ('students', '0006_student_exam_suspension_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examterm',
            name='is_counted_in_semester',
            field=models.BooleanField(default=True, help_text='កំណត់ថាតើសម័យប្រឡងនេះ ត្រូវរាប់បញ្ចូលក្នុងការគណនាមធ្យមភាគឆមាសដែរឬទេ', verbose_name='រាប់ក្នុងមធ្យមភាគឆមាស / Count in Semester Average'),
        ),
        migrations.AddField(
            model_name='examterm',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ឆមាសទី១ / Semester 1'), (2, 'ឆមាសទី២ / Semester 2')], default=1, verbose_name='ឆមាស / Semester'),
        ),
        migrations.CreateModel(
            name='StudentTransferGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'ឆមាសទី១ (Semester 1)'), (2, 'ឆមាសទី២ (Semester 2)')], default=1, verbose_name='ឆមាស / Semester')),
                ('prior_school_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ឈ្មោះសាលាចាស់ / Prior School Name')),
                ('monthly_average', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='មធ្យមភាគប្រចាំខែពីសាលាចាស់ / Prior Monthly Average')),
                ('semester_exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ពិន្ទុប្រឡងឆមាសពីសាលាចាស់ / Prior Semester Exam Score')),
                ('semester_final_average', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='មធ្យមភាគប្រចាំឆមាសពីសាលាចាស់ / Prior Semester Final Average')),
                ('letter_grade', models.CharField(blank=True, max_length=5, null=True, verbose_name='និទ្ទេស / Letter Grade (A-F)')),
                ('subject_scores', models.JSONField(blank=True, default=dict, verbose_name='ពិន្ទុតកមុខវិជ្ជា / Subject Breakdown')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='កំណត់សម្គាល់ / Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_grades', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='បញ្ចូលដោយ / Created By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_grades', to='students.student', verbose_name='សិស្ស / Student')),
            ],
            options={
                'verbose_name': 'ពិន្ទុសិស្សផ្ទេរចូល / Transfer-in Grade',
                'verbose_name_plural': 'ពិន្ទុសិស្សផ្ទេរចូលទាំងអស់ / Transfer-in Grades',
                'ordering': ['student', 'academic_year', 'semester'],
                'unique_together': {('student', 'academic_year', 'semester')},
            },
        ),
    ]
