# Generated by Django 6.1 on 2026-08-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0008_examterm_is_counted_in_semester_examterm_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examterm',
            name='grading_end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទ & ម៉ោងបញ្ចប់បញ្ចូលពិន្ទុ / Grading Deadline'),
        ),
        migrations.AddField(
            model_name='examterm',
            name='grading_start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទ & ម៉ោងចាប់ផ្តើមបញ្ចូលពិន្ទុ / Grading Start Time'),
        ),
        migrations.AddField(
            model_name='examterm',
            name='is_grading_locked',
            field=models.BooleanField(default=False, verbose_name='ចាក់សោការបញ្ចូលពិន្ទុ / Lock Grade Entry'),
        ),
        migrations.AddField(
            model_name='standardizedexam',
            name='grading_end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទ & ម៉ោងបញ្ចប់បញ្ចូលពិន្ទុ / Grading Deadline'),
        ),
        migrations.AddField(
            model_name='standardizedexam',
            name='grading_start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទ & ម៉ោងចាប់ផ្តើមបញ្ចូលពិន្ទុ / Grading Start Time'),
        ),
        migrations.AddField(
            model_name='standardizedexam',
            name='is_grading_locked',
            field=models.BooleanField(default=False, verbose_name='ចាក់សោការបញ្ចូលពិន្ទុ / Lock Grade Entry'),
        ),
    ]
