# Generated by Django 6.1 on 2026-08-31 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0009_examterm_grading_end_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesubjectscore',
            name='entered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទ & ម៉ោងបញ្ចូល / Entered At'),
        ),
        migrations.AddField(
            model_name='candidatesubjectscore',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_candidate_scores', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកបញ្ចូលពិន្ទុ / Entered By'),
        ),
        migrations.AddField(
            model_name='candidatesubjectscore',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_candidate_scores', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកកែប្រែចុងក្រោយ / Last Modified By'),
        ),
        migrations.AddField(
            model_name='candidatesubjectscore',
            name='secret_code_used',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='អក្សរសម្ងាត់ដែលបានប្រើ / Secret Code Used'),
        ),
        migrations.AddField(
            model_name='candidatesubjectscore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
