# Generated by Django 6.1 on 2026-09-03 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_alter_classroom_code_alter_classroom_name'),
        ('examinations', '0010_candidatesubjectscore_entered_at_and_more'),
        ('teachers', '0014_teacher_phone2_alter_teacher_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamInvigilatorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ចំណងជើងគម្រោង / Plan Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='សេចក្តីណែនាំ / Description & Guidelines')),
                ('start_date', models.DateField(verbose_name='ថ្ងៃចាប់ផ្តើមប្រឡង / Exam Start Date')),
                ('end_date', models.DateField(verbose_name='ថ្ងៃបញ្ចប់ការប្រឡង / Exam End Date')),
                ('is_active', models.BooleanField(default=False, help_text='បើក/បិទ ដំណើរការការស្នើសុំ។ លុះត្រាតែបើកទើបគ្រូអាចមើលឃើញ និងស្នើសុំបាន', verbose_name='បើកដំណើរការ (Active) / Is Active')),
                ('allow_teacher_registration', models.BooleanField(default=True, verbose_name='អនុញ្ញាតឱ្យគ្រូចុះឈ្មោះ / Allow Teacher Registration')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='ថ្ងៃផុតកំណត់ចុះឈ្មោះ / Registration Deadline')),
                ('default_regular_quota', models.PositiveIntegerField(default=4, verbose_name='កូតាលំនាំដើមគ្រូធម្មតា / Regular Teacher Default Quota (4 វេន)')),
                ('default_office_quota', models.PositiveIntegerField(default=5, verbose_name='កូតាលំនាំដើមគ្រូការិយាល័យ / Office Teacher Default Quota (5 វេន)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_plans', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
            ],
            options={
                'verbose_name': 'គម្រោងវេនអនុរក្សប្រឡង / Exam Invigilator Plan',
                'verbose_name_plural': 'គម្រោងវេនអនុរក្សប្រឡងទាំងអស់ / Exam Invigilator Plans',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamShiftSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='កាលបរិច្ឆេទ / Date')),
                ('session', models.CharField(choices=[('MORNING', '🌅 ពេលព្រឹក (Morning 07:00 - 11:00)'), ('AFTERNOON', '⛅ ពេលរសៀល (Afternoon 13:00 - 17:00)'), ('CUSTOM', '🕒 ម៉ោងជាក់លាក់ (Custom Time)')], default='MORNING', max_length=20, verbose_name='វេន / Session')),
                ('session_name', models.CharField(max_length=150, verbose_name='ឈ្មោះវេន / Slot Name')),
                ('start_time', models.TimeField(default='07:00', verbose_name='ម៉ោងចាប់ផ្តើម / Start Time')),
                ('end_time', models.TimeField(default='11:00', verbose_name='ម៉ោងបញ្ចប់ / End Time')),
                ('max_invigilators', models.PositiveIntegerField(default=20, verbose_name='ចំនួនអនុរក្សអតិបរមា / Max Invigilators')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='កំណត់ចំណាំ / Notes')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='លំដាប់ / Order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_slots', to='examinations.examinvigilatorplan', verbose_name='គម្រោង / Plan')),
            ],
            options={
                'verbose_name': 'វេនប្រឡង / Exam Shift Slot',
                'verbose_name_plural': 'វេនប្រឡងទាំងអស់ / Exam Shift Slots',
                'ordering': ['date', 'start_time', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TeacherDutyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ឈ្មោះក្រុម / Group Name')),
                ('required_shifts', models.PositiveIntegerField(default=4, verbose_name='ចំនួនវេនតម្រូវ / Required Shifts')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='ការពិពណ៌នា / Description')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='លំដាប់ / Order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_groups', to='examinations.examinvigilatorplan', verbose_name='គម្រោង / Plan')),
            ],
            options={
                'verbose_name': 'ក្រុមគ្រូ & កូតាវេន / Teacher Duty Group',
                'verbose_name_plural': 'ក្រុមគ្រូ & កូតាវេន / Teacher Duty Groups',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherDutyQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_required_shifts', models.PositiveIntegerField(blank=True, null=True, verbose_name='កូតាជាក់លាក់ (Override) / Custom Shifts')),
                ('is_exempt', models.BooleanField(default=False, verbose_name='លើកលែងមិនបាច់ធ្វើអនុរក្ស / Exempt')),
                ('exemption_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='មូលហេតុលើកលែង / Exemption Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duty_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotas', to='examinations.teacherdutygroup', verbose_name='ក្រុមគ្រូ / Duty Group')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_quotas', to='examinations.examinvigilatorplan', verbose_name='គម្រោង / Plan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_duty_quotas', to='teachers.teacher', verbose_name='គ្រូបង្រៀន / Teacher')),
            ],
            options={
                'verbose_name': 'កូតាវេនគ្រូបង្រៀន / Teacher Shift Quota',
                'verbose_name_plural': 'កូតាវេនគ្រូបង្រៀនទាំងអស់ / Teacher Shift Quotas',
                'ordering': ['teacher__khmer_name'],
                'unique_together': {('plan', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='TeacherShiftRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'បានបញ្ជាក់ / Confirmed'), ('ADMIN_ASSIGNED', 'ចាត់តាំងដោយ Admin / Admin Assigned'), ('PENDING', 'រង់ចាំការអនុម័ត / Pending'), ('CANCELLED', 'បានបោះបង់ / Cancelled')], default='CONFIRMED', max_length=30, verbose_name='ស្ថានភាព / Status')),
                ('room_assignment', models.CharField(blank=True, max_length=100, null=True, verbose_name='បន្ទប់ដែលត្រូវឈរ / Room Assignment')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='កំណត់ចំណាំ / Notes')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='examinations.examshiftslot', verbose_name='វេនប្រឡង / Shift Slot')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_shift_registrations', to='teachers.teacher', verbose_name='គ្រូបង្រៀន / Teacher')),
            ],
            options={
                'verbose_name': 'ការចុះឈ្មោះវេនអនុរក្ស / Teacher Shift Registration',
                'verbose_name_plural': 'ការចុះឈ្មោះវេនអនុរក្សទាំងអស់ / Teacher Shift Registrations',
                'ordering': ['slot__date', 'slot__start_time', 'teacher__khmer_name'],
                'unique_together': {('slot', 'teacher')},
            },
        ),
    ]
