# Generated by Django 6.1 on 2026-09-03 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0011_examinvigilatorplan_examshiftslot_teacherdutygroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinvigilatorplan',
            name='session_key',
            field=models.CharField(blank=True, help_text='កូដសម្គាល់សម័យប្រឡងពហុកម្រិតថ្នាក់', max_length=255, null=True, verbose_name='កូដសម័យប្រឡង / Session Key'),
        ),
        migrations.AddField(
            model_name='examinvigilatorplan',
            name='standardized_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilator_plans', to='examinations.standardizedexam', verbose_name='សម័យប្រឡងតេស្តស្តង់ដា / Standardized Exam'),
        ),
    ]
