# Generated by Django 6.1 on 2026-09-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0012_examinvigilatorplan_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardizedexam',
            name='grading_method',
            field=models.CharField(choices=[('BOTH', 'អនុញ្ញាតទាំងពីរ (គ្រូបង្រៀនផ្ទាល់ ឬ លេខកូដសម្ងាត់)'), ('TEACHER_DIRECT', 'តាមរយៈគ្រូបង្រៀនផ្ទាល់ (Direct Teacher Entry)'), ('BLIND_SECRET_CODE', 'តាមរយៈលេខកូដសម្ងាត់តែប៉ុណ្ណោះ (Secret Code Only)')], default='BOTH', max_length=30, verbose_name='របៀបបញ្ចូលពិន្ទុអនុញ្ញាត / Allowed Grading Method'),
        ),
    ]
