# Generated by Django 6.1 on 2026-09-03 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0013_standardizedexam_grading_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardizedexam',
            name='exam_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standardized_exams', to='examinations.examterm', verbose_name='សម័យប្រឡងប្រចាំខែ/ឆមាស / Linked Exam Term'),
        ),
        migrations.AddField(
            model_name='standardizedexam',
            name='exam_type',
            field=models.CharField(choices=[('MONTHLY', 'ការប្រឡងប្រចាំខែ (Monthly Exam)'), ('SEMESTER_1', 'ការប្រឡងឆមាសទី១ (Semester 1 Exam)'), ('SEMESTER_2', 'ការប្រឡងឆមាសទី២ (Semester 2 Exam)'), ('BASELINE', 'ការប្រឡងតេស្តដើមឆ្នាំ (Baseline Test)'), ('MOCK', 'ការប្រឡងសាកល្បង / បាក់ឌុបសាកល្បង (Mock Exam)'), ('ENDLINE', 'ការប្រឡងតេស្តចុងឆ្នាំ (Endline Test)'), ('OTHER', 'ការប្រឡងផ្សេងៗ (Other Admin Exam)')], default='OTHER', max_length=30, verbose_name='ប្រភេទសម័យប្រឡង / Exam Type'),
        ),
    ]
