# Generated by Django 6.1 on 2026-09-03 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0014_standardizedexam_exam_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdutyquota',
            name='assigned_role',
            field=models.CharField(choices=[('PRESIDENT', 'ប្រធាន (President / Chief)'), ('VICE_PRESIDENT', 'អនុប្រធាន (Vice President)'), ('INVIGILATOR', 'គណៈកម្មការអនុរក្ស (អនុរក្ស)'), ('SECRETARIAT', 'គណៈកម្មការកណ្តាល (កណ្តាល)'), ('BUILDING_INSPECTOR', 'គណៈកម្មការត្រួតអគារ (ត្រួតអគារ)'), ('TABULATOR', 'គណៈកម្មការបូកស្រង់ពិន្ទុ (បូកស្រង់)')], default='INVIGILATOR', max_length=30, verbose_name='មុខងារគណៈកម្មការ / Committee Role'),
        ),
        migrations.AddField(
            model_name='teacherdutyquota',
            name='auto_assign_all_shifts',
            field=models.BooleanField(default=False, verbose_name='ចាត់តាំងគ្រប់វេនស្វ័យប្រវត្តិ / Auto-Assign to All Shifts'),
        ),
        migrations.AddField(
            model_name='teachershiftregistration',
            name='role',
            field=models.CharField(choices=[('PRESIDENT', 'ប្រធាន (President / Chief)'), ('VICE_PRESIDENT', 'អនុប្រធាន (Vice President)'), ('INVIGILATOR', 'គណៈកម្មការអនុរក្ស (អនុរក្ស)'), ('SECRETARIAT', 'គណៈកម្មការកណ្តាល (កណ្តាល)'), ('BUILDING_INSPECTOR', 'គណៈកម្មការត្រួតអគារ (ត្រួតអគារ)'), ('TABULATOR', 'គណៈកម្មការបូកស្រង់ពិន្ទុ (បូកស្រង់)')], default='INVIGILATOR', max_length=30, verbose_name='មុខងារក្នុងវេន / Duty Role'),
        ),
        migrations.CreateModel(
            name='ExamPlanRoleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRESIDENT', 'ប្រធាន (President / Chief)'), ('VICE_PRESIDENT', 'អនុប្រធាន (Vice President)'), ('INVIGILATOR', 'គណៈកម្មការអនុរក្ស (អនុរក្ស)'), ('SECRETARIAT', 'គណៈកម្មការកណ្តាល (កណ្តាល)'), ('BUILDING_INSPECTOR', 'គណៈកម្មការត្រួតអគារ (ត្រួតអគារ)'), ('TABULATOR', 'គណៈកម្មការបូកស្រង់ពិន្ទុ (បូកស្រង់)')], max_length=30, verbose_name='មុខងារគណៈកម្មការ / Role')),
                ('is_requestable', models.BooleanField(default=True, help_text='ប្រសិនបើបិទ មានន័យថាមុខងារនេះចាត់តាំងដោយ Admin រួចជាស្រេច (គ្រូមិនអាចស្នើសុំបានទេ)', verbose_name='អនុញ្ញាតឱ្យគ្រូស្នើសុំវេន / Allow Teacher Request')),
                ('capacity_per_shift', models.PositiveIntegerField(default=1, verbose_name='ចំនួនតម្រូវការក្នុង១វេន / Capacity per Shift')),
                ('auto_assign_all_shifts', models.BooleanField(default=False, help_text='សម្រាប់ប្រធាន ឬអនុប្រធានដែលត្រូវមកគ្រប់ពេលដោយមិនបាច់សុំ', verbose_name='ចាត់តាំងគ្រប់វេនស្វ័យប្រវត្តិ / Auto-Assign to All Shifts')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='កំណត់ចំណាំ / Notes')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_settings', to='examinations.examinvigilatorplan', verbose_name='គម្រោង / Plan')),
            ],
            options={
                'verbose_name': 'ការកំណត់មុខងារគណៈកម្មការ / Exam Plan Role Setting',
                'verbose_name_plural': 'ការកំណត់មុខងារគណៈកម្មការទាំងអស់ / Exam Plan Role Settings',
                'ordering': ['role'],
                'unique_together': {('plan', 'role')},
            },
        ),
    ]
