# Generated by Django 6.1 on 2026-09-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0015_teacherdutyquota_assigned_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardizedExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ឈ្មោះប្រភេទសម័យប្រឡង / Exam Type Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='កូដសម្គាល់ / Code Identifier')),
                ('icon', models.CharField(default='🎯', max_length=50, verbose_name='រូបតំណាង ឬ Emoji / Icon or Emoji')),
                ('default_title', models.CharField(blank=True, max_length=200, verbose_name='ទម្រង់ឈ្មោះលំនាំដើម / Default Title Template')),
                ('is_monthly', models.BooleanField(default=False, verbose_name='ជាការប្រឡងប្រចាំខែ / Is Monthly Exam')),
                ('linked_term_type', models.CharField(blank=True, default='', max_length=30, verbose_name='ភ្ជាប់ទៅសម័យប្រឡងផ្លូវការ / Linked Term Type')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='លំដាប់លំដោយ / Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='សកម្ម / Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ប្រភេទសម័យប្រឡងតេស្តស្តង់ដា / Standardized Exam Type',
                'verbose_name_plural': 'ប្រភេទសម័យប្រឡងតេស្តស្តង់ដាទាំងអស់ / Standardized Exam Types',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='standardizedexam',
            name='exam_type',
            field=models.CharField(default='OTHER', max_length=50, verbose_name='ប្រភេទសម័យប្រឡង / Exam Type'),
        ),
    ]
