# Generated by Django 6.1 on 2026-09-04 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_alter_classroom_code_alter_classroom_name'),
        ('examinations', '0016_standardizedexamtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTermSubjectSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ខែ ១ - មករា (January)'), (2, 'ខែ ២ - កុម្ភៈ (February)'), (3, 'ខែ ៣ - មីនា (March)'), (4, 'ខែ ៤ - មេសា (April)'), (5, 'ខែ ៥ - ឧសភា (May)'), (6, 'ខែ ៦ - មិថុនា (June)'), (7, 'ខែ ៧ - កក្កដា (July)'), (8, 'ខែ ៨ - សីហា (August)'), (9, 'ខែ ៩ - កញ្ញា (September)'), (10, 'ខែ ១០ - តុលា (October)'), (11, 'ខែ ១១ - វិច្ឆិកា (November)'), (12, 'ខែ ១២ - ធ្នូ (December)')], null=True, verbose_name='ខែប្រឡង / Exam Month (1-12)')),
                ('grade_level', models.IntegerField(blank=True, null=True, verbose_name='កម្រិតថ្នាក់ (7-12) / Grade Level')),
                ('track', models.CharField(blank=True, max_length=50, null=True, verbose_name='ជំនាញសិក្សា / Track')),
                ('is_tested', models.BooleanField(default=True, verbose_name='ប្រឡង / Is Tested (True=ប្រឡង, False=មិនប្រឡង)')),
                ('custom_max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ពិន្ទុពេញផ្ទាល់ខ្លួន / Custom Max Score')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='កំណត់សម្គាល់ / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_subject_settings', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_subject_settings', to='academics.classroom', verbose_name='ថ្នាក់រៀនជាក់លាក់ / Specific Classroom')),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_subject_settings_given', to=settings.AUTH_USER_MODEL, verbose_name='កំណត់ដោយ / Configured By')),
                ('exam_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_settings', to='examinations.examterm', verbose_name='សម័យប្រឡងប្រចាំខែ/ឆមាស / Exam Term')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_subject_settings', to='academics.subject', verbose_name='មុខវិជ្ជា / Subject')),
            ],
            options={
                'verbose_name': 'ការកំណត់មុខវិជ្ជាប្រឡង/មិនប្រឡង / Exam Term Subject Setting',
                'verbose_name_plural': 'ការកំណត់មុខវិជ្ជាប្រឡង/មិនប្រឡងទាំងអស់ / Exam Term Subject Settings',
                'ordering': ['grade_level', 'classroom', 'subject__order', 'id'],
            },
        ),
    ]
