# Generated by Django 6.1 on 2026-09-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0017_examtermsubjectsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinvigilatorplan',
            name='invigilators_per_room',
            field=models.PositiveSmallIntegerField(choices=[(1, '១ នាក់/បន្ទប់'), (2, '២ នាក់/បន្ទប់')], default=2, verbose_name='ចំនួនអនុរក្សក្នុង១បន្ទប់ / Invigilators per Room'),
        ),
        migrations.AddField(
            model_name='examinvigilatorplan',
            name='rooms_count',
            field=models.PositiveIntegerField(default=0, verbose_name='ចំនួនបន្ទប់សរុប / Total Rooms'),
        ),
    ]
