# Generated by Django 6.1 on 2026-09-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0018_examinvigilatorplan_invigilators_per_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdutyquota',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបញ្ចប់ / Finalized At'),
        ),
        migrations.AddField(
            model_name='teacherdutyquota',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='បានបញ្ចប់ការស្នើសុំ / Finalized'),
        ),
    ]
