# Generated by Django 6.1 on 2026-09-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0019_teacherdutyquota_finalized_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examterm',
            name='is_provisional_published',
            field=models.BooleanField(default=False, help_text='បើកដំណើរការឱ្យគ្រូ សិស្ស និងអាណាព្យាបាលអាចមើលឃើញពិន្ទុ និងមធ្យមភាគបណ្តោះអាសន្ន', verbose_name='ចេញលទ្ធផលបណ្តោះអាសន្ន / Provisional Results Published'),
        ),
        migrations.AddField(
            model_name='examterm',
            name='provisional_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទចេញលទ្ធផលបណ្តោះអាសន្ន / Provisional Published At'),
        ),
        migrations.AddField(
            model_name='standardizedexam',
            name='is_provisional_published',
            field=models.BooleanField(default=False, help_text='បើកដំណើរការឱ្យគ្រូ សិស្ស និងអាណាព្យាបាលអាចមើលឃើញពិន្ទុ និងមធ្យមភាគបណ្តោះអាសន្ន', verbose_name='ចេញលទ្ធផលបណ្តោះអាសន្ន / Provisional Results Published'),
        ),
        migrations.AddField(
            model_name='standardizedexam',
            name='provisional_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទចេញលទ្ធផលបណ្តោះអាសន្ន / Provisional Published At'),
        ),
    ]
