# Generated by Django 6.1 on 2026-09-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0020_examterm_is_provisional_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinvigilatorplan',
            name='is_unified_quota',
            field=models.BooleanField(default=False, help_text='បើកជម្រើសនេះដើម្បីឱ្យគ្រូគ្រប់ប្រភេទទាំងអស់ជ្រើសរើសវេនស្មើគ្នាដូចគ្នាទាំងអស់', verbose_name='កំណត់កូតារួមសម្រាប់គ្រូគ្រប់ប្រភេទ / Unified Quota for All Teacher Types'),
        ),
        migrations.AddField(
            model_name='examinvigilatorplan',
            name='unified_quota',
            field=models.PositiveIntegerField(default=4, verbose_name='កូតាចំនួនវេនរួម / Unified Quota Value'),
        ),
    ]
