# Generated by Django 6.1 on 2026-09-08 02:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_clean_classroom_codes'),
        ('examinations', '0021_examinvigilatorplan_is_unified_quota_and_more'),
        ('students', '0011_student_photo_drive_url'),
        ('teachers', '0014_teacher_phone2_alter_teacher_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ចំណងជើងវិញ្ញាសា / Exam Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='សេចក្តីណែនាំ / Instructions')),
                ('grade_level', models.IntegerField(blank=True, help_text='កំណត់កម្រិតថ្នាក់ (ឧ. 7, 8, 9, 10, 11, 12) ឬទុកទទេ', null=True, verbose_name='កម្រិតថ្នាក់ / Grade Level')),
                ('duration_minutes', models.PositiveIntegerField(default=45, verbose_name='រយៈពេលប្រឡង (នាទី) / Duration (Mins)')),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6, verbose_name='ពិន្ទុពេញ / Max Score')),
                ('pass_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=6, verbose_name='ពិន្ទុជាប់ / Pass Score')),
                ('max_attempts', models.PositiveIntegerField(default=1, verbose_name='ចំនួនដងអនុញ្ញាត / Max Attempts')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='ម៉ោងចាប់ផ្តើមប្រឡង / Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='ម៉ោងបញ្ចប់ប្រឡង / End Time')),
                ('status', models.CharField(choices=[('DRAFT', 'ព្រាង / Draft'), ('PUBLISHED', 'ផ្សព្វផ្សាយ / Published'), ('CLOSED', 'បិទបញ្ចប់ / Closed')], default='DRAFT', max_length=20, verbose_name='ស្ថានភាព / Status')),
                ('is_published', models.BooleanField(default=False, verbose_name='ផ្សព្វផ្សាយ / Published')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='ច្របល់លំដាប់សំណួរ / Shuffle Questions')),
                ('shuffle_options', models.BooleanField(default=True, verbose_name='ច្របល់លំដាប់ជម្រើស / Shuffle Options')),
                ('show_result_immediately', models.BooleanField(default=True, verbose_name='បង្ហាញលទ្ធផលភ្លាមៗ / Show Result Immediately')),
                ('show_correct_answers', models.BooleanField(default=True, verbose_name='បង្ហាញចម្លើយត្រូវពេល Review / Show Correct Answers')),
                ('access_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='លេខកូដសម្ងាត់ / Access Code (PIN)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='បង្កើតដោយ / Created By')),
                ('exam_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='examinations.examterm', verbose_name='សម័យប្រឡង / Exam Term')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='academics.subject', verbose_name='មុខវិជ្ជា / Subject')),
                ('target_classrooms', models.ManyToManyField(blank=True, related_name='online_exams', to='academics.classroom', verbose_name='ថ្នាក់រៀនគោលដៅ / Target Classrooms')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_exams', to='teachers.teacher', verbose_name='គ្រូទទួលបន្ទុក / Teacher')),
            ],
            options={
                'verbose_name': 'វិញ្ញាសាប្រឡងអនឡាញ / Online Exam',
                'verbose_name_plural': 'វិញ្ញាសាប្រឡងអនឡាញទាំងអស់ / Online Exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='ខ្លឹមសារសំណួរ / Question Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='online_exams/questions/', verbose_name='រូបភាពភ្ជាប់ / Question Image')),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='ពិន្ទុ / Points')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='លំដាប់ / Order')),
                ('explanation', models.TextField(blank=True, help_text='ការពន្យល់ដែលត្រូវបង្ហាញឱ្យសិស្សមើលពេល Review លទ្ធផល', null=True, verbose_name='ការពន្យល់ចម្លើយ / Explanation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examinations.onlineexam', verbose_name='វិញ្ញាសា / Exam')),
            ],
            options={
                'verbose_name': 'សំណួរប្រឡង / Exam Question',
                'verbose_name_plural': 'សំណួរប្រឡងទាំងអស់ / Exam Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OnlineExamOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500, verbose_name='ខ្លឹមសារជម្រើស / Option Text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='ចម្លើយត្រឹមត្រូវ / Is Correct')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='លំដាប់ / Order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='examinations.onlineexamquestion', verbose_name='សំណួរ / Question')),
            ],
            options={
                'verbose_name': 'ជម្រើសចម្លើយ / Option',
                'verbose_name_plural': 'ជម្រើសចម្លើយទាំងអស់ / Options',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OnlineExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='លើកទី / Attempt #')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='ចាប់ផ្តើមនៅ / Started At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='ប្រគល់នៅ / Submitted At')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='រយៈពេលចំណាយ (វិនាទី) / Time Spent (s)')),
                ('score_obtained', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='ពិន្ទុទទួលបាន / Score Obtained')),
                ('total_possible_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='ពិន្ទុពេញ / Total Possible')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='ភាគរយ / Percentage')),
                ('letter_grade', models.CharField(blank=True, max_length=5, null=True, verbose_name='និទ្ទេស / Letter Grade')),
                ('is_passed', models.BooleanField(default=False, verbose_name='ជាប់/ធ្លាក់ / Is Passed')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'កំពុងប្រឡង / In Progress'), ('SUBMITTED', 'បានប្រគល់ / Submitted'), ('EXPIRED', 'ផុតម៉ោង / Time Expired')], default='IN_PROGRESS', max_length=20, verbose_name='ស្ថានភាព / Status')),
                ('synced_to_grade', models.BooleanField(default=False, verbose_name='បាន Sync ទៅតារាងពិន្ទុ / Synced to Grade Matrix')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classroom', verbose_name='ថ្នាក់រៀន / Classroom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='examinations.onlineexam', verbose_name='វិញ្ញាសា / Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exam_submissions', to='students.student', verbose_name='សិស្ស / Student')),
            ],
            options={
                'verbose_name': 'លទ្ធផលប្រឡងអនឡាញ / Exam Submission',
                'verbose_name_plural': 'លទ្ធផលប្រឡងអនឡាញទាំងអស់ / Exam Submissions',
                'ordering': ['-submitted_at', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='ត្រឹមត្រូវ / Correct')),
                ('points_awarded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='ពិន្ទុដែលទទួលបាន / Points Awarded')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examinations.onlineexamoption', verbose_name='ជម្រើសដែលបានរើស / Selected Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examinations.onlineexamquestion', verbose_name='សំណួរ / Question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='examinations.onlineexamsubmission', verbose_name='ការប្រឡង / Submission')),
            ],
            options={
                'verbose_name': 'ចម្លើយរបស់សិស្ស / Student Answer',
                'verbose_name_plural': 'ចម្លើយរបស់សិស្សទាំងអស់ / Student Answers',
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
