# Generated by Django 6.1 on 2026-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0022_onlineexam_onlineexamquestion_onlineexamoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='រយៈពេល (គិតជានាទី) / Duration in Minutes'),
        ),
    ]
