# Generated by Django 6.1 on 2026-09-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0023_examsubject_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='examterm',
            name='is_active_for_grading',
            field=models.BooleanField(default=False, help_text='បើកដំណើរការសម័យប្រឡងនេះ ឱ្យគ្រូបង្រៀនអាចបញ្ចូលពិន្ទុបាន (លើ Portal និង Mobile App)', verbose_name='បើកដំណើរការបញ្ចូលពិន្ទុសម្រាប់គ្រូ (Active Grading Term)'),
        ),
    ]
