# Generated by Django 6.1 on 2026-09-18 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0030_gradelevel_is_registration_open_and_more'),
        ('examinations', '0024_examterm_is_active_for_grading'),
        ('students', '0013_student_previous_school'),
        ('teachers', '0015_teacher_subject_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentConductAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_s1', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អ', max_length=20, verbose_name='ការគោរពវិន័យ (ឆ.១)')),
                ('diligence_s1', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អ', max_length=20, verbose_name='ការខិតខំប្រឹងប្រែង (ឆ.១)')),
                ('moral_s1', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អណាស់', max_length=20, verbose_name='សីលធម៌ សុជីវធម៌ (ឆ.១)')),
                ('hygiene_s1', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អ', max_length=20, verbose_name='អនាម័យ និងបរិស្ថាន (ឆ.១)')),
                ('social_s1', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អ', max_length=20, verbose_name='សកម្មភាពសង្គម/ពលកម្ម (ឆ.១)')),
                ('overall_s1', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អ', max_length=20, verbose_name='មារយាទរួម (ឆ.១)')),
                ('teacher_comment_s1', models.TextField(blank=True, default='', verbose_name='មតិគ្រូបន្ទុកថ្នាក់ (ឆ.១)')),
                ('parent_comment_s1', models.TextField(blank=True, default='', verbose_name='មតិមាតាបិតា (ឆ.១)')),
                ('discipline_s2', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អ', max_length=20, verbose_name='ការគោរពវិន័យ (ឆ.២)')),
                ('diligence_s2', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អ', max_length=20, verbose_name='ការខិតខំប្រឹងប្រែង (ឆ.២)')),
                ('moral_s2', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អណាស់', max_length=20, verbose_name='សីលធម៌ សុជីវធម៌ (ឆ.២)')),
                ('hygiene_s2', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អ', max_length=20, verbose_name='អនាម័យ និងបរិស្ថាន (ឆ.២)')),
                ('social_s2', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អ', max_length=20, verbose_name='សកម្មភាពសង្គម/ពលកម្ម (ឆ.២)')),
                ('overall_s2', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អ', max_length=20, verbose_name='មារយាទរួម (ឆ.២)')),
                ('teacher_comment_s2', models.TextField(blank=True, default='', verbose_name='មតិគ្រូបន្ទុកថ្នាក់ (ឆ.២)')),
                ('parent_comment_s2', models.TextField(blank=True, default='', verbose_name='មតិមាតាបិតា (ឆ.២)')),
                ('discipline_annual', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អ', max_length=20, verbose_name='ការគោរពវិន័យ (ប្រចាំឆ្នាំ)')),
                ('diligence_annual', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អ', max_length=20, verbose_name='ការខិតខំប្រឹងប្រែង (ប្រចាំឆ្នាំ)')),
                ('moral_annual', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អណាស់', max_length=20, verbose_name='សីលធម៌ សុជីវធម៌ (ប្រចាំឆ្នាំ)')),
                ('hygiene_annual', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អ', max_length=20, verbose_name='អនាម័យ និងបរិស្ថាន (ប្រចាំឆ្នាំ)')),
                ('social_annual', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អ', max_length=20, verbose_name='សកម្មភាពសង្គម/ពលកម្ម (ប្រចាំឆ្នាំ)')),
                ('overall_annual', models.CharField(choices=[('ល្អណាស់', 'ល្អណាស់ (Excellent)'), ('ល្អ', 'ល្អ (Good)'), ('ល្អបង្គួរ', 'ល្អបង្គួរ (Fairly Good)'), ('មធ្យម', 'មធ្យម (Average)'), ('ខ្សោយ', 'ខ្សោយ (Poor)')], default='ល្អ', max_length=20, verbose_name='មារយាទប្រចាំឆ្នាំ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_assessments', to='academics.academicyear', verbose_name='ឆ្នាំសិក្សា / Academic Year')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conduct_assessments', to='academics.classroom', verbose_name='ថ្នាក់រៀន / Classroom')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conduct_evaluations', to='teachers.teacher', verbose_name='វាយតម្លៃដោយគ្រូ / Evaluated By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_assessments', to='students.student', verbose_name='សិស្ស / Student')),
            ],
            options={
                'verbose_name': 'ការវាយតម្លៃអាកប្បកិរិយា & មារយាទ',
                'verbose_name_plural': 'ការវាយតម្លៃអាកប្បកិរិយា & មារយាទ',
                'ordering': ['student', 'academic_year'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
