# Generated by Django 6.1 on 2026-09-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0025_studentconductassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconductassessment',
            name='parent_comment_monthly',
            field=models.TextField(blank=True, default='', verbose_name='មតិមាតាបិតា (ប្រចាំខែ)'),
        ),
        migrations.AddField(
            model_name='studentconductassessment',
            name='teacher_comment_monthly',
            field=models.TextField(blank=True, default='', verbose_name='មតិគ្រូបន្ទុកថ្នាក់ (ប្រចាំខែ)'),
        ),
    ]
